### ISSUE TITLE
Akka.Persistence.Sqlite Fails to DeleteMessages When Processing High Traffic of Messages

### ISSUE THREAD

**Issue by arturosevilla** [akkadotnet/akka.net#3538] opened 2018-07-06 06:14 UTC
When receiving lots of messages as part of a AtLeastOnceDelivery pattern we sometimes get (but consistently) the following exception:

```
Failed to DeleteMessages ToSequenceNr [6800] for PersistenceId ["ReliableMailboxActor.UpstreamMessageRouter"] due to: ["Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked'.
   at Microsoft.Data.Sqlite.Interop.MarshalEx.ThrowExceptionForRC(Int32 rc, Sqlite3Handle db)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at System.Data.Common.DbCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Akka.Persistence.Sql.Common.Journal.AbstractQueryExecutor.<DeleteBatchAsync>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Akka.Persistence.Sql.Common.Journal.SqlJournal.<DeleteMessagesToAsync>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Akka.Util.Internal.AtomicState.<CallThrough>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Akka.Util.Internal.AtomicState.<CallThrough>d__8.MoveNext()": "SQLite Error 5: 'database is locked'."]
```

This happens on a .NET 4.6 environment.

The class that handles the messages works similarly to the following code:

```csharp
public class ReceiverActor : ReceivePersistentActor
{
    private const int DefaultSnapshotSize = 100;
    private readonly int _snapshotSize = 0;
    private int _messagesSinceSnapshot = 0;

    public static Props Props(string actorId, int? snapshotSize = null)
    {
        return Akka.Actor.Props.Create(
            () => new ReliableMailboxActor(actorId, snapshotSize ?? DefaultSnapshotSize));
    }

    public ReceiverActor(string actorId, int snapshotSize)
    {
        _snapshotSize = snapshotSize;

        PersistenceId = nameof(ReceiverActor) + "." + actorId;

        // Recover<Message>();

        Recover<SnapshotOffer>(snapshot => RecoverFromSnapshot(snapshot));

        Command<SaveSnapshotSuccess>(success =>
        {
            DeleteMessages(success.Metadata.SequenceNr);
        });

        Command<SaveSnapshotFailure>(failure =>
        {
            // log it
        });


        Command<Message>(message => HandleMessage(message));
    }

    private void RecoverFromSnapshot(SnapshotOffer snapshot)
    {
        // recover state from snapshot
    }

    private void SaveSnapshotOnThreshold<T>(T message, Action<T> messageHandler)
    {
        messageHandler(message);
        if (++_messagesSinceSnapshot % _snapshotSize == 0)
        {
            SaveSnapshot(GetCurrentMessages());
        }
    }

    private List<Message> GetCurrentMessages()
    {
        // retrieves the current messages from actor state
    }

    private void HandleMessage(Message message)
    {
        Persist(message,
            e => SaveSnapshotOnThreshold(e, entry => ProcessMessage(message))));
    }

    private void ProcessMessage(Message message)
    {
        // store the message in actor state
    }

    public override string PersistenceId { get; }
}
```

You can notice that the general behavior is that the journal is used, however after a certain amount of messages a snapshot is created (hence the `DeleteMessages()` call).

**Comment by Aaronontheweb** [comment] 2018-08-01 16:55
This is a confirmed bug; wrote a reproduction spec for it here: https://github.com/Aaronontheweb/Akka.Persistence.Sqlite-concurrency-repro/

Long story short, with the way SQLite's file-locking mechanism works it's not possible to run both the SQLite snapshotstore __and__ journal at the same time without running into a file locking issue. If I need to write or delete a snapshot at the same time the journal is persisting messages, one of those two operations will fail - and thus far in my reproducer it's the snapshot store that fails the 100% of the time. 

I think this is because the snapshots are only being saved intermittently whereas the journal is being used constantly, but the fact that we can't use both the journal and the snapshotstore at the same time with SQLite seems like a problem to me.

I'll look into what we could do to solve this in the C# code itself but there may not be that much we can do without temporally coupling the snapshot store and the journal together. 

### Work-around
As a work-around in the short run, you could use different database files for the snapshot store and the journal. The HOCON configuration would 

```
 akka {
    persistence.journal {
        plugin = ""akka.persistence.journal.sqlite""
        sqlite {
            class = ""Akka.Persistence.Sqlite.Journal.BatchingSqliteJournal, Akka.Persistence.Sqlite""
            plugin-dispatcher = ""akka.actor.default-dispatcher""
            table-name = event_journal
            metadata-table-name = journal_metadata
            auto-initialize = on
            connection-string = ""Datasource=journal.db;""
        }
    }

    persistence.snapshot-store{
        plugin = ""akka.persistence.snapshot-store.sqlite""
        sqlite{
            class = ""Akka.Persistence.Sqlite.Snapshot.SqliteSnapshotStore, Akka.Persistence.Sqlite""
            plugin-dispatcher = ""akka.actor.default-dispatcher""
            auto-initialize = on
            connection-string = ""Datasource=snapshot-store.db;""
        }
    }
}
```

**Comment by to11mtm** [comment] 2018-11-23 20:47
I think this issue has been fixed in the newer Microsoft.Data.SQLite package.

When I run the repro with the provided package version I get errors.

If I upgrade the Microsoft.Data.SQLite package to 2.1.0, I don't see any issues running the repro.

If I use System.Data.SQLite And shim out a Persistence provider for it based off the existing SQLite provider, I don't get any errors.

System.Data.SQLite has behavior where if the database file is locked when a command executes, it will wait up until `CommandTimeout` for the file to unlock (If you're running in Debug mode, SDS will write the lock warnings out to the console;) I believe that Microsoft.Data.SQLite does attempt similar but their implementation has changed a bit over the last year.

I can submit a patch for bumping up the version if that would help...

**Comment by Aaronontheweb** [comment] 2018-11-24 03:41
Go for it

**Comment by Aaronontheweb** [comment] 2020-10-26 00:28
I think this may be fixed already either via some of the Sqlite driver upgrades

**Closed by Aaronontheweb** 2020-10-26 00:28 UTC
Labels: akka-persistence, confirmed bug
