### ISSUE TITLE
Akka DistributedData not getting replicated

### ISSUE THREAD

**Issue by huzaifak** [akkadotnet/akka.net#4348] opened 2020-03-18 22:17 UTC
When creating a new issue, please make sure the following information is part of your issue description. (if applicable). Thank You!

- Which Akka.Net version you are using
1.4.2

- On which platform you are using Akka.Net
.Net 4.7, windows 10.

- A list of steps to reproduce the issue. Or an gist or github repo which can be easily used to reproduce your case.
The error is observed after the singleton node is stopped which causes the singleton to fail over to another node once the original node joins back in the cluster this error is observed.  
Akka Logs:

2020-03-17 18:18:44.9761 Akka.Remote.EndpointReader Serializer not defined for message with serializer id [6] and manifest []. Transient association error (association remains live). The type or method has 2 generic parameter(s), but 1 generic argument(s) were provided. A generic argument must be provided for each generic parameter.
2020-03-17 18:18:47.9763 Akka.Remote.EndpointWriter AssociationError [akka.tcp://JobDispatcherSystem@laxqax-mtir4001.office.com:9901] <- akka.tcp://JobDispatcherSystem@laxqax-mtir4002.office.com:9901: Error [Exception has been thrown by the target of an invocation.] [   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Akka.DistributedData.Serialization.ReplicatedDataSerializer.ORDictionaryDeltaGroupFromProto(ORMapDeltaGroup deltaGroup)
   at Akka.DistributedData.Serialization.ReplicatedDataSerializer.ORMultiDictionaryDeltaFromBinary(Byte[] bytes)
   at Akka.Serialization.Serialization.Deserialize(Byte[] bytes, Int32 serializerId, String manifest)
   at Akka.DistributedData.Serialization.ReplicatorMessageSerializer.DataEnvelopeFromProto(DataEnvelope proto)
   at Akka.DistributedData.Serialization.ReplicatorMessageSerializer.DeltaPropagationFromBinary(Byte[] bytes)
   at Akka.Serialization.Serialization.Deserialize(Byte[] bytes, Int32 serializerId, String manifest)
   at Akka.Remote.Serialization.MessageContainerSerializer.FromBinary(Byte[] bytes, Type type)
   at Akka.Serialization.Serialization.Deserialize(Byte[] bytes, Int32 serializerId, String manifest)
   at Akka.Remote.DefaultMessageDispatcher.Dispatch(IInternalActorRef recipient, Address recipientAddress, Payload message, IActorRef senderOption)
   at Akka.Remote.EndpointReader.<Reading>b__11_0(InboundPayload inbound)
   at lambda_method(Closure , Object , Action`1 , Action`1 , Action`1 )
   at Akka.Tools.MatchHandler.PartialHandlerArgumentsCapture`4.Handle(T value)
   at Akka.Actor.ReceiveActor.ExecutePartialMessageHandler(Object message, PartialAction`1 partialAction)
   at Akka.Actor.UntypedActor.Receive(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)]
2020-03-17 18:18:47.9919 Akka.Remote.ReliableDeliverySupervisor Association with remote system akka.tcp://JobDispatcherSystem@laxqax-mtir4002.office.com:9901 has failed; address is now gated for 5000 ms. Reason is: [System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidCastException: Unable to cast object of type 'AddDeltaOperation[System.String]' to type 'Akka.DistributedData.ORSet`1[System.String]'.
   at Akka.DistributedData.Serialization.ReplicatedDataSerializer.<>c__DisplayClass95_0`2.<GenericORDictionaryDeltaGroupFromProto>g__MapEntryFromProto|0(MapEntry entry)
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Immutable.ImmutableDictionary`2.AddRange(IEnumerable`1 items, MutationInput origin, KeyCollisionBehavior collisionBehavior)
   at System.Collections.Immutable.ImmutableDictionary`2.AddRange(IEnumerable`1 pairs, Boolean avoidToHashMap)
   at System.Collections.Immutable.ImmutableDictionary.ToImmutableDictionary[TSource,TKey,TValue](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Akka.DistributedData.Serialization.ReplicatedDataSerializer.GenericORDictionaryDeltaGroupFromProto[TKey,TValue](ORMapDeltaGroup deltaGroup)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Akka.DistributedData.Serialization.ReplicatedDataSerializer.ORDictionaryDeltaGroupFromProto(ORMapDeltaGroup deltaGroup)
   at Akka.DistributedData.Serialization.ReplicatedDataSerializer.ORMultiDictionaryDeltaFromBinary(Byte[] bytes)
   at Akka.Serialization.Serialization.Deserialize(Byte[] bytes, Int32 serializerId, String manifest)
   at Akka.DistributedData.Serialization.ReplicatorMessageSerializer.DataEnvelopeFromProto(DataEnvelope proto)
   at Akka.DistributedData.Serialization.ReplicatorMessageSerializer.DeltaPropagationFromBinary(Byte[] bytes)
   at Akka.Serialization.Serialization.Deserialize(Byte[] bytes, Int32 serializerId, String manifest)
   at Akka.Remote.Serialization.MessageContainerSerializer.FromBinary(Byte[] bytes, Type type)
   at Akka.Serialization.Serialization.Deserialize(Byte[] bytes, Int32 serializerId, String manifest)
   at Akka.Remote.DefaultMessageDispatcher.Dispatch(IInternalActorRef recipient, Address recipientAddress, Payload message, IActorRef senderOption)
   at Akka.Remote.EndpointReader.<Reading>b__11_0(InboundPayload inbound)
   at lambda_method(Closure , Object , Action`1 , Action`1 , Action`1 )
   at Akka.Tools.MatchHandler.PartialHandlerArgumentsCapture`4.Handle(T value)
   at Akka.Actor.ReceiveActor.ExecutePartialMessageHandler(Object message, PartialAction`1 partialAction)
   at Akka.Actor.UntypedActor.Receive(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Akka.Actor.ActorCell.HandleFailed(Failed f)
   at Akka.Actor.ActorCell.SysMsgInvokeAll(EarliestFirstSystemMessageList messages, Int32 currentState)]

**Comment by Aaronontheweb** [comment] 2020-03-24 17:16
Where is the data not being replicated? That's not clear from this error message.

**Comment by huzaifak** [comment] 2020-03-24 17:22
The data doesnt get replicated on the non singleton node joining the cluster. And later if the same node is made the singleton any entries set in the ddata collections return a success. But the replicator doesn't invoke the changed message notification to the actor registered to monitor for changed items.

**Comment by Arkatufus** [comment] 2020-05-05 21:03
@huzaifak This might have been fixed in Akka.NET 1.4.5. can you check this?

**Comment by huzaifak** [comment] 2020-05-05 21:09
it cannot be in 1.4.5 since i report it with 1.4.5.
    On Tuesday, 5 May, 2020, 02:03:46 pm GMT-7, Gregorius Soedharmo <notifications@github.com> wrote:  
 
 


@huzaifak This might have been fixed in Akka.NET 1.4.5. can you check this?

**Comment by Arkatufus** [comment] 2020-05-05 21:13
But you said you're using 1.4.2 in your original report?

**Comment by Arkatufus** [comment] 2020-05-05 21:15
@huzaifak But you said you're using 1.4.2 in your original report?

**Comment by huzaifak** [comment] 2020-05-05 21:18
i am sorry i was think about https://github.com/akkadotnet/akka.net/issues/4400.We are currently using 1.4.5 and still can reproduce it. not sure if having the fix for 4400 will resolve this as well.
    On Tuesday, 5 May, 2020, 02:15:18 pm GMT-7, Gregorius Soedharmo <notifications@github.com> wrote:  
 
 


@huzaifak But you said you're using 1.4.2 in your original report?

**Comment by Arkatufus** [comment] 2020-05-05 21:27
@huzaifak The reason I asked is that the exception message pointed at `ReplicatedDataSerializer.ORMultiDictionaryDeltaFromBinary()` and a specific generic invocation bug, and I recalled that the fix should already be deployed in 1.4.5. Are you sure that this is still reproducible in 1.4.5 with the same exact exception message?

**Comment by huzaifak** [comment] 2020-05-06 00:40
No, the error have changed.

On Singleton
2020-05-05 16:16:51.8481 Akka.Actor.EmptyLocalActorRef Message [WriteAck] from akka.tcp://JobDSystem@laxqax-mtir4002.office.com:9901/user/ddataReplicator to akka://JobDSystem/user/ddataReplicator/$b was not delivered. [1] dead letters encountered .This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.

On other node:
2020-05-05 17:39:31.2941 Akka.Actor.OneForOneStrategy Unable to cast object of type 'Akka.DistributedData.ORDictionary`2[System.ValueTuple`2[System.Guid,System.UInt16],Akka.DistributedData.LWWRegister`1[IStreamSessionPayloadProgress]]' to type 'Akka.DistributedData.LWWDictionary`2[System.ValueTuple`2[System.Guid,System.UInt16],IStreamSessionPayloadProgress]'

**Comment by Arkatufus** [comment] 2020-05-06 14:06
OK, that's #4400, and it should be fixed on the next version.
We'll leave this issue open just in case it wasn't, but I'm pretty sure that will be fixed by #4401.

**Comment by Aaronontheweb** [comment] 2020-05-08 16:09
@Arkatufus @huzaifak so it looks like DData confused an ORDictionary for an LWWDictionary? This is because we were using ORDictionaryDeltas under the covers and they weren't cast correctly upon deserialization?

**Comment by Arkatufus** [comment] 2020-05-13 18:22
No, its 2 different bugs happening in the same code. They're not related

**Comment by Arkatufus** [comment] 2020-05-13 20:44
@huzaifak can you see if the exceptions are cleared using 1.4.6? If it does, we can close this issue.

**Comment by huzaifak** [comment] 2020-05-13 21:07
we upgraded this morning and so far don't see any error related to the replication. Our QA is performing more tests if something fails i can update the thread. 
Thanks for taking care of this.

**Comment by Arkatufus** [comment] 2020-05-14 08:38
We can close this issue then, please open another one if you found a different problem.

**Closed by Arkatufus** 2020-05-14 08:38 UTC
Labels: akka-ddata, discussion, potential bug
