### ISSUE TITLE
Akka.Persistence.Sql.Common.Journal - JournalDbEngine Not Thread Safe

### ISSUE THREAD

**Issue by Zetanova** [akkadotnet/akka.net#1398] opened 2015-11-03 18:19 UTC
LinkedList.Remove() is not Thread safe and will Fail with a NullReferenceException under load.

**Comment by Horusiath** [comment] 2015-11-04 08:55
The problem lies in the PendingOperations list of journal engine, which is mutated from async tasks themselves, causing race conditions. This part should be redesigned - journal engine state mutations should not be shared or occur inside tasks.

**Comment by Horusiath** [comment] 2015-11-05 07:31
The problem is existence of `PendingOperations` list itself - it's not necessary for us. Actually what we might want to do is to cleanup all pending database tasks once we are stoping/restarting the journal - for this we need only one shared cancellation token source that will be used for all database calls and canceled at `PostStop` journal method.

**Comment by Danthar** [comment] 2015-11-12 20:51
Closing this issue: A PR was merged

**Closed by Danthar** 2015-11-12 20:51 UTC
Labels: akka-persistence, confirmed bug, ready, up for grabs
