### ISSUE TITLE
ConfigureAwait(false) all async/await stuff

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#886] opened 2015-04-22 09:41 UTC
It's a good practice anyway, so in order to prevent for mysterious deadlocks in synchronous code using async API (in example `IActorRef.Ask` method) we should add `ConfigureAwait(false)` to all of our task-based operations exposed as async methods.

**Comment by rogeralsing** [comment] 2015-04-22 10:35
Are you sure?
lets say I have an `ReceiveActor` with an `async` receive handler.
and lets assume this receive handler calls `.Ask` on another actor.
Will that returned task complete outside of the asking actors TaskScheduler?

**Comment by rogeralsing** [comment] 2015-04-22 10:58
Changing the Ask method to:

```
        public static Task<T> Ask<T>(this ICanTell self, object message, TimeSpan? timeout = null)
        {
            var t = AskProxy<T>(self, message, timeout);
            t.ConfigureAwait(false);
            return t;
        }

        private static async Task<T> AskProxy<T>(ICanTell self, object message, TimeSpan? timeout)
        {
            IActorRefProvider provider = ResolveProvider(self);
            if (provider == null)
                throw new NotSupportedException("Unable to resolve the target Provider");

            ResolveReplyTo();
            var result = (T) await Ask(self, message, provider, timeout);
            return result;
        }
```

Still passes all the tests.
But TBH, I have no clue if this change makes anything better in any way.
Would the above solve the deadlock issue you saw @Horusiath ?

**Comment by Aaronontheweb** [comment] 2015-04-22 18:10
@rogeralsing `ConfigureAwait(false)` is generally good idea inside libraries and frameworks - we had to do this EVERYWHERE inside the MarkedUp SDK. This is one of the stupid / evil default behaviors `await` introduced to our otherwise glorious concurrent programming libraries.

**Comment by rogeralsing** [comment] 2015-04-22 18:18
The semantics of it is pretty unclear to me at least, exactly how does this affect async state and schedulers?

Skickat från min iPhone

**Comment by kekekeks** [comment] 2015-04-22 18:32
@rogeralsing
```
        public static Task<T> Ask<T>(this ICanTell self, object message, TimeSpan? timeout = null)
        {
            var t = AskProxy<T>(self, message, timeout);
            t.ConfigureAwait(false);
            return t;
        }
```
`t.ConfigureAwait(false);` here does nothing. This method doesn't modify the Task, it returns [ConfiguredTaskAwaitable](https://msdn.microsoft.com/en-us/library/system.runtime.compilerservices.configuredtaskawaitable%28v=vs.110%29.aspx) that can be awaited.

**Comment by nvivo** [comment] 2015-04-22 18:38
Correct me if I'm wrong, but I think the point is that Akka.net currently requires the existing behavior to store the actor context for continuations. If that changes, some other way to store the context is required.

**Comment by kekekeks** [comment] 2015-04-22 18:42
Does it always need that context internally? I mean, the user code will still use `await` directly on `Task` and won't be affected. And the only place that allows user to safely use `await` has it's own SynchronizationContext anyway.

**Comment by rogeralsing** [comment] 2015-04-22 21:14
>Does it always need that context internally? 

The problem is that we have an ambient context which holds things like `Sender`, `Self` and a bunch of other things.
If the continuations run w/o that context being present a lot of features will break. e.g. you cant send messages to Sender or create new children.

**Comment by annymsMthd** [comment] 2015-04-23 02:02
Have you tried not using .Wait or .Result to see if the deadlock is resolved? It is good practice to never use these because of deadlocking. Most of the new .net frameworks make it easy to pull async / await all the way through the stack.

**Comment by Horusiath** [comment] 2015-04-23 05:46
Problem is that you're not always able to use async/await all the way through. There are situations when you simply have to work with synchronous code, and this is wat this issue is all about.

**Comment by nvivo** [comment] 2015-04-23 10:00
> There are situations when you simply have to work with synchronous code

@Horusiath do you mean some people working with old libraries inside akka?

**Comment by rogeralsing** [comment] 2015-04-23 13:21
Im all ok with making it work for sync code, as long as it doesnt kill the mechanics if the async code ofc :)

**Comment by Aaronontheweb** [comment] 2015-04-23 18:11
Added this to the v1.0.1 release

**Comment by nvivo** [comment] 2015-04-23 19:20
Sorry for the stupid question, but what will be done for 1.0.1?
Add ConfigureAwait(false) everywhere? Is there a solution for keeping the context?

**Comment by Aaronontheweb** [comment] 2015-04-23 19:21
@nvivo this milestone https://github.com/akkadotnet/akka.net/milestones/Akka.NET%20v1.0.1%20bugfix%20release

**Comment by nvivo** [comment] 2015-04-23 19:25
I meant what will be done *about this issue*. It seems there is no solution yet.

**Comment by gabikliot** [comment] 2015-04-25 04:06
If you do :
1: // my code calls some async func and gets task1 back
2: await  task1.ConfigureAwait(false);
3: // my code continues to do something with my state

the line 3 now runs not in the same context as line 1. 
The “context” can be different things:
In ASP.Net or UI apps it is the famous `SynchronizatonContext.`
Inside actors it is the TPL `TaskScheduler`.
If it is important to you to stay on line 3 in the same Task scheduler as on line 1, you do **NOT** want to execute `ConfigureAwait` here. And I presume it is important to you, otherwise you would not guarantee single threaded execution within the actor.
In your example @rogeralsing line 3 just returned a task, and basically did nothing, so you did not notice the context escaping.
The next time you awaited that task, you got back to the context, because the next (outer) await was started in the correct context.

The solution to avoid deadlocks is to never ever write synchronous code inside grains. On the client, in UI threads, ConfigureAwait(false) is indeed usefull.

**Comment by rogeralsing** [comment] 2015-04-25 05:11
@gabikliot thanks! that was what I expected.

Can anyone explain **why** or when asp.net would/could deadlock on a call like this:

```csharp
var result = someActor.Ask<SomeResult>(someMessage).Result;
```

If the asp.net code runs om thread `A` and then blocks while waiting for the result.
and the `TaskCompletionSource` inside Ask is eventually set in thread `B`
How can it be that thread `A` does not get resumed here?

There is no continuation to resume or schedule here and there already is a thread waiting to resume execution.

I _really_ want to understand the mechanics of this stuff :-)

**Comment by nvivo** [comment] 2015-04-25 11:14
Currently the deadlock happens because Ask has an "async/await" mechanism. This is the classic issue of trying to wrap async inside sync code.

In your example:

```cs
var result = someActor.Ask<SomeResult>(someMessage).Result;
```

For reference, the code of `Ask`:

```cs
public static async Task<T> Ask<T>(this ICanTell self, object message, TimeSpan? timeout = null)
{
	IActorRefProvider provider = ResolveProvider(self);
	if (provider == null)
		throw new NotSupportedException("Unable to resolve the target Provider");

	ResolveReplyTo();
	var result = (T)await Ask(self, message, provider, timeout);
	return result;
}
```

The flow is:

1. `someActor.Ask` is running in the asp.net synchronization context and sees this line:<br />
	`var result = (T)await Ask(self, message, provider, timeout);`
2. that `Ask` returns an incomplete task
3. because we're in an async method, the async FSM will schedule a continuation **in the current synchronization context** to execute the rest of the method and **returns immediately the new incomplete continuation task**, not the task it is waiting and will complete in another thread
4. you call `.Result` still in the same thread you started, blocking the only thread the sync context has to run it's continuations

There is your deadlock.

So it doesn't really matter that the TaskCompletionSource is set in another thread. That task is fine and is completed. The issue is that you're waiting for the task created by the async state machine, and that one never gets completed because it cannot run.

If the same code was running in a console app, the continuation would be scheduled on the Thread Pool and everything would be fine.

**Comment by rogeralsing** [comment] 2015-04-25 11:27
So what can be done to resolve the problem here?
We need to keep the semantics when asking from within an actor.
And when asking from the outside, we need code that works with the current synchronization context, right?

**Comment by nvivo** [comment] 2015-04-25 12:27
The solution was given by @gabikliot: "The solution to avoid deadlocks is to never ever write synchronous code inside grains."

That means the problem is on the *caller*, not on the *callee*.

Whoever waits for tasks should be using `await`, not `.Result`. `.Result` works in cases when you're not bound to a single thread, `await` *always* works. In other words, `.Result` is a workaround for legacy code, not a solution. It has some blocking cost that should be avoided.

So, from the ASP.NET just change methods to be `async` and  `await` for Asks. If that is not possible for some reason, the solution is to use `ContinueWith` instead of `.Result`.

From Akka, either use `ReceiveActor<T>(async value => ...)` or `ContinueWith`.

Now if you need an async result to return from a sync method that is bound to a single thread and you cannot change anything, you're out of luck. Wait for libraries to be updated and support that feature or don't depend on asyncrhonous code for that specific piece of code.

**Comment by kekekeks** [comment] 2015-04-25 12:31
>So what can be done to resolve the problem here?

Call `ConfigureAwait(false)` on the task returned by another `Ask` overload before awaiting. Or just use `ContinueWith(... , ExecuteSynchroniously)` to avoid unnecessary scheduling on ThreadPool thread.

**Comment by rogeralsing** [comment] 2015-04-25 12:51
@kekekeks how can that be, if @gabikliot just explained that calling configureawait false will break the context? or did I misunderstand him?

**Comment by kekekeks** [comment] 2015-04-25 12:54
In this particular case the context is not needed. The only thing that continuation does is casting the returned object to `T`. You don't need any context to do this.
The rule of the thumb: if you don't access any contexts after `await`, you can safely use `ConfigureAwait(false)` or `ContinueWith` (ContinueWith is better, because you can avoid unnecessary scheduling)

**Comment by rogeralsing** [comment] 2015-04-25 12:56
I think I have to declare myself officially beaten by the TPL, anyone that actually understands the details for the inner workings here are free to submit a fix, assuming no API or Tests break ofc.

**Comment by rogeralsing** [comment] 2015-04-25 22:54
Closing this as @kekekeks's PR have been merged and seems to fix the problem.
Feel free to re-open incase there are broken edgecases.

**Closed by rogeralsing** 2015-04-25 22:54 UTC
Labels: discussion, enhancement, up for grabs
