### ISSUE TITLE
Existing test cases started failing with timeout exception after upgrating from akka 1.4.31 to 1.5.13

### ISSUE THREAD

**Issue by sachindevtomar** [akkadotnet/akka.net#6990] opened 2023-11-14 08:42 UTC
Getting below error while executing test case with ExpectMsg

Failed: Timeout 00:00:05 while waiting for a message of type 

below is the test case for the same
```
public void AddAccessKeyTest()
        {
            var bridge = probe.ActorOf<Obj1<Obj2>>();
            bridge.Tell(Props.Create<Obj3>(), TestActor);

            ExpectMsg<TestMessage<Obj2>>(TimeSpan.FromSeconds(100));
        }
```

**Comment by Aaronontheweb** [comment] 2023-12-08 14:10
@sachindevtomar this might be related to the changes we made to the testkit which made it asynchronous under the hood. 

So in this case, it's taking 5 seconds instead of 100? That's the issue?

cc @Arkatufus

**Comment by Arkatufus** [comment] 2023-12-08 15:53
I could not reproduce this, even when using the same exact code shown (repro attempt at #7020).

@sachindevtomar are you sure you're not calling another `ExpectMsg` inside of the bridge actor receive handler?

**Comment by sachindevtomar** [comment] 2023-12-10 12:48
Hello,

It was the issue related to some dependent nuget packages which needed to
be included for akka test case execution.

Thanks for your response.

Kind regards,
Sachin Dev Tomar

**Comment by Aaronontheweb** [comment] 2023-12-11 21:34
@sachindevtomar thanks for letting us know. We'll close this issue.

**Closed as not planned by Aaronontheweb** 2023-12-11 21:34 UTC
Labels: potential bug, akka-testkit
