### ISSUE TITLE
Stack trace not preserved when unhandled exception gets sent to a Supervisor strategy

### ISSUE THREAD

**Issue by stevemesser** [akkadotnet/akka.net#1501] opened 2015-12-04 15:37 UTC
I did a quick look at the source and I found at least one exception throwing problem.

First I am not a JVM guy but with the little research I did I found out that the JVM and .NET handle the throwing and rethrowing of exceptions opposite of each other.

http://www.tkachenko.com/blog/archives/000352.html

    private void HandleFailed(Failed f) //Called handleFailure in Akka JVM
    {
         if (statsUid == f.Uid)
         {
             var handled = _actor.SupervisorStrategyInternal.HandleFailure(this, f.Cause, childStats,   ChildrenContainer.Stats);
             if (!handled)
                  throw f.Cause; // This is probably at least one of the culprits
         }
    }

You probably want to look into ExceptionDispatchInfo.Capture(...).Throw()  as it maintains the stack trace

**Comment by Danthar** [comment] 2015-12-04 15:52
Duplicate of #1499

**Closed by Danthar** 2015-12-04 15:52 UTC

**Comment by stevemesser** [comment] 2015-12-04 15:55
They should be combined  if possible. Mine has some background info
