### ISSUE TITLE
Akka.DistributedData.Replicator System.InvalidCastException: - while trying to prapogate deltas

### ISSUE THREAD

**Issue by huzaifak** [akkadotnet/akka.net#3759] opened 2019-04-16 17:28 UTC
Version of Akka being used as below.
<package id="Akka" version="1.3.12" targetFramework="net47" />
  <package id="Akka.Cluster" version="1.3.12" targetFramework="net47" />
  <package id="Akka.Cluster.Tools" version="1.3.12" targetFramework="net47" />
  <package id="Akka.DistributedData" version="1.3.12-beta" targetFramework="net47" />
  <package id="Akka.DistributedData.LightningDB" version="1.3.12-beta" targetFramework="net47" />
  <package id="Akka.Logger.NLog" version="1.3.3" targetFramework="net47" />
  <package id="Akka.Remote" version="1.3.12" targetFramework="net47" />
  <package id="Akka.Serialization.Hyperion" version="1.3.12-beta" targetFramework="net47" />
  <package id="Akka.Streams" version="1.3.12" targetFramework="net47" />

Reproducible on windows 10/windows 2012 server for testing, using .net 4.7.2.

Steps to reproduce:
1. Create a akka cluster. 
2. Create an distributed collection of type ORDictionary<string, Isomeinterface>, but i think any type will do. 
3. Add some items in the collection on the singleton 
4.  Modify an existing item in the collection, we use the below code to do the update on the collection.

var c = Cluster.Get(context.ActorSystem);
var r = DistributedData.Get(context.ActorSystem);
var a = await r.Replicator.Ask<IUpdateResponse>(Dsl.Update(_RegistryKey, ORDictionary<TKey, TVal>.Empty, consistency, m => m.AddOrUpdate(c, key, value, old => value)));

5. Once the replicator sends a request on the other server for delta replication the below exception is logged in the logs.

Akka.DistributedData.Replicator Couldn't process DeltaPropagation from [UniqueAddress: (akka.tcp://someservice@server.domai.com:9901, 446825355)] due to System.InvalidCastException: Unable to cast object of type 
'PutDeltaOperation[System.String, Test.IConfiguration]' to type 'Akka.DistributedData.ORDictionary`2[System.String,Test.IConfiguration]'.
   at Akka.DistributedData.ORDictionary`2.Merge(IReplicatedData other)
   at Akka.DistributedData.Internal.DataEnvelope.Merge(IReplicatedData otherData)
   at Akka.DistributedData.Internal.DataEnvelope.Merge(DataEnvelope other)
   at Akka.DistributedData.Replicator.Write(String key, DataEnvelope writeEnvelope)
   at Akka.DistributedData.Replicator.WriteAndStore(String key, DataEnvelope writeEnvelope, Boolean reply)
   at Akka.DistributedData.Replicator.ReceiveDeltaPropagation(UniqueAddress from, Boolean reply, ImmutableDictionary`2 deltas)

By looking at the code the error is being raised by the below line in ORDictionary.cs.
  
  public IReplicatedData Merge(IReplicatedData other) => Merge((ORDictionary<TKey, TValue>)other);

HOCON config used is as below.

akka {
	loggers = ["Akka.Logger.NLog.NLogLogger, Akka.Logger.NLog"]
	loglevel = INFO
	stdout-loglevel = INFO
	extensions = ["Akka.Cluster.Tools.PublishSubscribe.DistributedPubSubExtensionProvider, Akka.Cluster.Tools", "Akka.DistributedData.DistributedDataProvider, Akka.DistributedData"]
	cluster-dispatcher {
		type = ForkJoinDispatcher
		dedicated-thread-pool {
			thread-count = 8
			threadtype = background
		}
	}
	ddata-dispatcher {
		type = ForkJoinDispatcher
		dedicated-thread-pool {
			thread-count = 8
			threadtype = background
		}
	}
	actor {
		provider = "Akka.Cluster.ClusterActorRefProvider, Akka.Cluster"
		serializers {
			hyperion = "Akka.Serialization.HyperionSerializer, Akka.Serialization.Hyperion"
		}
		serialization-bindings {
			"System.Object" = hyperion
		}
		deployment {
			/jobeventstore-reader-router-pool {
				router = round-robin-pool
				resizer {
					enabled = on
					lower-bound = 1
					upper-bound = 4
				}
			}
			/jobeventstore-updater-router-pool {
				router = round-robin-pool
				resizer {
					enabled = on
					lower-bound = 1
					upper-bound = 4
				}
			}
			/notification-sender-router-pool {
				router = round-robin-pool
				nr-of-instances = 4
				cluster {
					enabled = on
					allow-local-routees = on
					max-nr-of-instances-per-node = 2
				}
			}
		}
		debug {
			receive = on 
			autoreceive = on
			lifecycle = on
			event-stream = on
			unhandled = on
		}
	}
	remote {
		enabled-transports = ["akka.remote.dot-netty.tcp"]
		log-remote-lifecycle-events = INFO
		dot-netty.tcp {
			transport-protocol = tcp
			tcp-reuse-addr = off
			enforce-ip-family = true
			public-hostname = "mymachine.office.cyberu.com"
			hostname = "0.0.0.0"
			port = 9901
			ssl {
				suppress-validation = true
				certificate {
					path = "SomeAkkaSystem.cer"
				}
			}
			maximum-frame-size = 1048576b
		}
	}
	cluster {
		debug {
			verbose-heartbeat-logging = on
		}
		use-dispatcher = akka.cluster-dispatcher
		seed-nodes = ["akka.tcp://SomeAkkaSystem@machine4001.office.cyberu.com:9901","akka.tcp://SomeAkkaSystem@machine4002.office.cyberu.com:9901","akka.tcp://SomeAkkaSystem@machine4003.office.cyberu.com:9901"]
		gossip-interval = 1s
		allow-weakly-up-members = on
		downing-provider-class = "Akka.Cluster.SplitBrainResolver, Akka.Cluster"
		down-removal-margin = 10s
		split-brain-resolver {
			active-strategy = static-quorum
			stable-after = 10s
			static-quorum {
				quorum-size = 2
			}
		}
		failure-detector {
			heartbeat-interval = 1s
			acceptable-heartbeat-pause = 30s
		}
		singleton {
			singleton-name = "CoreSingletonManager"
			hand-over-retry-interval = 1s
			min-number-of-hand-over-retries = 8
		}
		singleton-proxy {
			singleton-name = "CoreSingletonManager"
			singleton-identification-interval = 1s
			buffer-size = 1024
		}
		pub-sub {
			gossip-interval = 1s
			removed-time-to-live = 30s
			max-delta-elements = 128
		}
		distributed-data {
			use-dispatcher = akka.ddata-dispatcher
			gossip-interval = 15s
			serializer-cache-time-to-live = 120s
			delta-crdt {
				enabled = on
				max-delta-elements = 512
			}

		}
	}
}

**Comment by Aaronontheweb** [comment] 2020-10-27 15:27
@Arkatufus added this to our most recent sprint

**Comment by Arkatufus** [comment] 2020-10-28 23:39
This could be an old bug, I couldn't reproduce the problem anymore.

Here's a unit test I've used to try and recreate it:

Unit test:
https://github.com/Arkatufus/akka.net/blob/%233759_Proof_of_concept/src/contrib/cluster/Akka.DistributedData.Tests/ReplicatorSpecs.cs#L161-L200

Class:
https://github.com/Arkatufus/akka.net/blob/%233759_Proof_of_concept/src/contrib/cluster/Akka.DistributedData.Tests/ReplicatorSpecs.cs#L629-L674

**Comment by Aaronontheweb** [comment] 2020-10-28 23:52
We will close it out then

**Closed** 2020-10-28 23:52 UTC
Labels: akka-ddata, potential bug

**Comment by Arkatufus** [comment] 2020-10-29 00:42
@huzaifak you can re-open this issue if you're still having problems
