### ISSUE TITLE
Akka.IO.Tcp Write ack event received early

### ISSUE THREAD

**Issue by jaydeboer** [akkadotnet/akka.net#3997] opened 2019-10-18 16:38 UTC
# Intro

We are running Akka.net 1.3.15 in a Linux docker container and are using the ```Write Create(ByteString data, Event ack)``` API to know when a message has been acknowledged by the receiver before we close the connection to the receiver.  Using WireShark, we noticed that most often the write is sent, then the close, then the ack for the write.  Occasionally we see the Write, ack, close sequence we expected.  We have added a 50 ms delay between the write and the close to keep the events in order.  

# Sample Code
Here is a snippet of of the pattern we are using, the class is not complete, but the important bits should be there.

```csharp

        public class SampleActor : ReceiveActor
        {

            public SampleActor()
            {
                /// <snip>
                Receive<string>(_ => OnReceiveFullMessage());
                Receive<ResponseWritten>(_ => OnResponseWritten());
            }

            private IActorRef _connection;

            private void OnReceiveFullMessage()
            {
                _connection.Tell(Tcp.Write.Create(ByteString.FromString($"OK\r\n"), ResponseWritten.Instance));
            }

            private void OnResponseWritten()
            {
                Context.System.Scheduler.ScheduleTellOnce(TimeSpan.FromMilliseconds(50), _connection, Tcp.ConfirmedClose.Instance, Self);
            }

            public class ResponseWritten : Tcp.Event
            {
                public static ResponseWritten Instance { get; } = new ResponseWritten();
            }
        }
```

# Expectation

I expected to receive the ```ResponseWritten``` message only after the TCP ack from the receiver, therefore eliminating the need for the 50ms delay.

**Comment by IgorFedchenko** [comment] 2019-11-05 13:45
@jaydeboer Indeed, `Ack` naming is correlating with tcp acknowledgment, so this is something you could expect - getting it after tcp acknowledgment received.

But looking at the `Tcp.Write` class documentation, you can see the following:
```csharp
/// <summary>
/// Write data to the TCP connection. If no ack is needed use the special
/// `NoAck` object. The connection actor will reply with a <see cref="CommandFailed" />
/// message if the write could not be enqueued. If <see cref="SimpleWriteCommand.WantsAck">Write.WantsAck</see>
/// returns true, the connection actor will reply with the supplied <see cref="Write.Ack" />
/// token once the write has been successfully enqueued to the O/S kernel.
/// <b>Note that this does not in any way guarantee that the data will be
/// or have been sent!</b> Unfortunately there is no way to determine whether
/// a particular write has been sent by the O/S.
/// </summary>
```

So, in your sample above you are receiving `ResponseWritten` earlier then message is delivered to receiver, and this is by design.
To give more details - akka sends `Ack` message after internal `socket.Send` call is executed and all your data has been sent. And here is what [official docs](https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.socket.send?view=netframework-4.8#System_Net_Sockets_Socket_Send_System_Byte___) says about this:
`There is also no guarantee that the data you send will appear on the network immediately. To increase network efficiency, the underlying system may delay transmission until a significant amount of outgoing data is collected. A successful completion of the Send method means that the underlying system has had room to buffer your data for a network send.`

So technically .net does not give us any information about whether your data was delivered to receiver node.

Also, in general, my personal advice would be to send some confirmation message from receiver right after message is received by remote actor. Low-level delivery would not guarantee that your data was actually delivered to the receiver - lots of things can happen on that remote end until the actor will get your message from his message box. (There was a great note about that somewhere in Akka.NET docs, related to delivery guarantee).
Of course I do not know your business requirements, so maybe at-most-once delivery is still something you are ok with.

**Comment by IgorFedchenko** [comment] 2019-12-06 16:20
@Aaronontheweb I guess we can consider this issue as a question, and it is answered. Let's close it.

@jaydeboer Feel free to ask for any additional help/fix here, if required.

**Closed** 2019-12-06 16:22 UTC
