### ISSUE TITLE
Potential Resource Leaks with Akka.Clustering?

### ISSUE THREAD

**Issue by BrainSlugs83** [akkadotnet/akka.net#1597] opened 2015-12-21 09:21 UTC
Hey guys,

I have a cluster with 3 nodes in it -- and it runs blazing fast when I first deploy it -- and after two days of sitting idle (no other interaction or work being done by the system), and it's very sluggish (unacceptably slow, actually).

I've noticed in the Akka logs, about every 10 seconds, like clockwork, something like this:

    now supervising akka://System/system/transports/akkaprotocolmanager.tcp.0/akkaProtocol-tcp%3a%2f%2fSystem%4010.237.146.72%3a49588-426

    Started (Akka.Remote.Transport.ProtocolStateActor)

The number at the end of the first line auto-increments (i.e. 10 seconds later, and it's started -427, and then, -428, etc. etc.)

I never see any mention in the logs of these actors getting shutdown or unwatched -- so I guess there could be some "actor leak" here? (i.e. tons of actors getting created and never shut down...)

**Comment by annymsMthd** [comment] 2016-03-09 08:24
I'm not able to reproduce this. Is there a simple setup you can do that will produce the reoccurring log messages?

**Comment by Aaronontheweb** [comment] 2016-06-21 16:01
This has been found and fixed in #2090

**Comment by Aaronontheweb** [comment] 2016-06-21 17:54
Closed by #2090

**Closed by Aaronontheweb** 2016-06-21 17:54 UTC
Labels: akka-cluster, critical, potential bug
