### ISSUE TITLE
AkkaDotNet Persistence (SQLite) fails in v 1.4.3 but works in v 1.3.17 

### ISSUE THREAD

**Issue by AzureGulf** [akkadotnet/akka.net#4360] opened 2020-03-27 09:33 UTC
My UnTypedPersistentActor or ReceivePeristentActor (have tried both) never completes recovery on start-up so subsequently fails whenever I try to persist anything.
All I can see is the error message "OnRecoveryFailure reason=Recovery timed out, didn't get snapshot within 30s" when overriding the OnRecoveryFailure method.
Oddly, if I change my Hocon timeout to say 25s, the error message is still 30s. 
Using Akka.net / Akka.Persistence / Akka.Persistence.SQLite 1.4.3 and Hyperion 0.9.15 on UWP.
Works fine in version 1.3.17
2 Git repos on AzureGulf, one for each version of Akka - private repos, invitation set to Aaronontheweb - just let me know if I should invite others.
Suggest you run v 1.3.17 first so that you see the app's Persist message, then compare with v 1.4.3

**Comment by Aaronontheweb** [comment] 2020-03-27 20:32
Thanks, I'll take a look

**Comment by Aaronontheweb** [comment] 2020-03-28 01:29
So I created a reproduction spec here using your exact config in Akka.NET v1.4.3 and it passes: https://github.com/akkadotnet/akka.net/pull/4361

I think the issue you're running into is this bugfix from v1.4.1: https://github.com/akkadotnet/akka.net/pull/4313

We fixed a bug that caused some Akka.Persistence.Sqlite settings to not be loaded correctly - the default fallback values weren't loaded correctly, and worst of all: we had a hard-coded snapshot store table name that couldn't be changed via configuration.

We changed all of that in 1.4.1 and that's why your old data isn't being loaded: because we fixed the bug.

You can see my colleague @Arkatufus 's warning about that here on https://github.com/akkadotnet/akka.net/pull/4313

> This might be a breaking change for users that copy pasted sqlite journal configuration from a sample that contains a `table-name = not_called_snapshot` entry because it will start to use the property declaration instead of using the hard coded `snapshot` table.

So the fix in your case would be, if you needed to load the previous data, to change your HOCON to this:

```
akka.persistence.snapshot-store.sqlite.table-name = snapshot-store
```
I wasn't able to easily run either of your solutions - even after installing 10Gb of UWP Visual Studio add-ons. But I worked backwards from the code and made a reproduction in #4336 

**Please check both of those PRs, try to change the table-name for the snapshot store, and let us know if the issue persists**.

**Comment by AzureGulf** [comment] 2020-03-28 08:14
Thanks for looking at this.
I've changed the snapshot table name as below and run in the 1.4.3 repo but same problem - nothing gets written to the event journal nor snapshot store (events should be written on creating an (stream processing) object and snapshot when exiting the app.
When loading the app, I show the hocon string on the console, as below:
>>>>>>>>>>>>>>>> in task: await Windows.Storage.StorageFile.GetFileFromApplicationUriAsync(uri); ...
hoconString=
akka
{
actor {
deployment {
.....
.....
sqlite {
class = "Akka.Persistence.Sqlite.Snapshot.SqliteSnapshotStore, Akka.Persistence.Sqlite"
plugin-dispatcher = "akka.actor.default-dispatcher"
connection-string = "DataSource=AkkaSnapShotfxR16.db"
connection-timeout = 25s
table-name = snapshot-store
auto-initialize = on
}
.....
.....
but still get this error message from the Persist actor (on startup):
    10:42:14 from actor:/user/PersistSPO:
..  .......in PersistSPO >> OnRecoveryFailure reason=Recovery timed out, didn't get snapshot within 30s.<=

I've attached a couple of screenshots showing the difference between the 1.4.3 and 1.3.17 versions of the app (basically the Persist messages).
Please let me know if I should try anything else or have misunderstood your instructions (incorrect change to my hocon?).
ps 
- there is no need to reload old data for either these test repos
- code for both repos exactly the same just Akka packages different and new change to hocon in 1.4.3

![TestPersistUWP Akka 1_4_3 2020-03-28 105346](https://user-images.githubusercontent.com/18535145/77818517-1b3c1c00-70e4-11ea-924f-a1ccfce26522.jpg)

![TestPersistUWP Akka 1_3_17 2020-03-28 105346](https://user-images.githubusercontent.com/18535145/77818524-27c07480-70e4-11ea-864f-bc6965c4b2fb.jpg)

**Comment by Aaronontheweb** [comment] 2020-03-30 17:19
@AzureGulf got it, thanks - this is helpful. It's not what I thought it was then.

Do you have any error logs from the journal itself that you can somehow capture? If there's a serialization problem under the covers, that could certainly cause this kind of issue. That's something we changed between 1.3.17 and 1.4.1 but it should be backwards compatible.

**Comment by Aaronontheweb** [comment] 2020-03-30 17:22
Another distinct possibility is we made major upgrades to the SQLite driver:

https://www.nuget.org/packages/Akka.Persistence.Sqlite/1.3.18 - targets 1.1.1
https://www.nuget.org/packages/Akka.Persistence.Sqlite/1.4.3 - targets 3.1.2

I have no idea what the impact of those are on UWP because we don't test against that platform. Would need the same data that we have above to find out - logs from the snapshot store and journal system actors, not from the user-defined actors.

**Comment by Aaronontheweb** [comment] 2020-03-30 18:00
This could also be a related possibility https://github.com/akkadotnet/akka.net/issues/4353

**Comment by Arkatufus** [comment] 2020-03-30 18:54
@AzureGulf  Can you try and change your config to:
`akka.persistence.snapshot-store.sqlite.table-name = snapshot`
and see it if works?

**Comment by AzureGulf** [comment] 2020-03-31 07:31
@Arkatufus tried table-name = snapshot ; no change (same Persist 30 seconds error) with Akka 1.4.3

@Aaronontheweb - have amended my hocon to include logging
(as per docs: https://getakka.net/articles/utilities/logging.html)
but am not sure how to assign output for the StandardOutLogger, as I don't see anything when running the app.
Apologies for my ignorance, but please let me know how to configure this to output to the UWP Output window or a (txt) file.

Please note:
UWP "threw away" the Console (I think they have added back some console/command line capability) which means for any App level logging, you need to add the System.Diagnostics namespace and use Debug.Write etc for output to the Output window. However, this only works when debugging - no output for Release apps.
A quick look at some Akka source (src/core/Akka/Util/StandardOutWriter.cs), makes me think you're using the standard System.Console throughout.

**Comment by Arkatufus** [comment] 2020-03-31 14:02
The 30s timeout value is correct, that is the default.
The timeout value is taken from `akka.persistence.journal.sqlite.recovery-event-timeout` hocon field.

**Comment by Aaronontheweb** [comment] 2020-03-31 15:35
@AzureGulf if you can write the logs out to a file by configuring a Serilog or NLog logger, that would be very helpful: https://getakka.net/articles/utilities/logging.html#contrib-loggers

**Comment by Arkatufus** [comment] 2020-03-31 16:01
Based on [this](https://github.com/dotnet/efcore/issues/17613), it seems like this problem was not caused by Akka, but by the way the new netstandard2.0 SQLite library. It seems like, in sandboxed applications such as the UWP, the SQLite library does not set the default directory and enforces this on the user.

Please update your Akka NuGet packages to the latest nightly build, and add these lines of codes just before you start the ActorSystem:
```
            SQLitePCL.Batteries_V2.Init();
            SQLitePCL.raw.sqlite3_win32_set_directory(1, Windows.Storage.ApplicationData.Current.LocalFolder.Path);
            SQLitePCL.raw.sqlite3_win32_set_directory(2, Windows.Storage.ApplicationData.Current.TemporaryFolder.Path);
```

**Comment by Aaronontheweb** [comment] 2020-03-31 17:36
@AzureGulf please let us know if the Sqlite suggestions from @Arkatufus help and we'll close the issue or continue from there.

**Comment by AzureGulf** [comment] 2020-04-01 03:16
@Arkatufus thanks! All worked fine with your additional SQLite PCL lines of code after installing Akka latest stable 1.4.4
Installed Serilog (and Serilog.Sinks.File as no output to Sinks.Console) and have attached 2 files, one with successful Persist recovery and update, the other showing Persist failure (exactly same code but with your 3 SQLite PCL lines of code commented out).
Log clearly shows the SQLite error code 14.
Just a suggestion: could Akka bubble up these internal exceptions to the App?
(I tried wrapping "SqlitePersistence.Get(AkkaDotNet.AkkaSys);" in a 'try catch' but no exception caught.)

@Aaronontheweb appreciate your prompt response and patience - cheers!

[TestPersistUWP_Serilog_Akka1_4_4_PersistFail.log](https://github.com/akkadotnet/akka.net/files/4412570/TestPersistUWP_Serilog_Akka1_4_4_PersistFail.log)

[TestPersistUWP_Serilog_Akka1_4_4_PersistOK.log](https://github.com/akkadotnet/akka.net/files/4412571/TestPersistUWP_Serilog_Akka1_4_4_PersistOK.log)

**Comment by Aaronontheweb** [comment] 2020-04-01 14:29
> Just a suggestion: could Akka bubble up these internal exceptions to the App?

All of the exceptions are fairly self-contained inside the actors - that's one of the benefits of using them, so we won't be able to do that.

Glad we were able to help!

**Closed by Aaronontheweb** 2020-04-01 14:29 UTC
Labels: akka-persistence, potential bug
