### ISSUE TITLE
JObject transport integer replacements

### ISSUE THREAD

**Issue by mrn-aglic** [akkadotnet/akka.net#4463] opened 2020-06-08 19:48 UTC
Not sure if this is by design. But could use some help.
I'm using Akka, Akka.Cluster and Akka.Cluster.Tools version 1.4.7. 
Using Newtonsoft.Json 12.0.3.

I'm using Akka.NET with .Net Core 3.1 on a OS X laptop. 

I wanted to integrate an example web api that would use ClusterClient to communicate with a Cluster. The issue I have is passing a JObject from Cluster to the API project (ClusterClient to be more specific). As I can see the integers are replaced with JObjects

```
{
  "Id": {
    "$": "I2"
  },
  "Firstname": "ivo",
  "Lastname": "ivic",
  "Jmbag": "1432",
  "Email": "email@email.com",
  "Ects": {
    "$": "I40"
  },
  "IsEnrolled": true
}

```
Json looks normal on the Cluster end produced with JObject.FromObject(some_object).
I assume that this is the default behaviour for network transporation. However, I have not found mention of it in the docs, nor an example on how to handle it. 
Additionally, I don't understand why integers needed to be replaced. 

I'm using ClusterClinet.Ask<JObjectWrapperClass>(...) to get the object. The "problem" is not in the wrapper class, as the same thing happens when receiving JObject without it.

**Comment by Aaronontheweb** [comment] 2020-06-11 13:26
@mrn-aglic would you mind posting a small reproduction sample of the POCOs so we can see what exactly the input is?

**Comment by mrn-aglic** [comment] 2020-06-11 22:19
@Aaronontheweb I published the example project here: 
https://github.com/mrn-aglic/exercise-example/tree/master

**Comment by Aaronontheweb** [comment] 2023-03-10 17:18
Closing this - looks like we do it by design, per this comment:

https://github.com/akkadotnet/akka.net/issues/6502#issuecomment-1464116324

**Closed by Aaronontheweb** 2023-03-10 17:18 UTC
Labels: potential bug, serialization
