### ISSUE TITLE
Sending large message remotely fails with akka.net 1.3.4 and dotnetty 0.4.7

### ISSUE THREAD

**Issue by serpentthegreen** [akkadotnet/akka.net#3327] opened 2018-02-15 14:09 UTC
Sending large message via remoting with akka.net 1.3.4 and dotnetty 0.4.7 results in DotNetty.Codecs.TooLongFrameException.

For example, If I serialize message using Serializer.ToBinary (json serializer), it  produces 280650 bytes array. 
Sending it via Tell results in DotNetty.Codecs.TooLongFrameException: Adjusted frame length exceeds 10485760: 1549548106 - discarded

Rolling back dotnetty to 0.4.6 fixes the issue.

**Comment by Aaronontheweb** [comment] 2018-02-15 15:22
Hi @serpentthegreen - thanks for reporting this. I think Akka.Remote still uses DotNetty 0.4.6 by default, but I'm glad you reported this issue. I'll see if there's an issue that we need to report back to the DotNetty guys.

**Comment by Aaronontheweb** [comment] 2018-02-15 15:50
FYI, looks like this issue with DotNetty has already been fixed here: https://github.com/Azure/DotNetty/pull/326 - they just haven't pushed a new package since.

**Comment by Aaronontheweb** [comment] 2018-02-15 15:50
@serpentthegreen would you mind building the DotNetty latest `dev` sources and trying that out to see if you can still reproduce the issue? I'm sure they'll push a new release with these fixes included if that's the case.

**Comment by serpentthegreen** [comment] 2018-02-15 16:35
No issue with dev build, so  Azure/DotNetty#326 is the fix.

**Comment by Aaronontheweb** [comment] 2018-02-15 16:39
Thanks, appreciate you verifying that. We'll upgrade to the next version of DotNetty that has that patch incorporated whenever it's released. Looks like DotNetty v0.5.0, which isn't binary compatible with ~v0.4.*

**Comment by serpentthegreen** [comment] 2018-02-15 16:42
You are welcome.

**Comment by AndreSteenbergen** [comment] 2018-05-18 10:31
I am on 1.3.7 and I have this issue as well. I know I have some large messages in the system. But I can't think about messages of 1.7gb. So Iguess we are all waiting for the 0.5.0 dotnetty release?

Cause: DotNetty.Codecs.TooLongFrameException: Adjusted frame length exceeds 25600000: 1734430758 - discarded

**Comment by Danthar** [comment] 2018-05-18 10:54
Its already part of the 0.4.8 release

**Comment by AndreSteenbergen** [comment] 2018-05-18 11:50
Aaron states waiting for 0.5.0 in that link. The release 1.3.7 hinted reverting back to 0.4.6 solves this. but it doesn't

**Comment by Aaronontheweb** [comment] 2018-05-18 12:58
DotNetty moved a bunch of these fixes into v0.4.8, which we're still testing.

Are you running on Linux? v0.4.6 still has some framing issues there on .NET Core - those should be solved by the v0.4.8 upgrade.

**Comment by AndreSteenbergen** [comment] 2018-05-18 13:58
Actually, linux ACC/ PRD and Windows DEV, windows looks all fine.

**Comment by Aaronontheweb** [comment] 2018-05-31 15:21
Alrighty, ran DotNetty v0.4.8 continuously for close to 48 hours. No memory issues et al to speak off. Looks like it's good to go for v1.3.8 and should resolve this issue. Closing the ticket.

**Closed by Aaronontheweb** 2018-05-31 15:21 UTC
Labels: akka-remote, dotnetty, potential bug
