### ISSUE TITLE
Router not terminated when broadcasting PoisonPill if there is an Exception in routee which is handled using supervisorstrategy

### ISSUE THREAD

**Issue by bibekdw** [akkadotnet/akka.net#3597] opened 2018-09-18 15:28 UTC
Hi,

When one of the routee throws exception, my actor is not receiving Terminated message for the router being death watched even after broadcasting PoisonPill to the router. The exception is handled with supervisorstrategy with Resume Directive. If I don't throw the exception and handle with try catch in routee, router Terminated message is received just fine. Am I missing something here?

- using 1.3.9
- using on windows
- gist @ https://gist.github.com/bibekdw/d7f841b254520e47d07be0d111d15c35

Thanks.

**Comment by Aaronontheweb** [comment] 2018-10-02 14:40
Thanks @bibekdw - I'll be looking into this

**Comment by Aaronontheweb** [comment] 2018-10-03 23:12
You have indeed found something odd here.... Modified your gist some.

https://gist.github.com/Aaronontheweb/15fd90ff517027c6e4d7c00e4a87fc80

```
[INFO][10/3/2018 11:12:15 PM][Thread 0025][[akka://ActorSystem/user/$a/Consumer#285462192]] Router has 78 remaining routees
```

Router only kills off 22 of its routees with the `Broadcast(PoisonPill.Instance)`... I'm going to tweak the sample a bit more and see what's up.

**Comment by Aaronontheweb** [comment] 2018-10-03 23:15
I wonder if some of the code that we was proposed in this PR might shed a clue on this... Definitely appears to be related to the `Directive.Resume`: https://github.com/akkadotnet/akka.net/pull/2433

**Comment by Aaronontheweb** [comment] 2018-10-03 23:17
Oh wow.... In the case of restarting the actor none of the routees were killed off.

**Comment by Aaronontheweb** [comment] 2018-10-03 23:51
Ah, I know why that is:

Routee --> Router --> Consumer --> Coordinator is the structure of the hierarchy in this sample. The error escalates ALL THE WAY to the Coordinator from an individual routee.

The supervision decision being issued here is at the level of the Coordinator --> Consumer. When I use `Directive.Restart`, the Coordinator kills off the old instance of its router and re-creates it. That's why we end up with 100 routees at the end - they're a different 100 routees than what we had originally.

Now as for why there's only 22 routees killed (that number is consistent) when we use a `Directive.Resume`, I think that's because due to your modulus there are only 22 actors of the 100 routees who never receive a value where % 5 == 0. If I change your modulus statement to N % 1, the entire router dies. If I change it to N  % 2, only 48 routees remain. 

I think what you're seeing here is that the `Directive.Escalate` instruction results in the routees having their mailboxes suspended but the `Directive.Resume` status never gets propagated down the supervision chain back to the original, suspended actor who threw the exception in the first place. It seems pretty clear to me that this is what's going on.

`Directive.Escalate` is normally coupled with `Directive.Restart`, which would work fine in this case as it effectively reboots the entire supervision underneath the actor who escalated.

The issue here is the combination of `Directive.Escalate` and `Directive.Resume` - we'd need to add code to propagate the `Directive.Resume` all the way back down the stack again to make this work, since `Directive.Escalate` __locks the parent actor__. Escalate == "I am treating this child's failure as my own," not "I am delegating the supervision of my child to my parent."

I'll take a look at the `ActorCell` code around supervision. We should automatically resume suspended children in the event that we ourselves get `Directive.Resume`-d but your reproduction code makes it appear as though this isn't happening. I'll also take a look at that closed PR we never merged.

**Comment by Aaronontheweb** [comment] 2018-10-16 21:01
Oh man, yeah, that looks like another bug. Thanks for reporting that too.

**Comment by Aaronontheweb** [comment] 2018-10-18 02:00
I was finally able to reproduce this in a spec. So the suspend / resume semantics work fine up and down the food chain (tested that) when done in sequence, but if I _interleave_ normal messages and ones that produce failures in routee children together this causes the issue you described here to appear.

Makes me think this might be an issue with concurrent access to the pool router's `ChildContainer` collection and the suspend / resume semantics not being properly balanaced when the _router itself is supposed to be in a suspended state_ when it escalates.

**Comment by Aaronontheweb** [comment] 2018-10-23 19:56
I'm going to keep looking into this some, but just as an FYI @bibekdw - there's a reasonable chance I'm going to mark this as "won't fix." It's _old_ code and this the first time it's been reported. If the fix looks like it's going to be invasive or expensive, I might have to do that simply because the economics of the change aren't all that good. Just want to set that expectation now in case that's what we find as I dig in.

**Comment by bibekdw** [comment] 2018-11-02 22:47
Understood

**Closed** 2020-02-12 04:22 UTC
Labels: akka-actor, won't fix
