### ISSUE TITLE
Snapshot Store breaks and never recovers if an error occurs during its initialization

### ISSUE THREAD

**Issue by ondrejpialek** [akkadotnet/akka.net#3665] opened 2018-11-29 09:47 UTC
Using `Akka` 1.3.9 and `Akka.Persistence.SqlServer` 1.3.7.

There is an issue with the Snapshot Store plugin that if there is a failure during its initialization it will not attempt to reinitialize and will remain in a broken state until the Actor System is restarted.

We have noticed the following sequence of events twice in production already:

- The DB connectivity is lost
- Snapshot Store fails to load snapshots
- Its circuit breaker opens
- Unsure what the store does here, probably re-attempts to connect?
- The store attempts to initialize (note: we have automatic initialization turned on, which if I understand the code correctly is a requirement to experience this issue)
- The store fails to initialize and remains forever in a broken state, causing entities to throw `Akka.Persistence.RecoveryTimedOutException` (Recovery timed out, didn't get snapshot within 30s.)
- The DB comes back online but the store will keep timing out

Screenshot:
![image](https://user-images.githubusercontent.com/580850/49212908-68f72600-f3c3-11e8-8cd9-f2edbc2c11bf.png)

I believe that for this to happen the `auto-inititalize` option is required. It is possible the same happens without that option but I have not tested that (and I doubt it looking at the source code).

**Comment by Aaronontheweb** [comment] 2019-08-01 16:59
Closed as dupe of #3870

**Closed by Aaronontheweb** 2019-08-01 16:59 UTC
