### ISSUE TITLE
Underlying Actor code exception causes disassociation

### ISSUE THREAD

**Issue by skills0** [akkadotnet/akka.net#1841] opened 2016-03-31 20:00 UTC
I've run into the following issue on multiple occasions when trying to get a simple Cluster working. My specific use case is I have 2 nodes, both seed nodes and they are basically set up at the Actor level (outside Akka) to play either the active or passive role. Various use cases can trigger a failover from one node to the other (some Akka-related triggers, some our our Actor code). This generally works fairly well, but I'm running into cases where the following happens.

1. Some unhandled error occurs in the Actor code (C#), which throws an Association error (from Akka.Remote.EndpointWriter.PublishAndThrow. A for instance is Json throws an exception on an object in a message I'm trying to send between nodes.

2. This either causes gating or in some cases breaks up the cluster entirely.

So hopefully I'm missing something, but I don't see a way to add a handler for these types of exceptions and take care of them to prevent any issues with the cluster.

To me, the right pattern would be something like the EndpointWriter.PublishAndThrow instead checks the exception to see if it is an Akka type (can't remember if you have an interface IAkkaException or base class, something like that). If not, it should attempt to send a message to the Actor and carry on with the normal clustering code as normal. If there was a standard exception message I could Receive on, then at least I could potentially fix the issue or handle it more gracefully. 

At the very least, it would make my logs cleaner and help clearly show the issue without breaking up my cluster. Granted it would be great if my code never threw an exception, but I'm not quite that much of a genius yet :-)

**Comment by Aaronontheweb** [comment] 2016-04-04 22:41
> A for instance is Json throws an exception on an object in a message I'm trying to send between nodes.

You have a serialization exception here. JSON.NET is notorious for being bad with C#6 auto properties and the like and we will be switching to Wire as the default serializer for reasons like this.

Try that instead: https://gist.github.com/Aaronontheweb/b96ec974eb6bd6354f4e

In terms of the remoting system: not a bug. Expected and desired behavior. If the underlying connection can't serialize or deserialize a message, the actors are designed to blow the entire thing up and restart. Hence why the Erlang and Akka philosophy is called "let it crash."

In terms of the gating and endpoint management issues: those are definitely bugs and we have numerous issues open for them. Working on it personally. Closing this one for now.

**Closed by Aaronontheweb** 2016-04-04 22:41 UTC
Labels: akka-remote, potential bug
