### ISSUE TITLE
Mark internal classes -- particularly in the internals namespace -- as such

### ISSUE THREAD

**Issue by SeanKilleen** [akkadotnet/akka.net#651] opened 2015-02-19 13:36 UTC
Per #633 and @Aaronontheweb, the first step towards interface renaming would be to get more restrictive and mark internal classes as such, particularly beginning with those in the "Internals" namespace.

**Comment by rogeralsing** [comment] 2015-02-19 15:37
If I recall correctly, @HCanber made everything the artefacts under the "internals" namespace public so that they can be used in tests for the framework itself.
Much like the Scala version have the "Dungeon" namespace.

**Comment by sean-gilliam** [comment] 2015-02-19 17:00
Just a suggestion, but maybe change them back from being public to being internal. Then mark the Internals assembly with 
```csharp
[assembly:InternalsVisibleTo("<<assembly name>>")]  
```
for each assembly that needs access to that assembly. Granted it may include every assembly in the solution.

**Comment by rogeralsing** [comment] 2015-02-19 17:14
This would require each module to know about every future potential new module.
e.g. Akka.dll would have to know about Akka.Persistence.dll etc if any of the child modules use one of the internal interfaces.

IMO we should just do as they do in Scala Akka, tell users that the internals namespace is hands off and at your own risk. Or name that namespace something more frightening :)

**Comment by Aaronontheweb** [comment] 2015-02-19 17:43
@rogeralsing there's some system internals that should be off limits - for instance I marked the `RouterActor` as internal yesterday because even for user-defined routers the developer isn't supposed to be able to access or modify this class directly.

The `.Internals` namespace has some stuff in it that can probably be marked as off limits, but you're right - a lot of that is intended to be used inside user-defined AkkaSpecs.

I'd propose that we mark everything `internal` that is marked as `private[akka]` in JVM Akka. At least that way we'll have a consistent view of what's really meant to be surfaced to an end-user or not.

As for the `.Internals` namespace - probably best to propose specific things to mark as internal here rather than sending a PR for it right away.

**Comment by HCanber** [comment] 2015-02-23 07:00
The reason for why I argumented for a public Internals namespace had nothing with `InternalsVisbleTo` or visibility to tests.

The most common reason to make things internals is _"I don't think you should be using that"_.

I've lost track of how many times I've installed a framework via Nuget, or used one of Microsofts apis in the .Net Framework, and wanted to tweak it just a tiny little bit. But I wanted to do it in a way the developers had not anticipated. The only way to tweak it is to download the source and modify it, or decompile and reimplement a bunch of classes (that were internal).

So by not making things internal (and instead putting them in a specific namespace) we allow people to do those things. They can extend the framework for their own projects in ways we never thought of. Because _"I don't think you should be using that"_ is a guess that's more often wrong than right.

The second reason for making things internals is _"We don't want to expose this as public api and take responsibility for it"_. That's why things in the Internals namespace are marked with __"Note! Part of internal API. Breaking changes may occur without notice. Use at own risk."__

The third reason is to _protect users from doing illegal or potential dangerous operations_. I don't think we have any of those in Akka.

**Comment by Aaronontheweb** [comment] 2015-02-23 18:36
I think @HCanber has the right idea. I was wrong.

**Comment by nvivo** [comment] 2015-02-24 01:00
If I may say so, from an user point of view, I think its quite strange to have a "internals" namespace exposed this way.

I agree with @HCanber that extensibility is very important, and I also had this problem of trying to extend MS stuff, but their problem is that [they usually seal things for reasons](http://stackoverflow.com/questions/268251/why-seal-a-class/268287#268287) that seem like an old way of thinking, more suited to commercial software where any public API  is something you need to commercially support.

But OSS projects doesn't suffer from that. Also, there are already a lot of plugins in Akka that give a good idea of what needs to be exposed for extensibility.

So, my point is that if you are just exposing things publicly, don't put that in an "internals" namespace. Just expose them publicly in the base namespace and if you need to change, you change it and announce the breaking change.  If you don't want to do that, don't expose it yet, keep it internal and wait to see what is needed.

I really don't see people trying to extend Akka and hitting walls because interfaces are not public. People that want to change the internals will just fork and do a PR. Also, remember that you are all core developers and have this complex framework in your heads. For you, it makes sense to expose a lot of stuff that most people will never touch.
 
As an user, I think it would be much better to reach 1.0 with a dry core that can be opened in future versions with a reliable API than having everything available publicly today with an unstable API that can break at any time.

**Comment by HCanber** [comment] 2015-02-24 08:20
The reason for putting them in the internals namespace is to show that it is normally things you shouldn't be using. If you are using things in there, and not knowing why, you're most likely doing something you shouldn't. We can come up with another name, like Advanced or something, but I think they should be separate from the other api. Having a separate namespace defeats exposing to much to the user at once.

> People that want to change the internals will just fork and do a PR

That might be true for people within the OSS community, but being quite new to this game, I know that for most devs that's not true. Many want to install everything via nuget, but still be able to fiddle with a thing or two; without having to fork and maintain their own copy (as the changes they want to do is something that really no one else will have any use of).

**Comment by ashutoshraina** [comment] 2015-02-24 09:16
I agree with @nvivo here. If there is something that can be extended then it should be explicitly public else it needs to be off limits from the user. If I am going to extend Akka I would rather do it at points where the author of the library gave me an explicit entry point. 

@HCanber I think the Advanced namespace might be a good idea. RavenDB probably has that too, for messing around with advanced configuration and stuff.

If someone is going to extend Akka.net to make Akka.net Streams (like Akka HTTP Streams) then they will probably use the advanced bits. If the provided mechanisms aren't good enough then like other OSS projects an issue should be raised to open up more things.

Just my 2 cents.

**Comment by HCanber** [comment] 2015-02-24 10:20
>If there is something that can be extended then it should be explicitly public else it needs to be off limits from the user

The problem is that it's extremely hard to know that on beforehand. Developers are creative and will come up with much more ways to extend and modify Akka than we can think of. Hindering them with "you have to submit an issue or PR and we will consider and possibly reject it" is not an good option.

An example:
Nancy is one the most extensible OSS projects out there. You can customize everything. However, a few weeks back I needed to write conneg a little bit differently than they had. Sure, Nancy is open for replacing the conneg with your own. But that wasn't really what I wanted. I wanted to reuse their Content Negotiation algorithm in a slightly new way, a way they never thought of. So I wanted to reuse what they had written, and only write what differed. The classes were internal so I that was not possible. In my day-to-day-work I cannot always take the route of waiting for updates, I need to solve the business problem asap, so I ended up using disassembled copies of all classes needed. I would have prefered to reuse what they had written, even under the presumption it could break at next update.

What's really the problem with opening up everything? 

If you don't want to fiddle with the internal advanced stuff, stay off the `Internals` namespace and stick to the public, stable api. If you want to use the internal stuff, it's there for you, right in the nuget package. It' is however not stable and can change at any time, much like if you built your modifications in a fork.

**Comment by nvivo** [comment] 2015-02-24 11:49
@HCanber,

Just to clarify, I don't see any problems with opening up everything. In fact, I completely agree with your reasons to make everything public.

My concern is just that it's strange to make it public but "leave a note" saying it's internal, because the language already has a way to express that. It's one of those cases where something just doesn't smell right - it's either trying to solve the wrong problem or trying to solve it the wrong way. 

The only reason to make an interface internal is if all types that implement or use it are also private/internal. Any other case, the compiler will complain. So, if you're already exposing it with a "public", it's part of your public API and needs to be public anyway. So, why try to mask it?

For example, looking at the "Akka.Actors.Internals" namespace, there are 4 files:

* ActorSystemImpl
* InitializableActor
* InternalCurrentActorCellKeeper
* InternalSupportsTestFSMRef

To me, it seems only the last one should be really internal. The rest could be renamed and exposed publicly. I could imagine myself extending an `Akka.Actors.DefaultActorSystem` instead of an `Akka.Actors.Internals.ActorSystemImpl` for example. And I'm not proposing this change, I'm just trying to say that if there is a reason to make them public, than maybe some of these internals are not that internal anyway. I'd move everything to the base namespace and use "internal" only if needed.

It's just naming and I agree it's not a big deal, but it's one of those things that I really care about, because good naming makes things easier to understand and reason about.

**Comment by HCanber** [comment] 2015-02-25 07:39
@nvivo I think we're in agreement on most things. :) Names can be better and many types that are in the internals namespace can be moved to the public one.

__Why public__
There are types that really are things the user normally wouldn't touch. You mentioned `InternalCurrentActorCellKeeper`. It should _not_ be moved out to the "normal" namespace. Setting `InternalCurrentActorCellKeeper.Current` when you don't know what you're doing can break the system completely. However, if you _do_ know what you are doing, then you might come up with a very legitimate reason for doing so. I can't think of any good reason now (it might be used to specify another implicit sender for example than the one currently in place), but I'm pretty sure that someone else might. 
If you come up with a reason, I want you to be able to do that, even when you're using the the nuget packages, without having to fork the code. That's why it's public. I think we're in an agreement on this part. :)

__Why Internals namespace__
But I also want us, as a team, to be able to modify how the current cell is stored, without having to provide a safe upgrade path for anyone using it.  It's there for advanced users to use, but as it really is the guts of Akka, we must be able to modify it. It's not really part of the public api. That's why it's in the `Internals` namespace, and that's why it's marked _INTERNAL! Part of internal API. Breaking changes may occur without notice. Use at own risk._ (I wished there were other attributes than `[Obsolete]` that would give a compile warning)

__Useful classes, but not really Akka__
Then there are classes that might be useful for a user using Akka, but really isn't part of what Akka solves. For example our implementation of `ImmutableAvlTree` or our CAS helpers in `InterlockedSpin`. If anyone wants to use them I think they should be able to do so. But do we really want to take on the full responsibility, with documentation, handling breaking changes, and so on as if they were part of the "real" public apia and part of what Akka solves? I'm not so sure. We need to discuss what to do with these classes.

__Advanced namespace?__
Some other classes that currently resides in the Internals namespace can be moved to the public part, as you say, but that I think still should be "hidden" in namespaces so that they do not confuse and overwhelm the users that only uses Akka.NET as-is. Maybe `Advanced` is better for these.


__When to use internal__
The only types I can think of that should be internal are the ones with extension methods that extends basic types like `int`, `string`, `IEnumerable`. `Akka.Util.Internal.Extensions` should not be visible to the outside, in my opinion.

**Comment by nvivo** [comment] 2015-02-25 13:47
@HCanber,

I think we agree on keeping things open instead of internal, but I still disagree on a key point. This is just my opinion and it's a little bit long, so take it as you want, I'm not trying to force anything, just expose a point of view.

My view is that Akka.NET is going to grow a lot after 1.0 and once docs are more robust, because it's a proven concept and there is nothing currently in the .NET ecosystem that achieves this so easily. It's a port of a famous library, so there is every reason to believe this is going to be a key project in .NET in the future. It's important for this code to be extensible and people should replace things and try new ideas with little friction.

So, IMHO I should be able to replace any part of akka with my own implementation at my own risk. This involves extending or replacing ActorSystem, Actors, mailboxes, dispatchers or any other core part I can't think of just by extending the existing classes and overriding a method or implementing an interface. There shouldn't be internal or sealed implementations in Akka for these things, and if my code breaks between versions, so be it. Maybe those are the things you classify as "advanced".

But things you mention like "Useful classes, but not really Akka" shouldn't. Because *Akka.dll is important enough that it should try to do only what it needs to do, and do it very well and in a very stable way*. Akka is not a general purpose helper library, and people shouldn't import Akka.dll to use things helper classes unrelated to akka.

It seem to me that by your definition, the line between what should and shouldn't be public is too blurry, and is governed not by extensibility points, but by fear that someone might not like the library if they download the nuget package and can't turn akka's guts inside out.

If the average Joe is not happy because he can't use your implementation of ImmutableAvlTree out of the box and he is too lazy to learn how to go the github repository and grab it from there, so what? It's not the purpose of Akka to provide those things, and trying to leave everything open like that is a recipe for maintenance hell.

So, my proposal is:

* Make any currently "internal" implementations related to Actors, ActorSystems, Mailboxes, etc, including any "*Impl" classes clearly public and out of some "internal/advanced" namespace.  Leave them public and extensible, rename them if needed. Those are the things people will want override and replace to try new things. Remove notes to "don't touch this", they are not needed. If Akka changes its implementation from version 1.0 to 2.0, that's normal and understandable and people will have to rewrite things.

* Some of the things that have notes like *INTERNAL! Part of internal API. Breaking changes may occur without notice* sound experimental, because you feel this should be public for some reason, but it's not clear if that's is good enough or even if that is useful. Experimental seems match this behavior better than "advanced", even so because you state that it may change at any time, so it's not clear even if Akka should use it like that. Some of those things should be just internal, and some should be in an Experimental namespace, and they should either upgrade to a public API on time or be removed. *A project of this importance should not expose things by fear* that someone might find useful. If things are useful outside of Akka, they should be kept internal and move to it's own project in time, just like Helios.

* Make any helper/extensions/data structures/test related classes `internal` and use assembly attributes to expose them for testing, and if people want to mess with that, let them grab the code from gihub and copy to their projects. If there is a legitimate use of an internal code, someone will bring it up as an issue or create a PR. If they don't want to go through that trouble, the project shouldn't support that. It's better for the project to keep its public surface clear and doing only what it's supposed to do.

Again, this is only my opinion, and I can't say there aren't edge cases to be accounted for. But to me this project is too important to not give some real thought about what should be exposed by the main library. Plugins may relax the constraints, but Akka.dll should be rock solid and know exactly what it's doing.

**Comment by sean-gilliam** [comment] 2015-02-26 04:28
I really like @nvivo's proposal.

**Closed** 2015-03-30 22:45 UTC
