### ISSUE TITLE
StreamRef deserialization doesn't work for serializers without manifest

### ISSUE THREAD

**Issue by NielsHoogeveen** [akkadotnet/akka.net#3620] opened 2018-10-14 20:31 UTC
In Akka 1.4 beta 4, when trying to deserialize a message with an associated serializer that does not have a string manifest (Hyperion, Newtonsoft), the serializer crashes in Akka.Streams/Serialization/StreamRefSerializer.cs at:
158                    var type = Type.GetType(manifest, throwOnError: true);

The reason is manifest == null.

Removing the if condition at line 214 - 219 seems to solve the issue:
214 if (serializer.IncludeManifest)
215            {
216                manifest = serializer is SerializerWithStringManifest s
217                    ? s.Manifest(payload)
218                    : payload.GetType().TypeQualifiedName();
219            }

When removing the if condition, manifest is no longer null.

**Comment by Horusiath** [comment] 2018-10-14 20:41
The problem is not on the serializer side (it's there for a reason), but rather on deserializer - see: https://github.com/akkadotnet/akka.net/blob/v1.4/src/core/Akka.Streams/Serialization/StreamRefSerializer.cs#L156

In `DeserializeSequenceOnNext` we should check for `IncludeManifest` as well - if it's false, it should be safe to use `FromBinary` with type param equal null. Therefore `Type.GetType(manifest)` should be called only when `serializer.IncludeManifest == true` and serializer itself is not SerializerWithStringManifest.

**Comment by Horusiath** [comment] 2018-10-15 06:47
EDIT: for deserialization, we probably should use [Serialization.Deserialize](https://github.com/akkadotnet/akka.net/blob/39d0d0037db0b8d990453836a8bb589bf1cd1805/src/core/Akka/Serialization/Serialization.cs#L203) method, which does exactly what we need.

**Comment by sean-gilliam** [comment] 2018-11-16 20:36
Closed via #3649

**Closed by sean-gilliam** 2018-11-16 20:36 UTC
Labels: akka-streams, confirmed bug
