### ISSUE TITLE
Cluster Broadcast-Group Router always returns a single routee

### ISSUE THREAD

**Issue by mmisztal1980** [akkadotnet/akka.net#2293] opened 2016-09-06 18:44 UTC
Hi all,

Seems like my issue might be related to [this issue](https://github.com/akkadotnet/akka.net/issues/2266)

I've been struggling with this for a while, so I've decided to reach out for help:

I've got 5 homogenous nodes (with the role **[servicediscovery]**) which are joining the cluster via a dedicated Lighthouse instance. Joining the cluster works as expected, however I have a problem with my actor's initialization.

Here's my nodes' config:
```
akka {
    actorsystem = "hive",
    
    actor { 
	    provider = "Akka.Cluster.ClusterActorRefProvider, Akka.Cluster"          
        deployment {
		    /services/broadcast {
			    router = broadcast-group
				routees.paths = ["/user/services"]				
                cluster {
				    enabled = on
                    max-nr-of-instances-per-node = 1
					allow-local-routees = off
					use-role = servicediscovery
				}
			}
		}                                                  
    }
            
    remote {
	    #log-remote-lifecycle-events = DEBUG
		helios.tcp {
		    transport-class = "Akka.Remote.Transport.Helios.HeliosTcpTransport, Akka.Remote"
			transport-protocol = tcp
			hostname = "127.0.0.1"
			port = 0
        }
    }
            
    cluster {
        seed-nodes = ["akka.tcp://hive@127.0.0.1:50000"]
        roles = [servicediscovery]
        role.servicediscovery.min-nr-of-members = 5
		loggers = ["Akka.Logger.Serilog.SerilogLogger, Akka.Logger.Serilog"]
        loglevel = INFO
    }
}
```

My actor is created as **/user/services** on each node. 

```c#
system.ActorOf<ServicesActor>(ServicesActor.ActorName); // ServicesActor.ActorName = "services"
```

During it's initialization cycle, I'm attempting to retrieve a list of it's cluster-siblings so that I may broadcast a message to them and await their responses.

*A fragment of my actor's code:*
```c#
private const string ClusterBroadcastRouterName = "broadcast";

protected override void PreStart()
{
    Cluster.Subscribe(Self,
    typeof(ClusterEvent.IMemberEvent),
    typeof(ClusterEvent.IReachabilityEvent));

    ClusterBroadcast = Context.Child(ClusterBroadcastRouterName).Equals(ActorRefs.Nobody)
        ? Context.ActorOf(Props.Empty.WithRouter(FromConfig.Instance), ClusterBroadcastRouterName)
        : Context.Child(ClusterBroadcastRouterName);
}
```

*Here's the way I'm trying to get the routees:*

```c#
var routees = ClusterBroadcast.Ask<Routees>(new GetRoutees()).Result.Members;
```
     
What happens is, the amount of routees returned, always equals one, despite having 5 homogenous nodes running at the same time. I haven't been able to determine the reason, therefore I need to ask for some guidance here.

**Comment by mmisztal1980** [comment] 2016-09-06 20:06
I've applied the config change to:

```
max-total-nr-of-instances = 10000
```

It seems to have made the difference. I'd apreciate if anyone could confirm that my overall approach and configuration are correct.

**Comment by mmisztal1980** [comment] 2016-09-06 20:20
Curious thing I've noticed:

This is my actors' initialization state:
```c#
 private void Initializing()
        {
            Log.Info("Initializing");
            initialized = false;

            if (IsRoleLeader)
            {
                Become(Ready);
                return;
            }

            Receive<ReceiveTimeout>(x => OnReceiveTimeout(x));

            Receive<SetServices>(x => OnServices(x));

            Receive<ClusterEvent.UnreachableMember>(x => OnUnreachableMember(x));

            Receive<Initialize>(x => OnInitialize(x));

            Self.Tell(new Initialize());
        }

        private void OnInitialize(Initialize msg)
        {
            Log.Info("{@Event}", msg);

            ack = ClusterBroadcast.Ask<Routees>(new GetRoutees()).Result.Members.Count();
            
            Context.SetReceiveTimeout(TimeSpan.FromSeconds(3));

            ClusterBroadcast.Tell(new GetServices());            
        }
```

While in this state, the actor is broadcasting a ```GetServices``` message, waiting for one of it's siblings (role leader) to respond. The logs confirm that one of the nodes is promoted to leader and becomes ```Ready``` however it never receives the message...

**Comment by Aaronontheweb** [comment] 2016-09-06 21:56
Duplicate of https://github.com/akkadotnet/akka.net/issues/2266

**Closed** 2016-09-16 23:29 UTC
