### ISSUE TITLE
RestartFlow.WithBackoff does not retry each element

### ISSUE THREAD

**Issue by vasily-kirichenko** [akkadotnet/akka.net#3225] opened 2017-12-23 19:40 UTC
There is a Source which generates a sequence of 1..10 ints and a Flow, which fails on numbers 6, 7 and 8. I want the `RestartFlow` to retry _each failing element_ according to it's configuration. But it does not retry elements, it just drop them and pick the next:

```fsharp
let system = ActorSystem.Create("test", config)
let mat = ActorMaterializerSettings.Create(system) |> system.Materializer
    
let flow : Flow<int, int, NotUsed> = 
    Flow.id 
    |> Flow.map (function
        | 6 | 7 | 8 -> failwithf "It's 6 and we are failing"
        | x -> x) 
    
let restartFlow =
    RestartFlow.WithBackoff(
        (fun _ -> flow), TimeSpan.FromSeconds 1., TimeSpan.FromSeconds 5., 0.2)
    
async {
    do! [1..10]
        |> Source.ofList
        |> Source.via restartFlow
        |> Source.runWith mat (Sink.forEach (printfn "%d"))
    
    do! system.Terminate() |> Async.AwaitTask
} 
|> Async.RunSynchronously
    
Task.WaitAll system.WhenTerminated
```
output
```
[DEBUG][23-Dec-17 19:29:13][Thread 0001][EventStream] StandardOutLogger started
[DEBUG][23-Dec-17 19:29:13][Thread 0001][EventStream(test)] Logger log1-DefaultLogger [DefaultLogger] started
[DEBUG][23-Dec-17 19:29:13][Thread 0001][EventStream(test)] StandardOutLogger being removed
[DEBUG][23-Dec-17 19:29:13][Thread 0001][EventStream(test)] Logger log1-DefaultLogger [DefaultLogger] started
[DEBUG][23-Dec-17 19:29:13][Thread 0001][EventStream(test)] StandardOutLogger being removed
[DEBUG][23-Dec-17 19:29:13][Thread 0001][EventStream(test)] Default Loggers started
1
2
3
4
5
[DEBUG][23-Dec-17 19:29:13][Thread 0008][Akka.Streams.Dsl.RestartWithBackoffFlow`3+Logic[System.Int32,System.Int32,Akka.NotUsed]] Graph in finished

[DEBUG][23-Dec-17 19:29:13][Thread 0008][Akka.Streams.Dsl.RestartWithBackoffFlow`3+Logic[System.Int32,System.Int32,Akka.NotUsed]] Restarting graph
in 00:00:01.0379531
[DEBUG][23-Dec-17 19:29:14][Thread 0003][Akka.Streams.Dsl.RestartWithBackoffFlow`3+Logic[System.Int32,System.Int32,Akka.NotUsed]] Graph in finished

[DEBUG][23-Dec-17 19:29:14][Thread 0003][Akka.Streams.Dsl.RestartWithBackoffFlow`3+Logic[System.Int32,System.Int32,Akka.NotUsed]] Restarting graph
in 00:00:02.2848763
[DEBUG][23-Dec-17 19:29:17][Thread 0008][Akka.Streams.Dsl.RestartWithBackoffFlow`3+Logic[System.Int32,System.Int32,Akka.NotUsed]] Graph in finished

[DEBUG][23-Dec-17 19:29:17][Thread 0008][Akka.Streams.Dsl.RestartWithBackoffFlow`3+Logic[System.Int32,System.Int32,Akka.NotUsed]] Restarting graph
in 00:00:04.1598629
9
10
[DEBUG][23-Dec-17 19:29:21][Thread 0008][ActorSystem(test)] System shutdown initiated
[DEBUG][23-Dec-17 19:29:21][Thread 0006][EventStream] Shutting down: StandardOutLogger started
[DEBUG][23-Dec-17 19:29:21][Thread 0006][EventStream] All default loggers stopped
[DEBUG][23-Dec-17 19:29:21][Thread 0006][EventStream] Shutting down: StandardOutLogger started
```
Maybe it's not a `RestartFlow` responsibility to retry elements and there is a special combinator for it?

**Comment by marcpiechura** [comment] 2017-12-23 19:54
See http://getakka.net/articles/streams/error-handling.html .
There is no build in stage to retry the failing element since the next stage only sees the error but not which element caused it. The easiest way would be to use try catch.

**Comment by vasily-kirichenko** [comment] 2017-12-23 20:00
I found this in Akka https://github.com/akka/akka-stream-contrib/blob/master/contrib/src/main/scala/akka/stream/contrib/Retry.scala

Looks like what I want exactly. I'm trying to port it, but I'm not sure I'll success.

**Comment by vasily-kirichenko** [comment] 2017-12-23 20:46
Could anybody help with porting https://github.com/akka/akka-stream-contrib/blob/master/contrib/src/main/scala/akka/stream/contrib/Retry.scala? I tried and found that I don't understand what the Scala code does at all :(

**Comment by vasily-kirichenko** [comment] 2017-12-25 17:24
@marcpiechura This is what I've ended up with:
```fsharp
open Akka
open System.Threading
open Akka.Actor
open Akka.Configuration
open Akka.Dispatch.SysMsg
open Akka.Event
open Akka.Routing
open Akka.Streams
open Akka.Streams.Dsl
open Akka.Streams.Supervision
open Akkling
open Akkling.Streams
open Akkling.Streams.Operators
open System
open System.Net
open System.Threading.Tasks
open FSharp.Control.WebExtensions

module Graph =
    let mapMaterializedValue fn (graph: #IRunnableGraph<_>) =
        graph.MapMaterializedValue(Func<_,_> fn)

module Flow =
  open Akka.Streams.Stage

  type Logic<'i, 's, 'o, 'e>
    (
        shape: Shape, 
        in1: Inlet<'i * 's>, 
        out1: Outlet<Result<'o, 'e>>, 
        in2: Inlet<Result<'o, 'e> * 's>, 
        out2: Outlet<'i * 's>,
        retryWith
    ) 
    as self =
    inherit GraphStageLogic(shape)
    
    let mutable elementInCycle = false
    let mutable pending: (Result<'o, 'e> * 's) option = None
          
    do self.SetHandler(in1, 
        { new InHandler() with
            override __.OnPush() =
              let is' = self.Grab'(in1)
              if not (self.HasBeenPulled' in2) then self.Pull'(in2)
              self.Push'(out2, is')
              elementInCycle <- true
              
            override __.OnUpstreamFinish() =
              if not elementInCycle then
                self.CompleteStage() })
                
       self.SetHandler(out1, 
         { new OutHandler() with
             override __.OnPull() =
               if self.IsAvailable'(out2) then self.Pull'(in1)
               else self.Pull'(in2) })
  
       self.SetHandler(in2, 
         { new InHandler() with
             override __.OnPush() =
               elementInCycle <- false
               match self.Grab'(in2) with
               | ((Ok _) as success, _) -> self.PushAndCompleteIfLast(success)
               | ((Error _) as failure, s) -> 
                    match retryWith s with 
                    | None -> self.PushAndCompleteIfLast(failure)
                    | Some is ->
                        self.Pull'(in2)
                        if self.IsAvailable'(out2) then
                            self.Push'(out2, is)
                            elementInCycle <- true
                        else 
                            pending <- Some is })
  
       self.SetHandler(out2, 
         { new OutHandler() with 
             override __.OnPull() =
               if self.IsAvailable'(out1) && not elementInCycle then
                 match pending with
                 | Some p ->
                     self.Push'(out2, p)
                     pending <- None
                     elementInCycle <- true
                 | None ->
                     if not (self.HasBeenPulled'(in1)) then
                         self.Pull'(in1) 
                         
             override __.OnDownstreamFinish() = () })
      
    member private this.Grab' (i: Inlet) = this.Grab i
    member private this.HasBeenPulled' (i: Inlet) = this.HasBeenPulled i
    member private this.Push'(o: Outlet, y) = this.Push(o, y)
    member private this.Pull' (x: Inlet) = this.Pull x
    member private this.IsAvailable' (o: Outlet) = this.IsAvailable o
    member private this.IsAvailable' (i: Inlet) = this.IsAvailable i
          
    member private this.PushAndCompleteIfLast(elem: Result<'o, 'e>) =
      this.Push(out1, elem)
      if this.IsClosed in1 then
        this.CompleteStage()
        

  type RetryCoordinator<'i, 's, 'o, 'e>(retryWith: 's -> (Result<'o, 'e> * 's) option) =
    inherit GraphStage<BidiShape<'i * 's, Result<'o, 'e>, Result<'o, 'e> * 's, 'i * 's>>()
        
    let in1 = Inlet<'i * 's>("Retry.ext.in")
    let out1 = Outlet<Result<'o, 'e>>("Retry.ext.out")
    let in2 = Inlet<Result<'o, 'e> * 's>("Retry.int.in")
    let out2 = Outlet<'i * 's>("Retry.int.out")
    
    override __.Shape = BidiShape(in1, out1, in2, out2)
    
    override this.CreateLogic(_: Attributes) = Logic(this.Shape, in1, out1, in2, out2, retryWith) :> _
    
  let retry<'i, 'o, 's, 'e, 'm> 
        (retryWith: 's -> (Result<'o, 'e> * 's) option) 
        (flow: IGraph<FlowShape<'i * 's, Result<'o, 'e> * 's>, 'm>) 
        : IGraph<FlowShape<'i * 's, Result<'o, 'e>>, 'm> =
    
    flow |> Graph.create1 (fun b origFlow ->
      let retry = b.Add(RetryCoordinator<'i, 's, 'o, 'e>(retryWith))
      b.From(retry.Outlet2).Via(origFlow).To(retry.Inlet2) |> ignore
      FlowShape(retry.Inlet1, retry.Outlet1)
    )
    
type Attempt = int

[<EntryPoint>]
let main _ = 
    let config = 
        ConfigurationFactory.ParseString """
akka {
  actor { 
    serializers {
      wire = "Akka.Serialization.HyperionSerializer, Akka.Serialization.Hyperion"
    }
    serialization-bindings {
      "System.Object" = wire
    }
    debug {  
      receive = off
      autoreceive = off
      lifecycle = off
      event-stream = off
      unhandled = on
    }
  }
  stdout-loglevel = DEBUG
  loglevel = DEBUG
}"""
    let system = ActorSystem.Create("test", config)
    let mat = 
        ActorMaterializerSettings
            .Create(system)
            .WithSupervisionStrategy(Deciders.RestartingDecider)
        |> system.Materializer
        
    let flow : Flow<int * Attempt, Result<int, string> * Attempt, NotUsed> = 
        Flow.id 
        |> Flow.map (fun (x, attempt) ->
            match x with
            | 6 | 7 | 8 -> Result.Error (sprintf "It's %d and we are failing" x), attempt + 1 
            | x -> Result.Ok x, attempt + 1)
        
    let retryFlow s =
        s
        |> Source.map (fun x -> x, 0)
        |> Source.via(
             flow
             |> Flow.retry (fun s ->
                  if s < 3 then 
                     Some (Result.Error (sprintf "attempt %d failed" s), s + 1)
                  else 
                     None)
           )
        
    async {
        do! [1..10]
            |> Source.ofList
            |> retryFlow
            |> Source.runWith mat (Sink.forEach (printfn "%A"))
        
        do! system.Terminate() |> Async.AwaitTask
    } 
    |> Async.RunSynchronously
        
    Task.WaitAll system.WhenTerminated
    0
```
Unfortunately, it crashes at runtime with:
```
[ERROR][24-Dec-17 14:08:53][Thread 0008][[akka://test/user/StreamSupervisor-0/Flow-0-0-unknown-operation#1613757097]] Error in stage [Program+Flow+RetryCoordinator`4[System.Int32,System.Int32,System.Int32,System.String]
]: Unable to cast object of type 'System.Tuple`2[System.Int32,System.Int32]' to type 'System.Tuple`2[Microsoft.FSharp.Core.FSharpResult`2[System.Int32,System.String],System.Int32]'.
Cause: System.InvalidCastException: Unable to cast object of type 'System.Tuple`2[System.Int32,System.Int32]' to type 'System.Tuple`2[Microsoft.FSharp.Core.FSharpResult`2[System.Int32,System.String],System.Int32]'.
   at Akka.Streams.Stage.GraphStageLogic.Grab[T](Inlet inlet)
   at Program.Flow.Logic`4.Grab'(Inlet i) in E:\github\AkklingStreamsTest\AkklingStreamsTest1\Program.fs:line 91
   at Program.Flow.-ctor@42.OnPush() in E:\github\AkklingStreamsTest\AkklingStreamsTest1\Program.fs:line 44
   at Akka.Streams.Implementation.Fusing.GraphInterpreter.Execute(Int32 eventLimit)
```
I'm very surprised that the code is successfully compiled, but type mismatch exception is thrown :(

**Comment by marcpiechura** [comment] 2017-12-26 20:08
@vasily-kirichenko  Don't have a solution since my F# skills are still a bit limited but I think the problem is that you're using the "untyped" overload of `Grab` , we have two, one which takes an `Intlet` and one which takes an `Inlet<T>` . 
[See](https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.Streams/Stage/GraphStage.cs#L1047)

If I'm using the "typed" one like this
`member private this.Grab'<'t> (i: Inlet<'t>) = this.Grab<'t> i`
I'm getting a few compiler errors 
![image](https://user-images.githubusercontent.com/6583600/34363770-5423f7b0-ea7f-11e7-83d9-1c1d15f7c496.png)
which looks kind of what the exceptions says. 

Also the inferred method definition indicates that the return type of your `Grap'` method is always `Result<..>`,  which can't be correct since inlet1 has `<'i * ' s>` as type parameter.

![image](https://user-images.githubusercontent.com/6583600/34363920-cca05df4-ea80-11e7-9d86-e30c1898352e.png)

Hope that helps, if not let me know, I can try to port the scala version to C# and see what I get.

**Comment by vasily-kirichenko** [comment] 2017-12-26 20:38
I tried to make some and all `Inlet`/`Outlet` generic and it resulted with errors I've never seen before :(

![image](https://user-images.githubusercontent.com/873919/34364325-bca736ce-ea95-11e7-8084-ddc3fe3d3b7f.png)

Anyway, I think it would be great to have this flow as a part of Akka.NET and implemented in C#. So, please, port it if you find some time. Thanks!

**Comment by marcpiechura** [comment] 2017-12-29 22:26
@vasily-kirichenko  I've ported the retry stage, see my PR https://github.com/AkkaNetContrib/Alpakka/pull/19 , would you be able to continue from here on, i.e. adding the remaining specs + docs ? 

Some more notes regarding this issue.
During the port I've got the same exception and it turned out that these two calls to `PushAndCompleteIfLast` are wrong too

```fsharp
               match self.Grab'(in2) with
               | ((Ok _) as success, _) -> self.PushAndCompleteIfLast(success)
               | ((Error _) as failure, s) -> 
                    match retryWith s with 
                    | None -> self.PushAndCompleteIfLast(failure)
```
, not the `Result` needs to be pushed but instead the complete tuple like this

```fsharp
               match self.Grab'(in2) with
               | ((Ok _) , _) as success -> self.PushAndCompleteIfLast(success)
               | ((Error _) , s) as failure-> 
                    match retryWith s with 
                    | None -> self.PushAndCompleteIfLast(failure)
```

The problem is that the `Push` method also takes an `Outlet` instead of an `Outlet<T>`, so you can easily do something like this.
```csharp
var outlet = new Outlet<int>("someOutlet");
Push(outlet, "hello world");
``` 

I can't remember why we haven't restricted it to `Outlet<T>` so I'll raise an issue for further investigation.

**Comment by marcpiechura** [comment] 2018-01-16 09:25
Both PR‘s are merged, so I’ll close this one.

**Closed by marcpiechura** 2018-01-16 09:25 UTC

**Comment by vasily-kirichenko** [comment] 2018-01-16 09:59
@marcpiechura thank you :)
