### ISSUE TITLE
MNTR Cross-Platform spec failure

### ISSUE THREAD

**Issue by heynickc** [akkadotnet/akka.net#2942] opened 2017-08-08 19:21 UTC
Spec being run on #2939 using the multi platform flag designed to allow us to test wire-format compatibility between .NET Core and .NET 4.5:

Command: 
```
dotnet "~\akka.net\src\core\Akka.MultiNodeTestRunner\bin\Release\netcoreapp1.1\Akka.MultiNodeTestRunner.dll" "~\akka.net\src\core\Akka.Remote.Tests.MultiNode\bin\Release\netcoreapp1.1\Akka.Remote.Tests.MultiNode.dll" "-Dmultinode.enable-filesink=on" "-Dmultinode.output-directory="~\akka.net\TestResults\multinode"" "-Dmultinode.platform=multi" "-Dmultinode.spec=Akka.Remote.Tests.MultiNode.RemoteDeliverySpec"`
```
This filters the MNTR runner to run only `Akka.Remote.Tests.MultiNode.RemoteDeliverySpec`

The multi-platform spec alternates between versions of NodeTestRunner.  Odd NODEs will be .NET Core NodeTestRunner processes and even NODES will be .NET 4.5 NodeTestRunner processes.

This spec fails on NODE1, being a .NET Core NodeTestRunner:

```
fo visit: http://getakka.net/docs/Serialization#how-to-setup-hyperion-as-default-serializer ). If you want to suppress this message set HOCON `akka.suppress-json-serializer-warning` config flag to on.
[INFO][8/8/2017 7:13:52 PM][Thread 0005][akka://TestRunnerLogging/deadLetters] Message Bound from akka://TestRunnerLogging/system/IO-TCP/$a to akka://TestRunnerLogging/deadLetters was not delivered. 1 dead letters encountered.
Starting test Remoting_with_TCP_must_not_drop_messages_under_normal_circumstances
[RUNNER][8/8/2017 7:13:52 PM][INFO][Akka.MultiNodeTestRunner]: Skipping [RemoteScatterGatherSpecs] (Filtering)
[RUNNER][8/8/2017 7:13:52 PM][INFO][Akka.MultiNodeTestRunner]: Skipping [RemoteRoundRobinSpecs] (Filtering)
[RUNNER][8/8/2017 7:13:52 PM][INFO][Akka.MultiNodeTestRunner]: Skipping [RemoteRandomSpecs] (Filtering)
[RUNNER][8/8/2017 7:13:52 PM][INFO][Akka.MultiNodeTestRunner]: Skipping [ATestConductorMust] (Filtering)
[RUNNER][8/8/2017 7:13:52 PM][INFO][Akka.MultiNodeTestRunner]: Skipping [A_restarted_quarantined_system_should_not_crash_the_other_system] (Filtering)
[RUNNER][8/8/2017 7:13:52 PM][INFO][Akka.MultiNodeTestRunner]: Skipping [RemoteReDeployment_must_terminate_the_child_when_its_parent_system_is_replaced_by_a_new_one] (Filtering)
[RUNNER][8/8/2017 7:13:52 PM][INFO][Akka.MultiNodeTestRunner]: Skipping [RemoteReDeployment_must_terminate_the_child_when_its_parent_system_is_replaced_by_a_new_one] (Filtering)
[RUNNER][8/8/2017 7:13:52 PM][INFO][Akka.MultiNodeTestRunner]: Skipping [RemoteReDeployment_must_terminate_the_child_when_its_parent_system_is_replaced_by_a_new_one] (Filtering)
[RUNNER][8/8/2017 7:13:52 PM][INFO][Akka.MultiNodeTestRunner]: Skipping [RemoteQuarantinePiercingSpecs] (Filtering)
[RUNNER][8/8/2017 7:13:52 PM][INFO][Akka.MultiNodeTestRunner]: Skipping [RemoteNodeShutdownAndComesBack_must_properly_reset_system_message_buffer_state_when_new_system_with_same_Address_comes_up] (Filtering)
[RUNNER][8/8/2017 7:13:52 PM][INFO][Akka.MultiNodeTestRunner]: Skipping [RemoteNodeRestart_must_allow_restarted_node_to_pass_through_gate] (Filtering)
[RUNNER][8/8/2017 7:13:52 PM][INFO][Akka.MultiNodeTestRunner]: Skipping [Must_receive_terminated_when_remote_actor_system_is_restarted] (Filtering)
[RUNNER][8/8/2017 7:13:52 PM][INFO][Akka.MultiNodeTestRunner]: Skipping [RemoteNodeDeathWatchSpecs] (Filtering)
[RUNNER][8/8/2017 7:13:52 PM][INFO][Akka.MultiNodeTestRunner]: Skipping [RemoteNodeDeathWatchSpecs] (Filtering)
[RUNNER][8/8/2017 7:13:52 PM][INFO][Akka.MultiNodeTestRunner]: Skipping [RemoteGatePiercing_must_allow_restarted_node_to_pass_through_gate] (Filtering)
[RUNNER][8/8/2017 7:13:52 PM][INFO][Akka.MultiNodeTestRunner]: Skipping [An_actor_system_that_deploys_actors_on_another_node_must_be_able_to_shutdown_when_remote_node_crash] (Filtering)
[RUNNER][8/8/2017 7:13:52 PM][INFO][Akka.MultiNodeTestRunner]: Skipping [An_actor_system_that_deploys_actors_on_another_node_must_be_able_to_shutdown_when_remote_node_crash] (Filtering)
[RUNNER][8/8/2017 7:13:52 PM][INFO][Akka.MultiNodeTestRunner]: Starting test Remoting_with_TCP_must_not_drop_messages_under_normal_circumstances
[RUNNER][8/8/2017]: Beginning spec Akka.Remote.Tests.MultiNode.RemoteDeliverySpec.Remoting_with_TCP_must_not_drop_messages_under_normal_circumstances on 3 nodes
[RUNNER][8/8/2017 7:13:52 PM][INFO][Akka.MultiNodeTestRunner]: Started node 1 : first on pid 50152
[RUNNER][8/8/2017 7:13:52 PM][INFO][Akka.MultiNodeTestRunner]: Started node 2 : second on pid 5516
[RUNNER][8/8/2017 7:13:52 PM][INFO][Akka.MultiNodeTestRunner]: Started node 3 : third on pid 33024
[INFO][8/8/2017 7:13:52 PM][Thread 0008][[akka://TestRunnerLogging/user/TcpLogger#1530360639]] Node connected on [akka://TestRunnerLogging/system/IO-TCP/$a/$b#1612521559]
[INFO][8/8/2017 7:13:52 PM][Thread 0008][[akka://TestRunnerLogging/user/TcpLogger#1530360639]] Node connected on [akka://TestRunnerLogging/system/IO-TCP/$a/$a#2018877047]
[INFO][8/8/2017 7:13:53 PM][Thread 0004][[akka://TestRunnerLogging/user/TcpLogger#1530360639]] Node connected on [akka://TestRunnerLogging/system/IO-TCP/$a/$c#1254125870]
[NODE2:second][8/8/2017]: SPEC PASSED: Akka.Remote.Tests.MultiNode.RemoteDeliverySpec.Remoting_with_TCP_must_not_drop_messages_under_normal_circumstances PASS
[INFO][8/8/2017 7:14:11 PM][Thread 0004][[akka://TestRunnerLogging/user/TcpLogger#1530360639]] Node disconnected on [akka://TestRunnerLogging/system/IO-TCP/$a/$c#1254125870]

[NODE3:third][8/8/2017]: SPEC PASSED: Akka.Remote.Tests.MultiNode.RemoteDeliverySpec.Remoting_with_TCP_must_not_drop_messages_under_normal_circumstances PASS
[INFO][8/8/2017 7:14:11 PM][Thread 0004][[akka://TestRunnerLogging/user/TcpLogger#1530360639]] Node disconnected on [akka://TestRunnerLogging/system/IO-TCP/$a/$b#1612521559]

 FAIL1:first][8/8/2017]: SPEC FAILED: Akka.Remote.Tests.MultiNode.RemoteDeliverySpec.Remoting_with_TCP_must_not_drop_messages_under_normal_circumstances
Unknown message:   at Akka.TestKit.Xunit2.XunitAssertions.Fail(String format, Object[] args) in C:\Users\nickc\Documents\Projects\akka.net\src\contrib\testkits\Akka.TestKit.Xunit2\XunitAssertions.cs:line 27
   at Akka.TestKit.TestKitBase.InternalExpectMsgEnvelope[T](Nulla
[NODE1:first][8/8/2017]: SPEC FAILED: StackTrace:    at Xunit.Assert.True(Nullable`1 condition, String userMessage)
Unknown message: ble`1 timeout, Action`2 assert, String hint, Boolean shouldLog)
   at Akka.TestKit.TestKitBase.InternalExpectMsg[T](Nullable`1 timeout, Action`2 assert, String hint)
   at Akka.TestKit.TestKitBase.ExpectMsg[T](Predicate`1 isMessage, Nullable`1 timeout, S
Unknown message: tring hint)
   at Akka.Remote.Tests.MultiNode.RemoteDeliverySpec.<Remoting_with_TCP_must_not_drop_messages_under_normal_circumstances>b__6_0() in C:\Users\nickc\Documents\Projects\akka.net\src\core\Akka.Remote.Tests.MultiNode\RemoteDeliverySpec.cs:line
 11
Unknown message: 5
   at Akka.Remote.TestKit.MultiNodeSpec.RunOn(Action thunk, RoleName[] nodes)
   at Akka.Remote.Tests.MultiNode.RemoteDeliverySpec.Remoting_with_TCP_must_not_drop_messages_under_normal_circumstances() in C:\Users\nickc\Documents\Projects\akka.net\src\c
Unknown message: ore\Akka.Remote.Tests.MultiNode\RemoteDeliverySpec.cs:line 123

[INFO][8/8/2017 7:14:19 PM][Thread 0015][[akka://TestRunnerLogging/user/TcpLogger#1530360639]] Node disconnected on [akka://TestRunnerLogging/system/IO-TCP/$a/$a#2018877047]

[NODE2:second][8/8/2017]: SPEC PASSED: Akka.Remote.Tests.MultiNode.RemoteDeliverySpec passed.
[NODE3:third][8/8/2017]: SPEC PASSED: Akka.Remote.Tests.MultiNode.RemoteDeliverySpec passed.
[RUNNER][8/8/2017 7:14:19 PM][INFO][Akka.MultiNodeTestRunner]: Waiting 3 seconds for all messages from all processes to be collected.
Complete
[RUNNER][8/8/2017]: Spec completed.
[RUNNER][8/8/2017 7:14:22 PM][INFO][Akka.MultiNodeTestRunner]: Skipping [PiercingShouldKeepQuarantineSpecs] (Filtering)
[RUNNER][8/8/2017 7:14:22 PM][INFO][Akka.MultiNodeTestRunner]: Skipping [NewRemoteActorSpecs] (Filtering)
[RUNNER][8/8/2017 7:14:22 PM][INFO][Akka.MultiNodeTestRunner]: Skipping [LookupRemoteActorSpecs] (Filtering)
[RUNNER][8/8/2017 7:14:22 PM][INFO][Akka.MultiNodeTestRunner]: Skipping [AttemptSysMsgRedelivery] (Filtering)
[RUNNER][8/8/2017 7:14:22 PM][INFO][Akka.MultiNodeTestRunner]: Waiting 5 seconds for all messages from all processes to be collected.
[RUNNER][8/8/2017]: Results for Akka.Remote.Tests.MultiNode.RemoteDeliverySpec.Remoting_with_TCP_must_not_drop_messages_under_normal_circumstances
Writing test state to: C:\Users\nickc\Documents\Projects\akka.net\TestResults\multinode\Akka.Remote.Tests.MultiNode-636378164324640155-multi.json
[RUNNER][8/8/2017]: Start time: 8/8/2017 7:13:52 PM
Writing test state to: C:\Users\nickc\Documents\Projects\akka.net\TestResults\multinode\Akka.Remote.Tests.MultiNode-636378164324640155-multi.html
[RUNNER][8/8/2017]:  --> Node 1:first : FAIL [00:00:27.0139501 elapsed]
[RUNNER][8/8/2017]:  --> Node 2:second : PASS [00:00:19.0556705 elapsed]
[RUNNER][8/8/2017]:  --> Node 3:third : PASS [00:00:19.0566763 elapsed]
[RUNNER][8/8/2017]: End time: 8/8/2017 7:14:22 PM
[RUNNER][8/8/2017]: FINAL RESULT: FAIL after 00:00:30.1985565.
[RUNNER][8/8/2017]: Failure messages by Node
[RUNNER][8/8/2017]: <----------- BEGIN NODE 1:first ----------->
 FAILER][8/8/2017]:  --> Akka.Remote.Tests.MultiNode.RemoteDeliverySpec.Remoting_with_TCP_must_not_drop_messages_under_normal_circumstances
[RUNNER][8/8/2017]:  --> StackTrace:    at Xunit.Assert.True(Nullable`1 condition, String userMessage)
[RUNNER][8/8/2017]: <----------- END NODE 1:first ----------->
Finished.
```
I'll be adding more info to this issue as I gather it.

**Comment by Arkatufus** [comment] 2017-08-09 06:04
Dissecting this further, this is the log from the third node:
<pre>
[WARNING][8/8/2017 9:11:18 PM][Thread 0001][ActorSystem(NoteTestRunner-2)] NewtonSoftJsonSerializer has been detected as a default serializer. It will be obsoleted in Akka.NET starting from version 1.5 in the favor of Hyperion (for more info visit: http://getakka.net/docs/Serialization#how-to-setup-hyperion-as-default-serializer ). If you want to suppress this message set HOCON `akka.suppress-json-serializer-warning` config flag to on.
Running specs for akka.remote.tests.multinode.dll [e:\git\akka.net\src\core\akka.remote.tests.multinode\bin\release\net452\akka.remote.tests.multinode.dll]
[Akka.Remote.TestKit][Debug][8/8/2017 9:11:32 PM]Using StandardOut as the default logging system.
[Akka.Remote.TestKit.MsgEncoder][Debug][8/8/2017 9:11:32 PM]Encoding Akka.Remote.TestKit.Hello
[Akka.Remote.TestKit.Proto.ProtobufEncoder][Debug][8/8/2017 9:11:32 PM][[::1]:50175 --> [::1]:4711] Encoding { "hello": { "name": "third", "address": { "system": "RemoteDeliverySpec", "hostname": "localhost", "port": 50174, "protocol": "akka.tcp" } } } into Protobuf
[Akka.Remote.TestKit.Proto.ProtobufDecoder][Debug][8/8/2017 9:11:32 PM]Decoding SlicedByteBuffer(ridx: 0, widx: 3, cap: 3/3, unwrapped: PooledHeapByteBuffer(ridx: 7, widx: 7, cap: 1024)) into Protobuf
[Akka.Remote.TestKit.MsgDecoder][Debug][8/8/2017 9:11:32 PM]Decoding { "done": " " }
[Akka.Remote.TestKit.MsgDecoder][Debug][8/8/2017 9:11:32 PM]Decoded Akka.Remote.TestKit.Done
[WARNING][8/8/2017 9:11:32 PM][Thread 0025][[akka://RemoteDeliverySpec/user/TestConductorClient#1567378390]] unhandled event <Terminated>: [akka://RemoteDeliverySpec/user/$a#1510828869] - ExistenceConfirmed=True in state Connected
[Akka.Remote.TestKit.MsgEncoder][Debug][8/8/2017 9:11:32 PM]Encoding Akka.Remote.TestKit.EnterBarrier
[Akka.Remote.TestKit.Proto.ProtobufEncoder][Debug][8/8/2017 9:11:32 PM][[::1]:50175 --> [::1]:4711] Encoding { "barrier": { "name": "actors-started", "timeout": "300000000" } } into Protobuf
[Akka.Remote.TestKit.Proto.ProtobufDecoder][Debug][8/8/2017 9:11:33 PM]Decoding SlicedByteBuffer(ridx: 0, widx: 20, cap: 20/20, unwrapped: PooledHeapByteBuffer(ridx: 24, widx: 24, cap: 1024)) into Protobuf
[Akka.Remote.TestKit.MsgDecoder][Debug][8/8/2017 9:11:33 PM]Decoding { "barrier": { "name": "actors-started", "op": "Succeeded" } }
[Akka.Remote.TestKit.MsgDecoder][Debug][8/8/2017 9:11:33 PM]Decoded Akka.Remote.TestKit.BarrierResult
[Akka.Remote.TestKit.MsgEncoder][Debug][8/8/2017 9:11:33 PM]Encoding Akka.Remote.TestKit.EnterBarrier
[Akka.Remote.TestKit.Proto.ProtobufEncoder][Debug][8/8/2017 9:11:33 PM][[::1]:50175 --> [::1]:4711] Encoding { "barrier": { "name": "after-1", "timeout": "300000000" } } into Protobuf
>>>>>>>>>>>> NET FAILED <<<<<<<<<<<<
<b>{
	"$id": "1",
	"$type": "Akka.Remote.Tests.MultiNode.RemoteDeliveryMultiNetSpec+Letter, Akka.Remote.Tests.MultiNode",
	"N": { "$": "I1" },
	"Route": {
		"$type": "System.Collections.Generic.List`1[[Akka.Actor.IActorRef, Akka]], System.Private.CoreLib",
		"$values": [{
				"$id": "2", "$type": "Akka.Actor.ActorRefBase+Surrogate, Akka", "Path": "akka.tcp://RemoteDeliverySpec@localhost:50167/user/postman-second#1298057640"
			}, {
				"$id": "3", "$type": "Akka.Actor.ActorRefBase+Surrogate, Akka", "Path": "akka.tcp://RemoteDeliverySpec@localhost:50174/user/postman-third#469643634"
			}, {
				"$id": "4", "$type": "Akka.Actor.ActorRefBase+Surrogate, Akka", "Path": "akka.tcp://RemoteDeliverySpec@localhost:50173/system/testActor1#2132844457"
			}
		]
	}
}</b>
>>>>>>>>>>>> ====== <<<<<<<<<<<<
Newtonsoft.Json.JsonSerializationException: Error resolving type specified in JSON 'System.Collections.Generic.List`1[[Akka.Actor.IActorRef, Akka]], System.Private.CoreLib'. Path 'Route.$type', line 1, position 233. ---> Newtonsoft.Json.JsonSerializationException: Could not load assembly 'System.Private.CoreLib'.
   at Newtonsoft.Json.Serialization.DefaultSerializationBinder.GetTypeFromTypeNameKey(TypeNameKey typeNameKey)
   at Newtonsoft.Json.Utilities.ThreadSafeStore`2.AddValue(TKey key)
   at Newtonsoft.Json.Utilities.ThreadSafeStore`2.Get(TKey key)
   at Newtonsoft.Json.Serialization.DefaultSerializationBinder.BindToType(String assemblyName, String typeName)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolveTypeName(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, String qualifiedTypeName)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolveTypeName(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, String qualifiedTypeName)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataProperties(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue, Object& newValue, String& id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Akka.Serialization.NewtonSoftJsonSerializer.FromBinary(Byte[] bytes, Type type)
</pre>
The failure happened when net452 binary tried to deserialize a json message from a netcore binary.
The root cause was incompatible dll library packaging of certain built in classes in .net, in this case it is the `System.Collection.Generic.List` where it is packed inside `System.Private.CoreLib.dll` in net core and packed in `System.dll` in net framework, causing deserialization to fail.

**Closed** 2017-08-10 22:52 UTC
