### ISSUE TITLE
Exception creating actor implementing IWithUnboundedStash

### ISSUE THREAD

**Issue by sadprofessor** [akkadotnet/akka.net#941] opened 2015-05-02 22:58 UTC
When an actor that implements IWithUnboundedStash that was resolved from DIExt (autofac in this case, although I doubt that matters) calls it's first Become, this exception is thrown:
```
[ERROR][02/05/2015 23:54:32][Thread 0012][ActorSystem(System)] An exception occurred while trying to apply plugin of type Akka.Actor.ActorStashPlugin to the newly created actor (Type = Machina.
MessagePipeline.MessageBufferingActor, Path = akka://System/user/$b/$b)
Cause: System.NotSupportedException: DequeBasedMailbox required, got: UnboundedMailbox
An (unbounded) deque-based mailbox can be configured as follows:
    my-custom-mailbox {
        mailbox-type = "Akka.Dispatch.UnboundedDequeBasedMailbox"
    }
   at Akka.Actor.Internal.AbstractStash..ctor(IActorContext context, Int32 capacity)
   at Akka.Actor.Internal.UnboundedStashImpl..ctor(IActorContext context)
   at Akka.Actor.StashFactory.CreateStash(IActorContext context, Type actorType)
   at Akka.Actor.ActorStashPlugin.AfterIncarnated(ActorBase actor, IActorContext context)
   at Akka.Actor.ActorProducerPipeline.AfterActorIncarnated(ActorBase actor, IActorContext context)
```

**Comment by rogeralsing** [comment] 2015-05-03 05:58
As the exception complains about the mailbox type, have you configured the actor to use some custom mailbox type?

Not all mailboxes support stashing, as the mailbox has to be able to prepend messages at the front when using stashing.

**Comment by sadprofessor** [comment] 2015-05-03 09:13
I haven't changed the configuration of the mailbox type. It's just a vanilla ReceiveActor with no custom configuration.

This sample actor has the same issue with resolving through DI

```
   class TestActor : ReceiveActor, IWithUnboundedStash
    {
        public IStash Stash { get; set; }

        protected override void PreStart()
        {
            base.PreStart();
            Become(FirstState);
        }

        private void FirstState()
        {
            
        }
    }
```

When resolving it through 
```
Context.ActorOf(Context.System.GetExtension<DIExt>().Props(typeof(TestActor)))
```

it errors, when creating it directly through
```
Context.ActorOf(Props.Create(() => new TestActor()));
```

it's fine

The registration in autofac is just:
```
builder.RegisterType<TestActor>().AsSelf();
```

Cheers

**Comment by Danthar** [comment] 2015-05-04 07:35
The problem is in the `Akka.DI.Core.DIActorProducer`.

```
 public Type ActorType
        {
            get { return this.dependencyResolver.GetType(); }
        }
```

It returns the type of the dependencyResolver instead of the ActorType. This causes the rest of the Actor Initialisation routine to fail to detect the IWithUnboundedStash and inject the wrong Mailbox type.

**Comment by jcwrequests** [comment] 2015-05-07 00:30
@Danthar Thanks for catching that one.

**Comment by DNosralla** [comment] 2015-05-07 03:59
Still can't use IWithUnboundedStash actor from DI Context.

Akka.Actor.Internal.AbstractStash is trying to get:
  var mailbox = actorCell.Mailbox as IDequeBasedMailbox

If actor is created from system directly, the actorCell.Mailbox is Akka.Dispatch.UnboundedDequeBasedMailbox, that is IDequeBasedMailbox.

If actor is created from DI (AutoFac), the actorCell.Mailbox is
Akka.Dispatch.UnboundedMailbox, wich does not resolve to IDequeBasedMailbox

Next it checks if the mailbox is not null, and throw the "DequeBasedMailbox required" exception.

**Comment by Danthar** [comment] 2015-05-07 06:32
A PR containing a fix got merged a short while ago. Have you tried it with a version including that fix? I believe nowadays we have nightlies on nuget  but I'm not sure @aaronontheweb (?)

-----Original Message-----

**Comment by DNosralla** [comment] 2015-05-07 15:05
Yes, running the dev branch, including fix from #950 
Just made a pull request with unit tests for it #955 

(I have no idea about the compliance of my pull request or its contents, just wanted to make it easy for you to catch the problem)

**Comment by Danthar** [comment] 2015-05-07 15:35
I found it. Its a stupid typo in my last PR. Ill fix that asap.

**Comment by Danthar** [comment] 2015-05-18 15:19
A fix for this issue has been merged several days ago. Ergo this can be closed.

**Comment by Horusiath** [comment] 2015-12-24 07:35
From @mithril52 , Akka version 1.0.5 and Ninject DI:

> If I try to create the actor like this:
`Context.ActorOf(Context.DI().Props(typeof(MdmSessionHandlerActor)), msg.DestinationAddress)'
It does work, and I get the stash properly. But if I try it via a bound interface like this:
'container.Bind&lt;IMdmSessionHandler&gt;().To&lt;MdmSessionHandlerActor&gt;();
It doesn't work
And I obviously need to figure out how to properly do markdown here...
After the above Bind call there should have been a line like this:
Context.ActorOf(Context.DI().Props(typeof(IMdmSessionHandler)), msg.DestinationAddress)

**Comment by rogeralsing** [comment] 2015-12-24 09:13
@Horusiath same error different DI package?

**Comment by Horusiath** [comment] 2015-12-24 09:33
Sorry, my bad. Using container directly to creat an actor will always fail. Closing this.

**Closed by Horusiath** 2015-12-24 09:33 UTC
Labels: confirmed bug

**Comment by bonza** [comment] 2017-02-17 09:52
Is it the same issue or I just doing something wrong?
http://stackoverflow.com/questions/42294663/how-to-add-stash-to-the-actor-in-akka-net-with-windsor-container
