### ISSUE TITLE
Router cannot be created from fallback configuration

### ISSUE THREAD

**Issue by eisendle** [akkadotnet/akka.net#2348] opened 2016-10-21 13:05 UTC
I have two HOCON configuration files A and B. B is configured as fallback of A. B contains the deployment definition for a router. However if I try to create the router with `Props.Empty.WithRouter(FromConfig.Instance)` I get a configuration error that the router configuration is missing. If I put the router definition in configuration file A, everything works like expected, the router is created without an error.

I already checked the code. Looks like Deployer.cs loads the section **akka.actor.deployment** in its constructor, which does not consider the fallback configuration.

**Comment by Danthar** [comment] 2016-11-01 11:14
Can you share how you created your config and passed it into your ActorSystem instance ?

**Comment by eisendle** [comment] 2016-11-01 12:20
Sure. I´ve created a gist which shows the issue [here](https://gist.github.com/eisendle/2f8f92e2f9bf734093782fda7a3aa51b). In the example creation of **workerB** fails with an ConfigurationException. However, **workerBConfig** contains the valid configuration for the router.

**Comment by kantora** [comment] 2016-11-22 11:23
There is an old bug. I have even provided test to reproduce it.
https://github.com/akkadotnet/akka.net/issues/1321

**Comment by kerch-ai** [comment] 2016-12-18 02:57
Trying to learn the inner workings of akka.net. Not 100%, but it looks like Deployer only looks at the root config. Should it also take into account the fallaback config? Will create pull request with my solution

**Comment by Danthar** [comment] 2017-01-21 14:39
Fixed via PR

**Closed by Danthar** 2017-01-21 14:39 UTC
Labels: confirmed bug, up for grabs
