### ISSUE TITLE
System.DllNotFoundException: Unable to load shared library 'lmdb' or one of its dependencies

### ISSUE THREAD

**Issue by fscavo** [akkadotnet/akka.net#5174] opened 2021-08-06 19:42 UTC
**Version Information**
Version of Akka.NET?
**1.14.22**
Which Akka.NET Modules?
**Akka.Cluster
Akka.Cluster.Sharding**

**Describe the bug**
The service used to work fine with the version 1.14.21. After having updated to 1.14.22 the service stopped working and kept throwing **System.DllNotFoundException** with the following details:
**_Unable to load shared library 'lmdb' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblmdb: cannot open shared object file: No such file or directory_**

**Comment by Aaronontheweb** [comment] 2021-08-06 19:57
We just received another bug report via our paid support channel about this issue. This appears to be a regression in our HOCON configuration that didn't get caught because we have the https://www.nuget.org/packages/Akka.DistributedData.LightningDB/ package installed in our test suites.

You can work around this issue, in the short run, by just installing that package.

However, we're working on an emergency patch to roll this back as it represents a breaking change. We're also going to add a regression test to block for this in the future.

**Comment by Aaronontheweb** [comment] 2021-08-06 20:13
Actually, it looks like we are referencing it: https://www.nuget.org/packages/Akka.Cluster.Sharding/1.4.22

**Comment by Aaronontheweb** [comment] 2021-08-06 20:14
@fscavo is this on Linux or Windows?

**Comment by fscavo** [comment] 2021-08-06 20:17
> @fscavo is this on Linux or Windows?

This is on Linux and the docker image is mcr.microsoft.com/dotnet/aspnet:5.0.7-focal

**Comment by Aaronontheweb** [comment] 2021-08-06 20:23
Could be related to https://github.com/CoreyKaylor/Lightning.NET/issues/141

**Comment by andyfurnival** [comment] 2021-08-06 20:25
I’ve always installed lmdb libraries via apt-get since I started using ddata. I always assumed that was a prerequisite

**Comment by Aaronontheweb** [comment] 2021-08-06 20:27
Looks like this was even previously reported and fixed https://github.com/CoreyKaylor/Lightning.NET/issues/133

Not sure why this is happening now with v1.4.22.

**Comment by Arkatufus** [comment] 2021-08-06 20:29
@fscavo For a workaround, if you're not using durable ddata, you can set `akka.cluster.sharding.distributed-data.durable.keys=[]` to  make sure that LightningDB isn't loaded

**Comment by Aaronontheweb** [comment] 2021-08-06 20:29
> We just received another bug report via our paid support channel about this issue. This appears to be a regression in our HOCON configuration that didn't get caught because we have the https://www.nuget.org/packages/Akka.DistributedData.LightningDB/ package installed in our test suites.
> 
> You can work around this issue, in the short run, by just installing that package.
> 
> However, we're working on an emergency patch to roll this back as it represents a breaking change. We're also going to add a regression test to block for this in the future.

Looks like none of this is the case. Just spot checked all of our HOCON configuration changes, library updates, and settings class changes. All of them appear to be ok - wouldn't have effected this in any meaningful way.

**Comment by Aaronontheweb** [comment] 2021-08-06 20:52
This should stop LMDB from loading automatically for users who don't want to use it intentionally https://github.com/akkadotnet/akka.net/pull/5175

**Comment by fscavo** [comment] 2021-08-06 20:56
> ## Workaround
> @fscavo For a workaround, if you're not using durable ddata, you can set `akka.cluster.sharding.distributed-data.durable.keys=[]` to make sure that LightningDB isn't loaded

@Arkatufus

**Comment by Aaronontheweb** [comment] 2021-08-06 21:19
@fscavo we'll publish a fix to resolve this issue for users upgrading, but I want to keep this issue open until https://github.com/CoreyKaylor/Lightning.NET/issues/141 is resolved as that will be a footgun for users in perpetuity until a new version is pushed.

**Comment by Aaronontheweb** [comment] 2021-08-06 21:20
I'm amazed you didn't have this issue on v1.4.21 though - the offending HOCON was added back then.

**Comment by fscavo** [comment] 2021-08-06 21:29
> I'm amazed you didn't have this issue on v1.4.21 though - the offending HOCON was added back then.

The previous version was running with this base image **mcr.microsoft.com/dotnet/aspnet:3.1-focal**. Could it be possible that **aspnet:3.1-focal** had **liblmdb-dev** installed by default?

**Comment by Aaronontheweb** [comment] 2021-08-06 21:43
@fscavo I was just able to reproduce your error using https://github.com/petabridge/akkadotnet-cluster-workshop, but I had to set `akka.cluster.sharding.remember-entities=on` and `akka.cluster.sharding.state-store-mode=ddata` to reproduce it with v1.4.22.

The issue _does not_ occur when `akka.cluster.sharding.remember-entities=off`, FYI.

I'm going to try with v1.4.21 and see if that comes up.

**Comment by Aaronontheweb** [comment] 2021-08-06 21:43
Version of the SDK we're using: https://github.com/petabridge/akkadotnet-cluster-workshop/blob/dev/src/Akka.CQRS.Pricing.Service/Dockerfile#L1

**Comment by Aaronontheweb** [comment] 2021-08-06 21:47
Yeah I'm definitely hitting this problem on v1.4.21 as well. It's possible that you're only hitting it now because of the underlying changes in the base image.

**Comment by Aaronontheweb** [comment] 2021-08-06 22:01
Decided on a different approach for fixing this issue and reverted our planned PR. Stay tuned.

**Comment by fscavo** [comment] 2021-08-06 22:09
> @fscavo I was just able to reproduce your error using https://github.com/petabridge/akkadotnet-cluster-workshop, but I had to set `akka.cluster.sharding.remember-entities=on` and `akka.cluster.sharding.state-store-mode=ddata` to reproduce it with v1.4.22.
> 
> The issue _does not_ occur when `akka.cluster.sharding.remember-entities=off`, FYI.
> 
> I'm going to try with v1.4.21 and see if that comes up.

I found out that the previous version of Akka was **1.14.19** and not 1.14.21. The other services run Akka 1.14.21 with no issue because they use StateStoreMode.Persistence. My bad :-(

**Comment by Aaronontheweb** [comment] 2021-08-06 22:42
No problem, this change was introduced in v1.4.21:

https://github.com/akkadotnet/akka.net/blob/7997b586ae6c546d157de101eb61394f62dedc14/src/contrib/cluster/Akka.Cluster.Sharding/reference.conf#L184-L195

This is what's causing the system to attempt to load LMDB

**Comment by Aaronontheweb** [comment] 2021-08-06 23:10
Have a solution pending here: https://github.com/akkadotnet/akka.net/pull/5180

We're going to put this up into a nightly package after it's merged. I just verified a few moments ago that this ran fine inside https://github.com/petabridge/akkadotnet-cluster-workshop without having to install any custom packages inside our `Dockerfile`s - all of the native DLLs are contained inside https://github.com/akkadotnet/Lightning.NET, which contains the most recent sources for https://github.com/CoreyKaylor/Lightning.NET that are not yet published on NuGet.

This is called a "vendored" package approach; it's fairly common in the JVM ecosystem; and it's, IMHO, a bit of a hack so I don't want this to be a "forever" thing. I've made our LightningDB.Vendored.Akka package hidden on NuGet because I'd rather have everyone in the ecosystem use the original, but I always don't want to leave our own users in the lurch while we wait for an official release. I will be very happy to drop our vendored version of the package and switch back to the original as soon as it's possible.

I'll post an update on this thread when there is a nightly available - please give that a try @fscavo and let us know if that runs in your environment. If it does, we'll push v1.4.23 on Monday.

**Closed** 2021-08-08 01:55 UTC
Labels: confirmed bug, critical, akka-cluster-sharding, akka-ddata, akka-ddata-durable

**Comment by Arkatufus** [comment] 2021-08-09 14:43
I ran `apt search liblmdb` on some of the dotnet docker containers and none of them have lmdb installed, but the WSL image for Windows 10 does, so this might cause a build that runs on local WSL linux to fail to run inside a docker container.

**Comment by Aaronontheweb** [comment] 2021-08-09 19:59
I've been able to validate in local Docker builds that #5180 resolved the issue, but in post-mortem analysis with @Arkatufus this morning we determined that this issue really slipped through our testing matrix because of https://github.com/akkadotnet/akka.net/issues/3573 and we will need to add MNTR support to Linux going forward to catch these types of issues. I've begun preliminary work on that here https://github.com/akkadotnet/akka.net/pull/5182 but it will probably take a while to get right.

**Comment by Aaronontheweb** [comment] 2021-08-10 02:12
Was able to validate that Windows still works with the latest nightlies here as well: https://github.com/Aaronontheweb/Akka.Cluster.Sharding.DDataDemo

Going to open a separate issue for this, but that code sample definitely exposed some bottlenecks with `ShardRegion` that need to be resolved

**Comment by Aaronontheweb** [comment] 2021-08-10 02:38
Ok, pushing Akka.NET v1.4.23 live with this fix included. Validated inside Docker, Ubuntu WSL, and Windows desktop.
