### ISSUE TITLE
Memory leak, event messages not disposing

### ISSUE THREAD

**Issue by schepersk** [akkadotnet/akka.net#2282] opened 2016-08-31 13:48 UTC
We have an issue because of non disposing event messages.
Our setup is a CQRS/ES architecture, powered by Cluster Sharding and SQL Server persistence.

For some obscure reason, there is this one event type that is not disposing. Instances have been persisted in the event journal and all read model projections have been executed (AR actor/shard entity publishes them on the Akka EventStream, projection actors subscribe to them).

Other event message types are not being held in memory!

Akka version 1.1.1, SQL Server persistence 1.1.1.5-beta, Cluster sharding 1.1.1.28-beta

Here is a screen shot of the memory dump being debugged in VS:
![image](https://cloud.githubusercontent.com/assets/18052450/18130994/78698eba-6f91-11e6-948c-eeadbe98a8ce.png)

**Comment by Aaronontheweb** [comment] 2016-09-01 17:51
@Horusiath hmmm... think it could be the `MessageExtractor` perhaps?

**Comment by Horusiath** [comment] 2016-09-01 18:15
`MessageExtractor` is pretty dumb - it's only resolving values from provided message fields. It doesn't block and doesn't stack anything. 

After some chat on gitter it looks like some problem with specific implementation - mainly publishing persisted events on the event bus. This hardly looked as an internal problem of Akka.NET - from the memory dump we can say that `LbvIngeschreven` is an custom persisted event and it's placed directly inside akka.net `Envelope`. This suggest problem in the user code - nowhere in akka internals persisted events are send directly between two actors, they are always wrapped with other internal message wrapper.

**Comment by Horusiath** [comment] 2016-09-04 07:09
Closing this one. The problem is not related to Akka.NET itself.

**Closed by Horusiath** 2016-09-04 07:09 UTC
Labels: akka-cluster-sharding, akka-persistence, potential bug
