### ISSUE TITLE
Our Tcp connections appear to be sharing their internal(to Akka) ByteBuffers

### ISSUE THREAD

**Issue by spankr** [akkadotnet/akka.net#3921] opened 2019-09-20 20:53 UTC
# Intro
We are using Akka.NET to manage short-lived communication from our array of IoT devices.
The connect, give us their status, we respond with "OK\r\n" and then close the connection.
We are running v1.3.12 on a .NET Core application within a Docker container. (so Linux platform).

Over the past year we've been seeing communication that looks like it is over-writing itself. This is a recent example: `OK\r\ntle 4.1 BufferGet Loaded\r\nd 2\r\n`

Valid communication examples:
* `OK\r\n`
* `Shuttle 4.1 BufferGet Loaded\r\n`
* `Buffer 4.1 ShuttleAlign Aligned 2\r\n`

For the past year, we've just chalked it up as a glitch in the few IoT devices we've had live and asked our IoT team to hunt it down and fix it.

About 3 months ago, we've been scaling the number of IoT devices and we've been seeing more of these messages(about 2-4 per day). Not only that but the messages seem to be amalgamations of communication from different devices. There is no way a single IoT device can construct/send some of these messages.

What appears to be happening is that on our side (the Akka system-side), the same memory is being shared for multiple TCP sockets.

The example I provided above, conveniently aligns to the valid examples (whitespace added to fill for non-printable characters):
```
OK\r\ntle 4.1 BufferGet Loaded\r\nd 2\r\n
OK\r\n
Shut  tle 4.1 BufferGet Loaded\r\n
Buff  er 4.1 ShuttleAlign Aligne  d 2\r\n
```

When researching this, we came across an interesting **_TODO_** in the **ReleaseSocketAsyncEventArgs()** of [Akka.IO.TcpConnection.cs](https://github.com/akkadotnet/akka.net/blob/a0c44f1ffff794139dcb65cba65c9e204ec7e9e8/src/core/Akka/IO/TcpConnection.cs):
```
        private void ReleaseSocketAsyncEventArgs()
        {
            if (ReceiveArgs != null)
            {
                var buffer = new ByteBuffer(ReceiveArgs.Buffer, ReceiveArgs.Offset, ReceiveArgs.Count);
                Tcp.SocketEventArgsPool.Release(ReceiveArgs);
                //TODO: there is potential risk, that socket was working while released. In that case releasing buffer may not be safe.
                Tcp.BufferPool.Release(buffer);
                ReceiveArgs = null;
            }

            if (SendArgs != null)
            {
                Tcp.SocketEventArgsPool.Release(SendArgs);
                SendArgs = null;
            }
        }
```

I don't know how valid that TODO is and my socket-fu is pretty weak. Would someone be able to take a deeper look at this to see if this could be the issue with our race condition?

Even if the BufferPool had more of a FIFO behavior so the ByteBuffers can "age" a little when they re-enter the pool, that would be nice.

**Comment by spankr** [comment] 2019-10-01 14:02
It's been a couple weeks of digging here so I thought I'd send an update on what we believe we are seeing. (We still don't know how to recreate the scenario on demand)

It appears that the `ByteBuffer` is most likely working properly. The data we are seeing is from previous, valid network communication history/use. It looks like the `ReceiveArgs` has `SocketError==Success` and `BytesTransferred` that are not in sync with the data in the buffer.

The working hypothesis that fits is that `ReceiveArgs` is also being reused but it retains the `SocketError` and `BytesTransferred` from the previous use, when the current read is performed.
(_Releasing back to the pool does not clear those properties and `BytesTransferred` has no setter._)

What I cannot find is how `InnerRead(...)` is called before the actual buffer is filled with data. **.NET Core** sets those two properties on a successful data read of the socket, after the ByteBuffer has been filled. So I can't see how it's possible.

If `ReceiveArgs` is valid, then that would have to mean that .NET Core didn't publish the socket data to the `ByteBuffer` (no actual writing occurred...or it was written to the wrong location).

**Comment by Aaronontheweb** [comment] 2019-10-01 14:12
Thanks for investigating this @spankr - looks to me like our implementation for reusing the `SocketAsyncEventArgs` might have been a little too clever by half.

For reproducing a bug like this, what's the scenario look like as a bulleted list of socket steps? If you could share that, I could probably write a way to simulate those failures at the network level.

**Comment by spankr** [comment] 2019-10-01 15:03
We're working on getting those steps ironed out.

**Comment by valdisz** [comment] 2019-10-22 10:13
@spankr do you have a sample code that demonstrates this issue? I want to fix this and any code that you haw will help me to fix it faster.

**Comment by spankr** [comment] 2019-10-22 15:11
Unfortunately, no. I pulled our tcp actors out into a standalone actor system, with the intent that I could provide it to you. 
The issue wouldn't recreate.

On an interesting side note, (we've been waiting until today to give the issue a chance to happen)...
Last Tuesday, we released a change that did just two things:
1. Akka 1.3.13 -> Akka 1.3.15
2. .NET Core 2.2 -> .NET Core 3.0

This issue hasn't happened since. The last time we've seen the issue was 30 minutes before our deployment, last Tuesday.

That's not to say that it's fixed....yay non-repeatable issue! But we were seeing 10-12 each day. We are now seeing zero.

**Comment by Aaronontheweb** [comment] 2019-10-22 15:23
@spankr it's possible that the issue was related to the underlying `System.IO` implementation itself - and that the .NET Core upgrade included a fix for it.

Naturally, it's a good practice for us to assume that the problem is our fault first and foremost, but if the issue doesn't come up again for let's say another 5 days or so, then let's mark this issue as closed with the solution being "upgrade to .NET Core 3.0" - does that seem reasonable?

**Comment by spankr** [comment] 2019-10-22 16:07
That is perfectly reasonable to me.

When I had researched this, I couldn't rule out `System.IO`. I put it at a "highly unlikely" probability.
Everything I reviewed in `Akka.IO` (after posting this issue), followed the current .NET patterns and looked pretty solid. Also "highly unlikely".

The only attack-vector I could think of was an early read of the buffer, using a stale `SocketAsyncEventArgs`.

But yes, **"upgrade to .NET Core 3.0"** is a reasonable solution.

**Comment by Aaronontheweb** [comment] 2020-01-14 21:57
Issue has been resolved via https://github.com/akkadotnet/akka.net/pull/4140

Will be part of v1.4.0 and possibly 1.3.18.

**Closed by Aaronontheweb** 2020-01-14 21:57 UTC
Labels: akka-io, confirmed bug
