### ISSUE TITLE
New incarnation of member won't join the cluster unless old incarnation is manually downed

### ISSUE THREAD

**Issue by nvivo** [akkadotnet/akka.net#3252] opened 2018-01-05 13:49 UTC
When a process is killed and restarted, I'm noticing that the old incarnation is not removed automatically sometimes. It seems to work once or twice after the leader is started, then suddenly stopped working.

I'm having messages like this for half an hour until I manually down the node through pbm:

```
New incarnation of existing member [UniqueAddress: (akka.tcp://SICluster@10.0.10.202:10052, 1933389984)] is trying to join. Existing will be removed from the cluster and then new member will be allowed to join.
```

This is Akka 1.3.2 on netcore 2.0 running on linux.

Could be related to #1458.

**Comment by Aaronontheweb** [comment] 2018-01-05 14:44
@nvivo hmmm.... wonder if there's an issue with Gossip pruning here

**Comment by nvivo** [comment] 2018-01-06 20:44
I've been doing some production debugging on this. I can see that once the leader (10.0.0.4) decides to down the node (10.0.15.96), it marks it as down, publishes the gossip but never removes the member.

```
overview = GossipOverview(
	seen=[UniqueAddress: (akka.tcp://SICluster@10.0.0.4:10000, 797030344)],
	reachability=Reachability(
		[akka.tcp://SICluster@10.0.15.89:10050 -> UniqueAddress: (akka.tcp://SICluster@10.0.15.96:10050, 217752204): Unreachable [Terminated] (4)]
		[akka.tcp://SICluster@10.0.15.227:10050 -> UniqueAddress: (akka.tcp://SICluster@10.0.15.96:10050, 217752204): Unreachable [Terminated] (1)]
		[akka.tcp://SICluster@10.0.0.4:10000 -> UniqueAddress: (akka.tcp://SICluster@10.0.15.96:10050, 217752204): Terminated [Terminated] (3)]
		[akka.tcp://SICluster@10.0.15.213:10050 -> UniqueAddress: (akka.tcp://SICluster@10.0.15.96:10050, 217752204): Unreachable [Terminated] (12)]
		[akka.tcp://SICluster@10.0.15.220:10050 -> UniqueAddress: (akka.tcp://SICluster@10.0.15.96:10050, 217752204): Unreachable [Terminated] (16)]
		[akka.tcp://SICluster@10.0.15.207:10050 -> UniqueAddress: (akka.tcp://SICluster@10.0.15.96:10050, 217752204): Unreachable [Terminated] (8)]
		[akka.tcp://SICluster@10.0.15.83:10051 -> UniqueAddress: (akka.tcp://SICluster@10.0.15.96:10050, 217752204): Unreachable [Terminated] (7)]
	)
)
``` 

It just keeps repeating that it will remove the old incarnation to let the new incarnation join.
I tried to force it to down by removing some checks in the ClusterDaemon and making it down even if it was already down. It simply kept saying it was downing the node, publishing the gossip but never actually removed the node.

Using pbm, running `cluster down-unreachable´ I can down the nodes and it will recover. I need to run it few times though. Sometimes when there are many unreachable nodes, it just hangs there indefinitely and I need to force-close and restart pbm multiple times until it works.

One thing here is that the cluster didn't had convergence at this point. Not sure if it should affect anything.

Not sure where to go from here, but I'll keep debugging this. If there are any tips on what I could look for, I can add some debugging code to production to see what is happening in these cases.

**Comment by Aaronontheweb** [comment] 2018-01-10 01:14
The common thread among all of these issues is the `Downing` command inside the `ClusterCoreDaemon`: https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka.Cluster/ClusterDaemon.cs#L1699

It appears to me that there are two things going on:

1. The way the gossip is merged following the issuance of a `Down` command isn't handled consistently unless ALL unreachable nodes are marked as `Down` at the same time. I can reproduce this easily using `pbm` and solo `cluster down -a {addr}` commands. Your logs and description confirm this too. This is a bug.
2. The way the reachability is set on nodes that are attempting to recover might be being overridden as well; I'm not 100% sure on this one yet as I haven't written a reproduction case for it, but that's my working theory for #3250

The good news is that this should be relatively easy to test and fix. I'm going to write a reproduction test case for the first issue and fix that first.

**Comment by Aaronontheweb** [comment] 2018-01-10 16:18
Can confirm that when multiple nodes are unreachable, can't transition a single unreachable node from its prior status to `Down`.

I can see the following appear in the logs:

```
Akka.Cluster.ClusterCoreDaemon: Marking unreachable node [akka.tcp://webcrawler@127.0.0.1:60269] as [Down]
```

But just like in our "node stuck at joining" issue from before, it appears as though the gossip isn't being received or updated correctly by the other nodes.

**Comment by Aaronontheweb** [comment] 2018-01-10 22:06
Well, it turns out that this is not a bug. It's by design with the way cluster convergence is supposed to work.

In order to `Remove` a `Downed` node, there needs to be convergence from the cluster. This means that in the event of a cluster that has multiple unreachable nodes:

1. All "unreachable" nodes in the cluster that are actually unreachable need to be downed at the same time. This is because the leader is still responsible for removing downed nodes from the cluster and it requires convergence from all reachable-non. Hence the `pbm cluster down-unreachable` command The reason this command might need to be run multiple times is because if the answer to the question "who is currently unreachable?" changes rapidly, then there might be new unreachable nodes that weren't detected before.
2. Any unreachable nodes in the cluster that are reachable need to become restored as "reachable" again.

It's possible that what you're seeing here is intentional behavior on the part of the cluster convergence system, but there might be an issue with the cluster heartbeat system once the cluster reaches a large enough size. I'm going to investigate that next by testing a several hundred node cluster, but that'll take me a little bit to setup on my end.

**Comment by nvivo** [comment] 2018-01-10 22:34
So, the problem may be that 2 is not working as expected? From that example I gave before, I had 6 unreachable nodes but only one was really down. They were unreachable for half an hour, then downing the bad node suddenly shows the others as Up.

When these problems happen, more and more nodes appear as unreachable as hours pass. May it be that only or a few one of those nodes are actually down, but the others cannot update their status for some reason, and I end up seeing lots of unreachable nodes by mistake?

**Comment by Aaronontheweb** [comment] 2018-01-10 22:53
> They were unreachable for half an hour, then downing the bad node suddenly shows the others as Up.

Now that's a different story... It could be that we've having issues similar to the ones originally reported here years ago: https://github.com/akka/akka/issues/16624

Have you tried messing around with your heartbeat settings at all, out of curiosity?

**Comment by Aaronontheweb** [comment] 2018-01-10 22:58
Other possibility is that if nodes have conflicting views of a single reachable / unreachable node, the gossip could be getting overwritten repeateadly. You'd see a rapid increase in the version counter of this was the case.

**Comment by nvivo** [comment] 2018-01-11 01:08
I'm currently using this config for the failure detector.

```
akka.cluster.failure-detector {
    heartbeat-interval = 3 s # default: 1 s
    acceptable-heartbeat-pause = 9 s # default: 3 s
    expected-response-after = 3 s # default: 1 s
}
```

The thing is that most of the time, when an instance is complaning about other, I can ssh into any of them, ping both from any side. I believe the unreachability status is something that akka believes is happening than something real. Tomorrow I'll see if I can setup to capture more logs.

**Comment by Aaronontheweb** [comment] 2018-01-11 03:00
> I believe the unreachability status is something that akka believes is happening than something real.

I believe you; the route I'm going to go to try to make it easier to reproduce this is #3264

**Closed** 2020-01-30 20:46 UTC
Labels: akka-cluster
