### ISSUE TITLE
unstable behavior in response to identify message 

### ISSUE THREAD

**Issue by mnoroozi1990** [akkadotnet/akka.net#6119] opened 2022-09-26 20:19 UTC
Version of Akka.NET? 1.4.38
Which Akka.NET Modules? Akka core

Hello everyone 
I have an actor that inherits from AtLesatOnceDelivery actor.
In one of my message handlers, I create an actor and send 3 messages to that for handling a message.
The problem is that, just one of those three messages delivered to that actor and the others missed.
I try to send Identify message to newly created actor before sending each messages.
I just received one ActorIdentity instead of three.

It happens usually what I described above, but some times every things work fine and there is no problem.
This instability makes me confused.

thanks in advance for helping
 
**Environment**
I'm using Rider on windows and .net core 3.1.

**Comment by Aaronontheweb** [comment] 2022-09-28 08:21
Can you show us some source code to demonstrate the issue? I don't entirely follow it just by reading the description

**Comment by mnoroozi1990** [comment] 2022-09-28 10:08
I must add some more description bellow
1- I send Identify message to code just for troubleshooting and it's not the part of source code.
2- After sending message1 to customerActor, It receives message1 and handles it without any exception or error.
3- customerActor is there and before sending messages to it, I check it to ensure that it's not Nobody.
4- Unit tests always pass and customerActor receives three messages always.
5- when I run the the entire process, some times it works as I expect but some times it doesn't work.
6- message2 and message3 don't move to deadletter.
7- In HandlerMessageY I check to see if customerActor exists or not and I always receive positive answer and it's always there.

![Issue](https://user-images.githubusercontent.com/108398024/192752359-d147f242-c0ec-4126-a039-5696f0a8db62.jpg)

**Comment by mnoroozi1990** [comment] 2022-09-29 10:19
> Can you show us some source code to demonstrate the issue? I don't entirely follow it just by reading the description

I must add some more description bellow
1- I send Identify message just for troubleshooting and it's not the part of source code.
2- After sending message1 to customerActor, It receives message1 and handles it without any exception or error.
3- customerActor is there and before sending messages to it, I check it to ensure that it's not Nobody.
4- Unit tests always pass and customerActor receives three messages always.
5- when I run the the entire process, some times it works as I expect but some times it doesn't work.
6- message2 and message3 don't move to deadletter.
7- In HandlerMessageY I check to see if customerActor exists or not and I always receive positive answer and it's always there.
8- I'm using Serilog for logging and elasticsearch sink

![Issue](https://user-images.githubusercontent.com/108398024/192752359-d147f242-c0ec-4126-a039-5696f0a8db62.jpg)

**Comment by Arkatufus** [comment] 2022-10-06 18:55
@mnoroozi1990 
Can you check in your logs that there is no "Actor name "Test1" is not unique!" error when this happens?

**Comment by Arkatufus** [comment] 2022-10-06 19:23
@mnoroozi1990
As #6153 shows, we could not reproduce your bug.
If your test method is exactly as you've shown above, you can not have 2 actors with identical name, that will cause a collision.
Are you sure that the spawned actor did not kill itself?

**Comment by to11mtm** [comment] 2022-10-07 23:48
As an additional question @mnoroozi1990 , what persistence are you using in your tests? is it the in-memory journal or a different custom journal?

**Comment by Aaronontheweb** [comment] 2022-10-21 14:06
Closing as won't fix - could not reproduce.

**Closed by Aaronontheweb** 2022-10-21 14:06 UTC
Labels: potential bug
