### ISSUE TITLE
Add timeout to F# Ask operator

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#1042] opened 2015-06-04 23:33 UTC
Feedback from one of our trainees

> You were correct that the <? (Ask) operator does not specify any timeout. That makes it of pretty limited usefulness, since it seems like most times we want to use a timeout. Maybe this operator should have a default timeout? Otherwise, the documentation should warn users about how they could be setting themselves up for a deadlock when using this operator.

Sounds like we need to add the ability to pass a timeout to the F# Ask operator. What's the easiest way to do that?

**Comment by jtmueller** [comment] 2015-06-05 00:00
The problem is that custom operators can only have two arguments, and the `<?` operator already has two. The only way to add in a timeout argument would be to change one of the arguments to a compound value like a tuple. Something like...

`let! result = actor <? (SomeMessage, TimeSpan.FromSeconds(1.0))`

But that syntax means you're required to specify a timeout. Another option would be to keep the syntax as-is, but have the operator itself specify a default timeout. When you want a non-default timeout, or no timeout, you use the `Ask` method.

Speaking of the `Ask` method, I ended up writing this useful extension method that I expect other users of the F# API could benefit from...

    type ICanTell with
        member x.Ask(msg:obj, ?timeout:TimeSpan) =
            // As of F# 4.0, I'd use Option.toNullable instead of this match statement
            let timeout = match timeout with Some t -> Nullable(t) | None -> Nullable()
            x.Ask(msg, timeout) |> Async.AwaitTask

This extension method lets me write code like this:

    async {
        let! response = selection.Ask(Internal(GetActorRef), TimeSpan.FromSeconds(1.5))
        // do stuff
        return something
    }

Without that extension method, I'm forced to write all this boiler-plate every time I call `Ask`:

    async {
        let! response = selection.Ask(Internal(GetActorRef), Nullable(TimeSpan.FromSeconds(1.5))) |> Async.AwaitTask
        // do stuff
        return something
    }

**Comment by Horusiath** [comment] 2015-06-06 09:16
We could actually introduce overload over `ICanTell` interface to use F#-style optional timeout parameter. But changing ask operator would be harder - it will break existing API.

Scala has a notion of implicit parameters. Once variable with *implicit* keyword is introduced, it gets applied implicitly to all `?` operators in the same scope. We could mock similar behavior in Akka.NET - however this would be probably require some changes in akka core, rather than on F# API level.

My idea was to introduce DefaultTimeout field of type `TimeSpan?` inside ActorSystem or current Context, which could be set by the user. Other ideas? /cc @akkadotnet/developers

**Comment by rogeralsing** [comment] 2015-06-07 06:42
IMO we should have a global timeout setting in the config also.
Asking with unlimited timeout is just asking for problems (<- see what i did there :) )

**Comment by Horusiath** [comment] 2016-01-20 09:01
Closed by #1053

**Closed by Horusiath** 2016-01-20 09:01 UTC
Labels: akka-fsharp, discussion, enhancement
