### ISSUE TITLE
Akka.Cluster problem on seed node rejoin

### ISSUE THREAD

**Issue by Horusiath** [akkadotnet/akka.net#1359] opened 2015-10-05 16:54 UTC
From @christiansparre:

> We have 4 members, two of them are seed nodes. When shutting down the leader, the remaining seed node is elected leader. If we shutdown that node, one of the remaining two non-seed nodes are elected leader. This is what we expected. However if we start one of the original seed nodes again we see the following error on the remaining two non-seed nodes. And that node is not "allowed" to join and remains out in the cold. 

This is the error: "Association to [akka.tcp://clustertest@127.0.0.1:7000] having UID [443331660] is irrecoverably failed. UID is now quarantined and all messages to this UID will be delivered to dead letters. Remote actorsystem must be restarted to recover from this situation."

**Comment by Aaronontheweb** [comment] 2015-10-05 19:21
I need more info on this, but sounds like working-as-intended to me. If the leader was shutdown but never DOWNED from the cluster, it won't be able to rejoin.

So questions for @christiansparre 

1. Was `akka.cluster.auto-down` turned on or was the leader manually downed when it was shutdown? Or neither?
2. How was the seed node able to contact the non-seed nodes if it was downed? Configuration change?

**Comment by rogeralsing** [comment] 2015-10-05 19:26
If the leader comes online as a new system, restarted, with a new UID, it should not be considered the same system, no?
Even the error message says that restarting should be enough to fix the problem **"Remote actorsystem must be restarted to recover from this situation"**

I'll make some Scala examples to test out our Cluster/Remoting behaviors

**Comment by Aaronontheweb** [comment] 2015-10-05 19:29
> If the leader comes online as a new system, restarted, with a new UID, it should not be considered the same system, no?

Correct, but how can it join a non-seed node if it was downed?

**Comment by rogeralsing** [comment] 2015-10-05 19:55
If both seed nodes are shut down, and one of them are brought back online. how can that not even know about the other non seed nodes?
The old workers knew about the two original seed nodes, with their old UID's., the newly started seednode will have a different UID.

This _should_ result in two separate clusters, no?

**Comment by Aaronontheweb** [comment] 2015-10-05 20:03
> If both seed nodes are shut down, and one of them are brought back online. how can that not even know about the other non seed nodes?

Exactly - that's why I'm asking. Need the rest of that information before we can classify this as a bug or not.

**Comment by rogeralsing** [comment] 2015-10-05 20:04
Tried this in Scala and as I said in the above post, the restarted seednode does not join the old cluster as none of the nodes sees eachother.
The old nodes knows about the two dead seed nodes and their UIDs.
And the new seednode does not know about the old nodes.
They are not even trying to communicate.

If in Akka.NET the old nodes are trying to communicate back to the restarted node, then there is some sort of UID bug going on

**Comment by rogeralsing** [comment] 2015-10-05 20:08
This could also just be a logging problem, I assume the nodes in scala will still communicate back to the new node as they have no idea of knowing what UID the new node have, but there is nothing visible that it was rejected, it might just be that we log that interaction.

**Comment by christiansparre** [comment] 2015-10-05 20:18
@Aaronontheweb 

1. I have auto-down-unreachable-after = 10s
2. I'm not sure I understand, when starting one of the seed nodes the error come on one of the non-seed nodes so my guess is that the non-seed node saw the seed node but did not recognize the UID. We made no config change. 

We saw the problem in a system on our test environment and I decided to make a simple console app i could start with different ports.

If I'm to understand the above it is the expected behaviour that if all our seed nodes become unavailable the entire cluster should be restarted to recover?

To us it's quite scary that we could end up in a situation with more than one cluster :) What is the recommended way to discover this situation and recover from it?

Thanks for your feedback guys.

**Comment by Aaronontheweb** [comment] 2015-10-05 21:47
> To us it's quite scary that we could end up in a situation with more than one cluster :) What is the recommended way to discover this situation and recover from it?

Never use auto-down. You will end up with split brains 100% of the time you use it.

**Comment by Aaronontheweb** [comment] 2015-10-05 21:54
> If I'm to understand the above it is the expected behaviour that if all our seed nodes become unavailable the entire cluster should be restarted to recover?

No, you have to be able to issue a `Down` command from one of the available nodes to remove it from cluster membership.

Think of it this way: killing a process that's in the cluster is treated as a temporary failure, and the cluster's consensus algorithm depends on unanimous consent. If a node goes `Unreachable`, it's expected to return at some point unless it's explicitly marked as `Down` by one of the other nodes. So if a new node tries to join the cluster membership while those old nodes are still unreachable, the voting required by the members to allow that new node into the cluster membership can't occur - because there are members who are unreachable who can't vote.

This mechanism relies on humans to issue `Down` commands in response to reachability events right now; you'll want to write a Web API method or something that can kick an unreachable node out via a `Down` command. 

Cassandra and other distributed systems that use this Dynamo-style cluster also work that way, so this isn't unusual - it's just relying on humans to decide what's an irrecoverable hard-down vs. an intermittent outage. Doing this automatically (which auto-down does) is difficult to do reliably.

**Comment by christiansparre** [comment] 2015-10-06 07:32
Ok, I think I understand the reasoning. Do you have any examples of how to achieve the "Down'ing" of members? For one how do you handle this during deployment? Do you specifically down members as part of the deployment steps?

**Comment by Horusiath** [comment] 2015-10-06 07:37
I think, that no matter what, we should at least provide some friendlier message for user informing about what actually happened and what is possible reason of the problem.

**Comment by christiansparre** [comment] 2015-10-06 07:46
I my test I have ```auto-down-unreachable-after = off```. When I terminate a non-seed node we also see the above message when starting that node again. However it is allowed to join after a while. It also works for a seed-node but, when all the seed-nodes terminate then we have the problem and end up with two separate clusters. Are there any suggestions to handling this situation when you loose all the seed-nodes?

**Comment by rogeralsing** [comment] 2015-10-06 09:36
I'm verifying this against the Scala bits.
In Scala, when **auto down is set to off**, the restarted seed node is accepted back into the cluster.
While if **auto down is set to on**, the restarted seed node is **not** accepted back into the cluster.

This was also verified by Konrad/Typesafe

>rogeralsing 11:32:in a cluster scenario where there are some active worker nodes and all seed nodes goes down, and autodown is set to off, what is the expected behavior when a seednode comes back online? should the preexisting workers be able to re-establish a connection and let the seed back in.. or is the intended behavior that we see two different clusters , one with just the restarted seed and one with all the workers?

>ktoso 11:33:   @rogeralsing no partition should happen then. Since the node was never declared "down".

>rogeralsing 11:34: @ktoso and if auto down is on, then there should be a partition, right?

>ktoso 11:34: yeah

**Comment by ktoso** [comment] 2015-10-06 09:59
Not so fast @rogeralsing, as I mentioned on the chat - I missed from your question that all seed-nodes are down at some point in time which changes the story here.

Since all seed-nodes went down, and then come back up again yet there is no node that knows about the worker nodes - i.e. there is a time when no seed node is alive, to relay the information about the previous cluster. Then yes, in this situation a partition will happen.

What you could do to guard against this is to down the worker nodes once they detect none of the seed nodes are available anymore for example. 

// We've provided a number of strategies to deal with more complex downing scenarios as well, it's the Split Brain Sesolver: doc.akka.io/docs/akka/rp-15v09p01/scala/split-brain-resolver.html

**Comment by rogeralsing** [comment] 2015-10-06 10:57
I am definitely seeing the restarted seed node coming back into the cluster.

starting the entire cluster, 2 seed nodes, one worker node
cluster is formed
I kill seed 1 and seed 2
Waiting 1 min
Restarting seed 1
seed 1 is now accepted back into the cluster

worker
https://gist.github.com/rogeralsing/12dbe4745f5837f90940

seed
https://gist.github.com/rogeralsing/1affb84c004682c206d8

This is a screenshot of the worker node after the seed node have been restarted:
![seedbackonline](https://cloud.githubusercontent.com/assets/647031/10306811/bde6ce7e-6c29-11e5-95a5-42ae9175523b.png)

**Comment by patriknw** [comment] 2015-10-06 12:20
how do you observe "seed 2 is now accepted back into the cluster"?

**Comment by patriknw** [comment] 2015-10-06 12:22
being able to send a message with

    context.system.actorSelection("akka.tcp://ClusterSystem@127.0.0.1:8090/user/dummy").tell("hello", self)

doesn't mean that it is part of the cluster

**Comment by rogeralsing** [comment] 2015-10-06 13:24
It sends messages to the worker.
The output is from the worker showing messages from the seed.

Skickat från min iPhone

**Comment by rogeralsing** [comment] 2015-10-06 13:26
Oh, my bad.
So cluster gossip would be a more correct way then (?)

Skickat från min iPhone

**Comment by Aaronontheweb** [comment] 2015-10-06 14:33
@rogeralsing can we close this then?

@Horusiath users need is monitoring for this, because you have to reconstruct the gossip status messages over time to get a clear picture of what happened. It's like a combination of several log messages across multiple nodes in the cluster.

**Comment by rogeralsing** [comment] 2015-10-06 14:34
@Aaronontheweb yes, but I think our log message is wrong(ish)
*"Remote actorsystem must be restarted to recover from this situation."* will not solve the problem

**Comment by emilingerslev** [comment] 2015-10-07 06:10
Investigating this issue I found that a cluster that loses one or more node (that then becomes unreachable) the cluster seems not too accept any new nodes before all node are reachable again.

This means if you have more than two seed nodes, and two of them goes missing if fx they crash, the cluster will only accept the the newly started seed nodes when both are up. This is of cause only true when auto-down is off. 

I've made this little playground project for testing and playing with the cluster behavior: https://github.com/ingerslevio/akkanet-cluster-test

Using above mentioned project its easy to observe the behavior by starting four nodes

```
> .\AkkaTest.exe 7000 7000 7001 7002           # SeedNode 1
> .\AkkaTest.exe 7001 7000 7001 7002           # SeedNode 2
> .\AkkaTest.exe 7002 7000 7001 7002           # SeedNode 3
> .\AkkaTest.exe 7003 7000 7001 7002           # Worker 1
```

Any of the above nodes can execute a `status` while running, showing their view of cluster (using their `Cluster.ReadView`), and watching this is easy to see the behavior:

* Start all 3 seed nodes and worker
* Kill any 2 nodes
* Start one of the nodes again
* Issue a `status` on any of the nodes.

You'll see that two of the nodes are still unreachable. Only when starting the last node it will become reachable again. But as @Aaronontheweb already talked about, issuing a `Down` manually for all the missing nodes the cluster becomes able to accept nodes again.

Is this the true behavior of how it should work? That is, can a cluster with unreachable nodes not accept new nodes before all are up again or `Down` commands are issued?

**Comment by patriknw** [comment] 2015-10-07 08:02
Yes, works as designed.

**Comment by emilingerslev** [comment] 2015-10-08 08:50
@patriknw Alright. Good to know. Then I agree with @Aaronontheweb and @rogeralsing that the only thing that could be improved here seems to be the log message.

**Comment by rogeralsing** [comment] 2015-10-08 15:55
I'm closing this one

**Closed by rogeralsing** 2015-10-08 15:55 UTC
Labels: akka-cluster, akka-remote, potential bug
