### ISSUE TITLE
When using clustered pool, if use-local-routees is on, it seems to ignore the use-role property

### ISSUE THREAD

**Issue by jrlost** [akkadotnet/akka.net#2783] opened 2017-06-22 15:01 UTC
I'm attempting to implement a simple two node cluster (example: https://github.com/jrlost/AkkaNetRoutingTest). I'm seeing that when using a clustered pool, if use-local-routees is on, it seems to ignore the use-role property. Similar to what's outlined here: https://github.com/akka/akka/issues/15042

**Comment by Aaronontheweb** [comment] 2017-06-25 17:30
I'll investigate this for 1.2.2

**Comment by Aaronontheweb** [comment] 2017-06-26 21:34
Turns out we had a test that was commented out for `UseRoleIgnored`... uncommented it and it passes just fine. 

Just for a sanity check, which version of Akka.NET are you using?

**Comment by Aaronontheweb** [comment] 2017-06-26 21:36
Aha. Spoke to soon. The spec fails; I just needed to do a full rebuild first. Got it reproduced. Will have a fix soon.

**Comment by Aaronontheweb** [comment] 2017-06-27 22:11
closed by #2802

**Closed by Aaronontheweb** 2017-06-27 22:11 UTC
Labels: akka-cluster, potential bug
