### ISSUE TITLE
TCP sessions are timeout and showing problems to reestablish messages between them

### ISSUE THREAD

**Issue by vncoelho** [akkadotnet/akka.net#3648] opened 2018-11-14 14:59 UTC
It is a very strange situation, some nodes still connect and send some messages, but some types of messages do not arrive and are kind of discarded.

This mostly happen when a node looses connection and tries to get back to the "cluster"

We have the following logs that may be usefull:

```cs
[ERROR][11/11/2018 22:00:09][Thread 0003][akka://NeoSystem/user/$b] Error while creating actor instance of type Neo.Network.P2P.LocalNode with 1 args: (Neo.NeoSystem)
Cause: [akka://NeoSystem/user/$b#837781826]: Akka.Actor.PostRestartException: Exception post restart (System.Net.Sockets.SocketException) ---> System.TypeLoadException: Error while creating actor instance of type Neo.Network.P2P.LocalNode with 1 args: (Neo.NeoSystem) ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Neo.Network.P2P.LocalNode..ctor(NeoSystem system)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Akka.Actor.Props.ActivatorProducer.Produce()
   at Akka.Actor.Props.NewActor()
   --- End of inner exception stack trace ---
   at Akka.Actor.Props.NewActor()
   at Akka.Actor.ActorCell.CreateNewActorInstance()
   at Akka.Actor.ActorCell.<>c__DisplayClass109_0.<NewActor>b__0()
   at Akka.Actor.ActorCell.UseThreadContext(Action action)
   at Akka.Actor.ActorCell.NewActor()
   at Akka.Actor.ActorCell.FinishRecreate(Exception cause, ActorBase failedActor)
   --- End of inner exception stack trace ---
```

Object  Terminated was invoked before, closing all connections. 
```cs
public sealed class Terminated : IAutoReceivedMessage, IPossiblyHarmful, IDeadLetterSuppression, INoSerializationVerificationNeeded
```

Then, as described, nodes struggle to recover a health connection.

When creating a new issue, please make sure the following information is part of your issue description. (if applicable). Thank You!

**- Which Akka.Net version you are using**
<PackageReference Include="Akka" Version="1.3.10" />

**- On which platform you are using Akka.Net**
Running on isolated docker containers Ubuntu 18.04 as well as in Windows Apache Servers Enviroments.
We use this in partnership with https://github.com/neo-project/neo P2P communication protocol.

**- A list of steps to reproduce the issue. Or an gist or github repo which can be easily used to reproduce your case.**
In general it requires creating a swarm of connected TCP sessions.
If needed we can describe more about our setup on the Neo Blockchain. Do not hesitate to ask.

**Comment by Aaronontheweb** [comment] 2018-11-14 22:33
@vncoelho what version of .NET Core are you running on?

**Comment by vncoelho** [comment] 2018-11-15 00:04
@Aaronontheweb, first of all, thanks for your professionalism, quick response and attention with our issue.

I fell more comfortable with c++ programming...I do know much about .NET configuration.
The config files are:
https://github.com/neo-project/neo/blob/master/neo/neo.csproj
https://github.com/neo-project/neo-cli/blob/master/neo-cli/neo-cli.csproj

```cs
One file has
<TargetFrameworks>netstandard2.0;net47</TargetFrameworks>
The other one has:
<TargetFramework>netcoreapp2.0</TargetFramework>
```

**Comment by Aaronontheweb** [comment] 2018-11-15 00:07
Looks like net core 2.0

**Comment by Horusiath** [comment] 2018-11-15 13:45
From the stack trace it looks like the source of the exception is `Neo.Network.P2P.LocalNode` constructor.. It's not a part of Akka.NET. What does this class is supposed to do?

**Comment by vncoelho** [comment] 2018-11-15 15:02
Hi @Horusiath,

I think you are right.
Through another investigation a problem was noticed when a socket connection was being made:

```cs
                s.ReceiveTimeout = (int)TimeOut.TotalMilliseconds;
                s.SetSocketOption(SocketOptionLevel.Socket, SocketOptionName.Broadcast, 1);
                string req = "M-SEARCH * HTTP/1.1\r\n" +
                "HOST: 239.255.255.250:1900\r\n" +
                "ST:upnp:rootdevice\r\n" +
                "MAN:\"ssdp:discover\"\r\n" +
                "MX:3\r\n\r\n";
                byte[] data = Encoding.ASCII.GetBytes(req);
                IPEndPoint ipe = new IPEndPoint(IPAddress.Broadcast, 1900);
                s.SendTo(data, ipe);
```

This SendTo was the source of the problem when reconnecting.

I think it is not a problem related to Akka .Net.
It should be something related to this Socket not closing the session in the right manner during the last operation.

Maybe let's close this issue, right?

**Comment by Horusiath** [comment] 2018-11-15 16:01
@vncoelho sure, if you think it's not akka related, feel free to close it. You can always reopen it at any time if it'll turn out otherwise.

**Closed** 2018-11-15 17:19 UTC
Labels: akka-io

**Comment by yongjiema** [comment] 2018-11-16 03:39
@vncoelho Looks like the problem is the LocalNode actor is failed to restart due to it violate the singleton rule.

**Comment by superboyiii** [comment] 2019-02-08 12:33
@yongjiema Could you explain more detail about this situation? One exchange also met this problem after running neo-cli2.9.4 for several weeks.

**Comment by yongjiema** [comment] 2019-02-15 02:47
@superboyiii https://github.com/neo-project/neo/blob/master/neo/Network/P2P/LocalNode.cs#L54, The error is happening while any error is occurred in LocalNode as Akka try to recreate it but violate the singleton rule.

**Comment by Aaronontheweb** [comment] 2019-02-15 04:05
I'd need to look at the source, but this seems like something we can fix
