### ISSUE TITLE
Akka.DistributedData: memory leak when recovering events from LMDB data store

### ISSUE THREAD

**Issue by Aaronontheweb** [akkadotnet/akka.net#5022] opened 2021-05-19 20:06 UTC
Version: Akka.NET v1.4.19

Reproduction: https://github.com/andyfurnival/ddata 

Memory consumption grows steadily in a 2 node cluster, with both nodes recovering events from their own LMDB data stores:

![image](https://user-images.githubusercontent.com/326939/118873569-867c1b00-b8af-11eb-9796-2654a04f7c73.png)

The drivers of memory consumption appear to be non-stop gossip between the replicators:

![image](https://user-images.githubusercontent.com/326939/118876994-841bc000-b8b3-11eb-9df3-c7a476eb93a5.png)

I think there must be an equality check that is failing somewhere in this system, causing the same objects to be gossiped over and over again. We're not even producing any new events other than what's been deserialized from LMDB in this sample and yet the memory grows continuously.

**Comment by Aaronontheweb** [comment] 2021-05-19 21:06
Based on the logs, looks like this system is trying to continuously prune the data envelopes loaded from storage:

```
[DEBUG][5/19/2021 8:07:20 PM][Thread 0007][akka.tcp://test@desktop-1go6og2:18001/user/ddataReplicator] Initiating pruning of UniqueAddress: (akka.tcp://test@eng07-bet-mgmt-7.engineering.nonprod.sharpgaming.net:4256, 326986514) with data Event-75016
[DEBUG][5/19/2021 8:07:20 PM][Thread 0007][akka.tcp://test@desktop-1go6og2:18001/user/ddataReplicator] Initiating pruning of UniqueAddress: (akka.tcp://test@eng07-bet-mgmt-4.engineering.nonprod.sharpgaming.net:4256, 501230574) with data Event-75016
[DEBUG][5/19/2021 8:07:20 PM][Thread 0007][akka.tcp://test@desktop-1go6og2:18001/user/ddataReplicator] Initiating pruning of UniqueAddress: (akka.tcp://test@eng07-bet-mgmt-7.engineering.nonprod.sharpgaming.net:4256, 636684864) with data Event-75016
[DEBUG][5/19/2021 8:07:20 PM][Thread 0007][akka.tcp://test@desktop-1go6og2:18001/user/ddataReplicator] Initiating pruning of UniqueAddress: (akka.tcp://test@eng07-bet-mgmt-3.engineering.nonprod.sharpgaming.net:4256, 837357637) with data Event-75016
[DEBUG][5/19/2021 8:07:20 PM][Thread 0007][akka.tcp://test@desktop-1go6og2:18001/user/ddataReplicator] Initiating pruning of UniqueAddress: (akka.tcp://test@eng07-bet-mgmt-4.engineering.nonprod.sharpgaming.net:4256, 32551767) with data Event-74994
[DEBUG][5/19/2021 8:07:20 PM][Thread 0007][akka.tcp://test@desktop-1go6og2:18001/user/ddataReplicator] Initiating pruning of UniqueAddress: (akka.tcp://test@eng07-bet-mgmt-7.engineering.nonprod.sharpgaming.net:4256, 326986514) with data Event-74994
[DEBUG][5/19/2021 8:07:20 PM][Thread 0007][akka.tcp://test@desktop-1go6og2:18001/user/ddataReplicator] Initiating pruning of UniqueAddress: (akka.tcp://test@eng07-bet-mgmt-4.engineering.nonprod.sharpgaming.net:4256, 501230574) with data Event-74994
```

This might be due to the fact that the node we originally recovered this data from no longer exists (indeed, that would likely be the case in the event of any `ActorSystem` restards since the `Uid` on the `UniqueAddress` will change) - I'll start by looking there.

**Comment by Aaronontheweb** [comment] 2021-05-19 21:15
Also worth noting that we're attempting to prune many different unique addresses for the same `Address` in those logs - the `Uid`s are different but it's all originally from the same node.

**Comment by andyfurnival** [comment] 2021-05-27 08:25
Are these improvements that have been done so far in a nightly build I can try?

**Comment by ismaelhamed** [comment] 2021-05-27 08:54
Here's how to get the nightly builds: https://getakka.net/community/getting-access-to-nightly-builds.html . Anything merged into `dev` should be available the same night.

**Comment by Arkatufus** [comment] 2021-05-27 14:13
Initial observations:
- Memory usage spiked with DistributedData cluster

Possible causes:
- Memory leaks or non-optimized memory allocation. (not the cause)
  - [x] String allocation from several places
    - [x] MurmurHash. 
    - [x] Old style `string.Format`. 
    - [x] Address constructor
  - [x] Byte array allocation during serialization. 
- Gossip and Status isn't sent with proper address UID (not the cause)
  - [x] Make from and to UID in gossip and status construtor mandatory
  - [x] Change Replicator to use UniqueAddress exclusively

Further observations:
- Mutiple gossips are sent right after pruning is initialized and removed path count is above 0
- Gossips were retained in the mailbox, bloating memory usage
- Problem is compounded in a system with a lot of pruning, since all of the pruning data are also serialized with each gossip round

**Closed** 2021-06-02 01:54 UTC
Labels: akka-ddata, akka-ddata-durable, confirmed bug
