### ISSUE TITLE
Scheduler API testability vs usability

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#873] opened 2015-04-18 04:51 UTC
In retrospect to our 1.0 release, I'd like to discuss how we should evolve the API.

My primary concern is the scheduler API.
The API was changed to expose `ICancelable` and hide the underlying TPL parts.
One of the reasons was testability, to be able to alter and modify "time", make time go faster, as TPL `Task.Delay` can not be mocked.

That is a nice goal, but we lose quite a bit of other features.
I know @Aaronontheweb wants to be able to run actions on specific `TaskSchedulers`.
By hiding every trace of TPL in the scheduler API, makes hard to accomplish this goal. 

We can not mix and match TPL stuff and the abstracted API, as it makes the abstraction rather pointless IMO.

For example, if there is a scheduler implementation that does not use TPL behind the scenes, it would be odd if the scheduler API has arguments for `TaskSchedulers`.

We can not deny that the TPL is an integral part of the .NET platform, and as such I think we need to be able to use those features internally.

So how do we combine these features?
Should we publicly state that the scheduler will be TPL based and only allow this implementation?
and thus make it possible to use TPL features in the IScheduler API?

**Comment by Horusiath** [comment] 2015-04-18 06:58
I like that current schedulers implementation abstracted TPL away. If internal schedulers TPL access is really needed, maybe we could simply prepare other version of scheduler interface (exposing tasks) and made i.e. an extension method which could return it on demand.

**Comment by Aaronontheweb** [comment] 2015-04-18 16:44
I think @Horusiath's attitude is right - fundamentally we need a way to allow the `IScheduler` to benefit from Akka's concurrency abstractions, namely the dispatchers. But this can be accomplished without a lot of upheaval.

One of us should take a stab at doing this - goal of the API should be to allow the end user to allow explicit `ScheduleXXX` calls onto the actor's dispatcher. Any other big ticket items?

**Comment by HCanber** [comment] 2015-04-19 12:23
I'm confused. I'm so confused I'm not even clear about what and why I'm confused. :) This is the way I see it:

- `MessageDispatcher` is used in conjunction with actors and mailboxes to handle concurrency (via messages). There are (possibly) __many__ instances of dispatchers in a system.
- The `ITellScheduler` is used for postponing when a message should be sent. The `IActionScheduler` is used for postponing actions. The Scheduler makes _no_ concurrency guarantees (which is by design). There is __one__ scheduler in the system. 

The `IActionScheduler` should very rarely be used. That's why it's behind the `Advanced` property. It is meant to be used with very light weight operations, like completing a promise or using some other concurrency signalling primitives. It's not meant to be used as an all purpose I-want-to-schedule-anything. If you need concurrency guarantees or things to be run on the dispatcher, you need to channel it into the correct primitive: an Actor.

So I don't understand what it is you want to be able to do. :) Do you, inside an actor, want to postpone an action on the actor's dispatcher? Use the `ITellScheduler` and implement a message handler.

**Comment by nvivo** [comment] 2015-04-19 12:39
I agree that scheduling actions in an actor is kinda confusing for an user. I started doing that, but it's not clear anywhere if it gives the same guarantees as telling.

Moving those overloads to "Advanced" at least made me think twice before using them. At some point I decided to "schedule tell" because it makes the logic cleaner. Still today I'm not sure what are good use cases (for users) to schedule actions instead of messages.

**Comment by rogeralsing** [comment] 2015-04-19 13:10
@HCanber the issue at hand is the noisy neighbor problem, lets say the standard threadpool is saturated due to high load, important sysmessages inside e.g. Cluster might not be sent on time as there are other actions/tasks/messages waiting to run on the `ThreadPool`

Some system actors now run on the dedicated ForkJoinThreadPool to prevent this problem.
The ITellScheduler impl has a `Task.Delay` and a `ContinueWith`

The Delay shouldn't be a problems as that completes on an IO completion port thread in the threadpool, those are not the same as the standard worker threads in the pool.
It could possibly be a problem if there a lot of IO completions, but I guess if that is the case, one got bigger issues.

The `ContinueWith` will run using the current TaskScheduler.
So far so good.

But, the ForkJoinThreadPool does not execute it's stuff using a TaskScheduler.
So in this case the ContinueWith will be executing on the default ThreadPool (unless something is reconfigured)
Which may result in the ContinueWith running too late due to the above mentioned saturation, and the Tell to the important System actor does not arrive on time.

This can absolutely be fixed, just trying to point out the problem that needs to be solved.

**Comment by rogeralsing** [comment] 2015-04-19 13:13
That beeing said, the ForkJoinDispatcher should probably be setting a TaskScheduler and run ontop of that, as any tasks started from the actors probably require the same level of priority.

**Comment by HCanber** [comment] 2015-04-19 14:05
Hmm... I still don't understand how the scheduler is going to know which dispatcher you're using. As I said, a system has several dispatchers, but only one scheduler.

If I understand you correctly, the problem you're describing isn't really about problem with the api. And the solution is not that the scheduler should use the "current" dispatcher (whatever that is since you can schedule things from outside an actor when no dispatcher is in place). It's a problem with that the current implementation and that it can become saturated. Correct?

Akka JVM has a `LightArrayRevolverScheduler` that's used by default (specified in config) which receives a thread pool factory by the `ActorSystem`, which will be a `MonitorableThreadFactory`, that uses `ForkJoinPool.ForkJoinWorkerThreadFactory`.

Is that what we should do as well?

**Comment by Aaronontheweb** [comment] 2015-04-20 00:33
> Hmm... I still don't understand how the scheduler is going to know which dispatcher you're using. As I said, a system has several dispatchers, but only one scheduler.

This might have to be passed in explicitly as part of the call. I'll play around with putting an implementation together.

**Comment by HCanber** [comment] 2015-04-20 06:07
>> Hmm... I still don't understand how the scheduler is going to know which dispatcher you're using. As I said, a system has several dispatchers, but only one scheduler.

>This might have to be passed in explicitly as part of the call. I'll play around with putting an implementation together.

What's the use case, when exactly do you want to use that?

**Comment by Aaronontheweb** [comment] 2015-04-20 18:07
@HCanber whoops, looks like Github doesn't like my email replies :p 

The use case for this is the same as when we need a ForkJoinDispatcher - exclusive scheduling for actors with soft real-time requirements. Heartbeats in particular.

This is one of the reported causes of cluster nodes being marked as down by accident on busy systems - inability of heartbeat messages to fire off in time. This comes up in systems that are making the heavy use of the TPL - happens a lot in production systems that use a lot of async service calls.  I've personally observed this running some of Petabridge's samples and production Akka.Remote / Akka.Cluster users have reported it too. Not a myth - definitely an actual problem that occurs on busy systems.

Maybe the right way to solve this problem isn't using the dispatcher - it might be as simple as giving the scheduler its own `DedicatedThreadPool` instance (it comes with a `TaskScheduler`.)

That's what the JVM does:

https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/actor/ActorSystem.scala#L714

ThreadPools are all instanced inside the JVM, whereas they're totally static in the CLR. Our implementation (meaning .NET in general) works great for ease of use and lowers the likelihood of developers shooting themselves in the foot, but in non-trivial systems you lose the ability to determine if your action will even get scheduled onto a thread within your soft real-time constraint, let alone executed by the operating system.

Through the use of exclusive thread pools with independent work queues we can make stronger guarantees about the availability of threads for work. Still doesn't guarantee that the OS will schedule it on-time but it increases the likelihood drastically.

So we can do it that way - give the `Scheduler` its own `DedicatedThreadPool` and test that? Or allow the developer to bind specific scheduled messages to their dispatcher's threadpool explicitly for special cases or something similar. Which would you prefer?

**Comment by HCanber** [comment] 2015-04-21 16:28
I think what's been bugging me is the name `MessageDispatcher`. In my head `MessageDispatcher`s are used for scheduling mailbox runs, not for scheduling any action, and not for handling sends . So using a `MessageDispatcher` for something else than scheduling mailbox runs is sort of abusing it. 

On the other hand when I looked more closely, in Akka JVM a `MessageDispatcher` also is an [ExecutionContext](http://www.scala-lang.org/api/2.11.5/index.html#scala.concurrent.ExecutionContext) meaning it can execute any [Runnable](http://docs.oracle.com/javase/7/docs/api/java/lang/Runnable.html) asynchronously, which in C# would translate to that it can run any `Action` asynchronously.

The `Scheduler` in Akka JVM takes an `ExecutionContext` as an implicit argument, meaning it will run what's scheduled on the current `ExecutionContext`, unless another `ExecutionContext` is specified, which very well can be a `MessageDispatcher`.

So, I've changed my mind. :) A `MessageDispatcher` can be used as an optional argument to the scheduler. So let's do that.

**Comment by Aaronontheweb** [comment] 2015-04-21 16:40
@HCanber great! I like that approach better than messing with the `Scheduler`'s threadpool.

Each dispatcher has a `Schedule(Action<>)` method, so we could probably use that under the hood. Inside the `ForkJoinDispatcher` we can have it wrap its `DedicatedThreadPool` with one of these https://github.com/akkadotnet/akka.net/blob/dev/src/core/Akka/Helios.Concurrency.DedicatedThreadPool.cs#L75 and use that to schedule.

**Comment by HCanber** [comment] 2015-04-21 17:15
Or lets __not_ allow `MessageDispatcher` as an optional argument. :)

Let's introduce a new interface, `IActionRunner`, in lack of a better name.
``` C#
public interface IActionRunner
{
  void Run(Action action);
}
```
And have the abstract class `MessageDispatcher` implement that and let `IActionRunner` be the optional argument to scheduler.

**Comment by Aaronontheweb** [comment] 2015-04-21 17:43
@HCanber the `MessageDispatcher` isn't accessible as part of `IActorContext`, but it is available as part of the `ActorCell` - practically speaking what's the best way to allow an end-user to pass in the `MessageDispatcher` / `IActionRunner` from within their code?

Modify `IActorContext` or maybe add some syntactic sugar to the scheduler that does this under the hood? 

The other thing you can do is have the end-user pass in the dispatcher's name off of `Props` and then use `System.Dispatchers` to resolve it to an instance.

**Comment by HCanber** [comment] 2015-04-28 17:29
In Akka JVM they expose the dispatcher (or a bit smaller interface, `ExecutionContextExecutor`) on `ActorContext`
``` scala
  /**
   * Returns the dispatcher (MessageDispatcher) that is used for this Actor.
   * Importing this member will place an implicit ExecutionContext in scope.
   */
  implicit def dispatcher: ExecutionContextExecutor
```
https://github.com/akka/akka/blob/master/akka-actor/src/main/scala/akka/actor/ActorCell.scala#L124

So I guess we could expose something similar on `IActorContext`. 

Do we have something similar in .Net to [ExecutionContextExecutor](http://www.scala-lang.org/api/2.11.5/index.html#scala.concurrent.ExecutionContextExecutor)? It has three methods:
-  `prepare()` The role of prepare is to save any context relevant to an execution's _call site_, so that this context may be restored at the _execution site_.
- `run(runnable)` Executes a runnable
- `reportFailure(throwable)` Reports that an asynchronous computation failed.

**Closed** 2015-05-16 07:11 UTC
Labels: discussion
