### ISSUE TITLE
Akka.Fsharp spawning an actor results in Exception in 1.3.6 release

### ISSUE THREAD

**Issue by ivog** [akkadotnet/akka.net#3402] opened 2018-04-19 09:56 UTC
The exception is:

System.Exception: Doesn't match
   at Akka.FSharp.Linq.toExpression[Actor](Expression f)
   at Akka.FSharp.Spawn.spawnOpt[Message,Returned](IActorRefFactory actorFactory, String name, FSharpFunc`2 f, FSharpList`1 options)

I think the problem could be related to the Akka.Fsharp project referencing the 1.1.0 version of FSharp.Quotations.Evaluator which is a broken package. The 1.1.2 version of that package is correct.

**Comment by ivog** [comment] 2018-05-10 12:45
This is fixed since #3405 was merged. Since nightly build Akka.FSharp 1.3.7-beta501 Akka.Fsharp seems to be working properly again!

@chrisjhoare thanks! I guess PR #3441  wasn't even needed to fix Akka.FSharp.  I'll close this issue.

**Comment by jtmueller** [comment] 2018-11-28 23:07
@Aaronontheweb Yes, the same stack trace. I'm now getting it in 1.3.10 in a different project that I just updated from Akka 1.2.3. `spawnObj` appears to be completely unusable unless I stick to Akka 1.2.3.

at Akka.FSharp.Linq.toExpression[Actor](Expression f) 
at Akka.FSharp.Spawn.spawnObjOpt[a](IActorRefFactory actorFactory, String name, FSharpExpr`1 f, FSharpList`1 options)

I can't share this project, but I guess I can try to make an isolated repro case if you still can't reproduce it. From where I'm sitting it's harder to avoid getting this error than it is to reproduce.

**Comment by jtmueller** [comment] 2018-11-29 00:42
It might be relevant that my project is targeting .NET 4.5.2. However, I tried retargeting it to 4.6.1 and reinstalling all the nuget packages, but it didn't make any difference.

**Comment by chrisjhoare** [comment] 2018-12-02 12:07
Just opened a pull request which I appears to fix this. I'm not super familiar with this area and don't use expressions for actors myself, but at the very least you might be able to make use of the forked code yourself.

**Comment by Aaronontheweb** [comment] 2018-12-14 18:04
Looks like @chrisjhoare's PR addresses this. Will be releasing that fix as part of 1.3.11, which we're going to be releasing shortly.

**Comment by Aaronontheweb** [comment] 2018-12-14 20:11
closed via #3667

**Closed by Aaronontheweb** 2018-12-14 20:11 UTC
Labels: akka-fsharp, confirmed bug
