### ISSUE TITLE
NewtonSoft 7.0 Error using latest Akka and Cluster

### ISSUE THREAD

**Issue by ghost** [akkadotnet/akka.net#1409] opened 2015-11-07 11:30 UTC
Trying to dissect the example WebCrawler into a more concise project to make it easier to understand for me however I'm running into an issue where when sending a message to a router (crawler instance) it gives me the following exception;

```
Akka.Remote.EndpointWriter: AssociationError [akka.tcp://scrappy@127.0.0.1:54854] -> akka.tcp://scrappy@127.0.0.1:54847: Error [Unable to cast object of type 'Newtonsoft.Json.Linq.JObject' to type 'Newtonsoft.Json.Linq.JValue'.] [   at Newtonsoft.Json.Serialization.JsonFormatterConverter.GetTokenValue[T](Object value)
   at Newtonsoft.Json.Serialization.JsonFormatterConverter.ToInt32(Object value)
   at System.Runtime.Serialization.SerializationInfo.GetInt32(String name)
   at System.Exception..ctor(SerializationInfo info, StreamingContext context)
   at System.IO.FileLoadException..ctor(SerializationInfo info, StreamingContext context)
   at Void .ctor(System.Runtime.Serialization.SerializationInfo, System.Runtime.Serialization.StreamingContext)(Object[] )
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateISerializable(JsonReader reader, JsonISerializableContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType, IDictionary`2& extensionData)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Akka.Serialization.NewtonSoftJsonSerializer.FromBinary(Byte[] bytes, Type type)
   at Akka.Remote.MessageSerializer.Deserialize(ActorSystem system, SerializedMessage messageProtocol)
   at Akka.Remote.DefaultMessageDispatcher.Dispatch(IInternalActorRef recipient, Address recipientAddress, SerializedMessage message, IActorRef senderOption)
   at Akka.Remote.EndpointReader.<DeliverAndAck>b__3(Message msg)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Akka.Remote.EndpointReader.DeliverAndAck()
   at Akka.Remote.EndpointReader.OnReceive(Object message)
   at Akka.Actor.UntypedActor.Receive(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)]
```

Akka 1.0.4, NewtonSoft Json 7.0. Does not seem to happen when I run the WebCrawler example, I must be doing something wrong somewhere.

This is my CrawlMaster

``` C#
public class CrawlMaster : ReceiveActor, IWithUnboundedStash
    {
        public IStash Stash { get; set; }
        private const string CoordinatorRouterName = "coordinators";

        private IActorRef CoordinatorRouter;

        public CrawlMaster()
        {
            Ready();
        }

        public void Ready()
        {
            if (Context.Child(CoordinatorRouterName).Equals(ActorRefs.Nobody))
            {
                CoordinatorRouter =
                    Context.ActorOf(
                        Props.Create(() => new Crawler(Self))
                            .WithRouter(FromConfig.Instance), CoordinatorRouterName);
            }
            else //in the event of a restart
            {
                CoordinatorRouter = Context.Child(CoordinatorRouterName);
            }
            Context.SetReceiveTimeout(TimeSpan.FromSeconds(120));

            Become(ReceiveReady);
        }

        private void ReceiveReady()
        {
            Receive<Website>(str =>
            {
                var self = Self;
                CoordinatorRouter.Ask<Routees>(new GetRoutees()).ContinueWith(tr =>
                {
                    return new CrawlStart(str, tr.Result.Members.Count());
                }).PipeTo(self);
            });

            Receive<CrawlStart>(crawl =>
            {
                CoordinatorRouter.Tell(new StartCrawlMessage() { Website = crawl.Website.URL });
            });
        }
    }

    public class CrawlStart
    {
        public Website Website { get; set; }
        public int Count { get; set; }

        public CrawlStart(Website web, int c)
        {
            Website = web;
            Count = c;
        }
    }
```

Happens whenever it gets to `CoordinatorRouter.Tell`.

**Comment by Horusiath** [comment] 2015-11-07 17:29
This is problem with Json.NET not being able to serialize/deserialize your message. My guess is that something is wrong with `StartCrawlMessage` or `Website` types. What are their schemas?

**Comment by Levia-** [comment] 2015-11-07 17:31
Thank you for your response.
```
public class StartCrawlMessage
    {
        public string Website { get; set; }
    }
```

Not actually using the Website class here (atleast, not for sending across)

**Comment by vedeja** [comment] 2015-11-21 17:34
I've had this problem too. In my case I was remote deploying from one cluster node to another, with the actors defined in a shared assembly, but had forgotten to add reference to the shared in the deploy target project.

**Comment by easuter** [comment] 2015-12-05 03:05
@Levia- have you had any luck regarding your problem?

I just experienced the exact same thing, similar to @vedeja since it happened whenever a cluster-aware pool router tried to deploy actors remotely.

Here's what was happening:

- local instances of the actor deployed just fine
- creation of remote instances always failed with that same exception (`Unable to cast object of type 'Newtonsoft.Json.Linq.JObject' to type 'Newtonsoft.Json.Linq.JValue'.`)
- the remote instance's constructor never ran, so it wasn't an exception thrown inside the constructor
- a previous version of the same actor (a placeholder) used to deploy just fine, and it had a default constructor

Aparently one of the constructor arguments was causing the problem, string and a TimeSpan. If I removed the TimeSpan argument, deployment work just fine. For now I'm creating the actor props only with strings and then using `TimeSpan.Parse()` to get the value.

I'll try to reproduce this with a proper test case when I get the time, just writing this down in case anyone else has the same problem, hope it will save you some gray hairs!

**Comment by akoshelev** [comment] 2016-01-08 00:01
Hi guys,

I think I know where these exceptions are come from. Akka.NET uses custom JsonConverter and serializes some primitive types such as int/float/decimal itself (see full code [here](https://github.com/akkadotnet/akka.net/blob/95827ae6e6505cc1545d9c1d334c57c53a53b2d9/src/core/Akka/Serialization/NewtonSoftJsonSerializer.cs#L213))
```csharp
            /// <summary>
            ///     Writes the JSON representation of the object.
            /// </summary>
            /// <param name="writer">The <see cref="T:Newtonsoft.Json.JsonWriter" /> to write to.</param>
            /// <param name="value">The value.</param>
            /// <param name="serializer">The calling serializer.</param>
            public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
            {
                if (value is int || value is decimal || value is float)
                {
                    writer.WriteStartObject();
                    writer.WritePropertyName("$");
                    writer.WriteValue(GetString(value));
                    writer.WriteEndObject();
                }

```
So any int/decimal/float value will be converted to an json object during serialization. This is true for any object, no matter if it implements ```ISerializable``` or not. But when ```JsonConverter``` sees any ```ISerializable``` object during **deserialization** it ignores custom json converters at all and tries to deserialize it by itself. **Akka.NET converter is not used during ```ISerializable``` object deserialization**. As any int/decimal/float value is deserialized as an object, when ```ISerializable``` object tries to read them by calling ```SerializationInfo.Get(Int32/Float/Decimal)``` method, this exception is thrown.

Just a simple example to demonstrate this issue. When using Akka.Remoting/Cluster, deserialization of this message will cause an exception to be thrown.
```csharp
 public sealed class StoreFailed
        {
            public StoreFailed(string key, Exception error)
            {
                Error = error;
                Key = key;
            }

            public Exception Error { get; }

            public string Key { get; }
        }
```
As ```Exception``` type implements ```ISerializable```, during serialization all of its ```int``` properties such as ```RemoteStackIndex```, ```HResult``` will be serialized by Akka.NET converter, but during deserialization, this converter is ignored and, when constructor tries to read any of them as ```Int32```, an exception is thrown.

I've submitted an issue to Json.NET (https://github.com/JamesNK/Newtonsoft.Json/issues/780) maybe author will have a chance to look into it.

**Comment by AndreSteenbergen** [comment] 2018-06-05 20:56
I am having the exact same issue in latest Akka. Something is going wrong in the CrawlerService. I've updated all messages to MsgPack, except all unknown objects. I don't know the reason yet, but I see this message being serialized:  Akka.Actor.Status+Failure. There is an exception in that object, I guess that's the Exception not being able to get Serialized.

**Comment by Danthar** [comment] 2020-11-25 19:44
Closing the issue. Over the last few years alot has changed. Newtonsoft has changed how it serializes/deserialized exceptions. And we have also made changes in Akka.net regarding serialization. 

Should anyone come across this issue, with a similar problem. please create a new issue with as much details as possible.

**Closed by Danthar** 2020-11-25 19:44 UTC
Labels: akka-remote, potential bug, serialization
