### ISSUE TITLE
Sporadic SocketException in DotNetty NewServer ctor during the restart of a cluster node

### ISSUE THREAD

**Issue by object** [akkadotnet/akka.net#5186] opened 2021-08-09 09:48 UTC
This error occurs using all recent Akka.NET versions (last checked was 1.4.22).

Often after deploy of our system (an Akka.NET cluster running on Windows VMs) or restart of its nodes, some nodes fail to start due to socket exceptions. 

> An example of exception message: Failed to bind to [160.67.133.158:1966]. See InnerException for details., Only one usage of each socket address (protocol/network address/port) is normally permitted.
> 
> at  Akka.Remote.Transport.DotNetty.DotNettyTransport.NewServer(EndPoint listenAddress)
>    at Akka.Remote.Transport.DotNetty.DotNettyTransport.Listen()
>    at Akka.Remote.Transport.DotNetty.DotNettyTransport.Listen(),
>    at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
>    at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
>    at System.Net.Sockets.Socket.Bind(EndPoint localEP)
>    at DotNetty.Transport.Channels.Sockets.TcpServerSocketChannel.DoBind(EndPoint localAddress)
> 

Here's the remote configuration of the node that fails:

```
akka.remote.dot-netty.tcp {
  port = 1966
  hostname = "" # defaults to machine hostname (FQDN if available)
  # dns-use-ipv6 = true # uncomment when running on dev machine
}

```

Usually a second attempt to restart the failing node succeeds. Sometime a third attempt is needed. After successful restart the node is functioning normally.

We have been experiencing this kind of failures for last few months, I can't recall exact time when this began to happen.

**Comment by Aaronontheweb** [comment] 2021-08-09 15:04
@object let me check our default DotNetty settings - if the restart is pretty fast the `SO_LINGER` option might be responsible for this...

**Comment by Aaronontheweb** [comment] 2021-08-09 15:29
Near as I can tell, neither Akka.Remote nor DotNetty have `SO_LINGER` enabled by default nor do we explicitly set it anywhere:

https://github.com/akkadotnet/akka.net/blob/0673dc3e2bb08b7a9b39f9aefc065d2b657d9a73/src/core/Akka.Remote/Transport/DotNetty/DotNettyTransport.cs#L388-L399

https://github.com/Azure/DotNetty/blob/47f5ec7303037f1360615d182939e04d8619a2b3/src/DotNetty.Transport/Channels/Sockets/DefaultSocketChannelConfiguration.cs#L193-L233

According to Microsoft's documentation, sockets have this value disabled by default - which is what we should be doing given the code above:

https://docs.microsoft.com/en-us/dotnet/api/system.net.sockets.lingeroption.enabled?view=net-5.0#System_Net_Sockets_LingerOption_Enabled

So I don't think that's an issue. 

But the error message is pretty clear - the OS still believes that the old address in in-use and it's taking some time to release it after the process is terminated. It could be because of how the process is hosted - i.e. running under IIS or hosted under some other service or it could be an OS setting. Without looking at your setup, I'm not entirely sure what could cause the issue.

One workaround you could try, and we've recommended this in the past for users who had issues with things like IIS overlapped AppPool recycle, is to enable `SO_REUSEADDR` which is off by default on Windows only:

```
akka.remote.dot-netty.tcp.tcp-reuse-addr = on
```

That will allow the new socket to bind to the old address even if the old one hasn't been fully released by the OS yet.

**Comment by object** [comment] 2021-08-09 19:28
Thank you Aaron for checking out. We host our processes in .NET 5 Windows service hosting so there is no IIS in the picture, and the service is stopped before it's restarted.

I will try using the flag you mentioned (tcp-reuse-addr) but it won't probably have an effect on Windows service.

**Comment by Aaronontheweb** [comment] 2021-08-10 00:25
Thanks - I'll close this issue for now. Let us know if it reappears or if you get any additional information.

**Closed by Aaronontheweb** 2021-08-10 00:25 UTC
Labels: akka-remote, dotnetty

**Comment by object** [comment] 2021-08-10 07:05
@Aaronontheweb A couple of other observations.

1. I can't say for sure but we started getting socket errors on restart around the time we integrated our system with Phobos. Might be unrelated.
2. I added tcp-reuse-addr = on to see if it changes anything. Services still sometimes fail to restart, but the error is now different:
"An attempt was made to access a socket in a way forbidden by its access permissions."

**Comment by Aaronontheweb** [comment] 2021-08-10 14:01
Phobos doesn't really impact the way Akka.Remote or any of the networking functions behaves - it mostly just decorates the internals of actor base classes and introduces a new serializer for preserving trace context over the network.

> I added tcp-reuse-addr = on to see if it changes anything. Services still sometimes fail to restart, but the error is now different:
"An attempt was made to access a socket in a way forbidden by its access permissions."

Aha - this makes me think that the issue is an outstanding port reservation that your process can't access until its trust / privilege  level is elevated. How are you scripting your deployments of this service at the moment?

**Comment by Aaronontheweb** [comment] 2021-08-12 17:02
> But the failure happens not only during deploy: it also often happens if I stop a service and restart it immediately. So I don't think it has something to do with deployment process.

That's odd - I wonder if could have something to do with port reservations and Windows Services. 

Common port reservations on Windows: https://docs.microsoft.com/en-us/troubleshoot/windows-server/networking/service-overview-and-network-port-requirements#system-services-ports

Out of curiosity, which port number(s) are you using for your services?

**Comment by object** [comment] 2021-08-12 19:12
I am not aware of that and since this error may occur not only during deployment but also if I stop and start a service, I don't think it's Octopus Deploy related.

**Comment by Aaronontheweb** [comment] 2021-08-12 19:39
Ah, what I meant by that is - port reservations have to be done by changing Windows registry settings, so they're persistent even after the "deployment" is done. If Octopus deals with matters like opening ports in the firewall, it's conceivable that they might also reserve the port being used by the application.

**Comment by object** [comment] 2021-08-12 20:00
Ah I see. Will give it a try.
