### ISSUE TITLE
Possibly scheduler bug when doing long timespans?

### ISSUE THREAD

**Issue by ShamsulAmry** [akkadotnet/akka.net#2332] opened 2016-09-30 21:13 UTC
I'm trying to have Akka do daily batch processing. New batch starts at midnight and complete before 6 AM. I'm using the `ScheduleTellOnce` method to send a message to `Self` to start processing next day's batch.

The issue I'm facing: the actor is receiving the message I scheduled earlier than the expected time. I calculated the `TimeSpan` so that the actor should receive it earliest by 12:00 AM new day, but what I'm seeing is the actor is receiving it at 11:59:50 PM before new day (10 seconds earlier).

To confirm the issue, I've created a bare program just to test on this issue, and still getting it. The program's log showing the premature scheduler triggering (the log UTC time, thread ID and actor address removed for clarity):

> now = 9/30/2016 7:10:38 AM +08:00
> nextDay = 10/1/2016 12:00:00 AM
> nextDay - now = 16:49:21.4882134
> NextDay triggered
> now = 9/30/2016 11:59:50 PM +08:00
> nextDay = 10/1/2016 12:00:00 AM
> nextDay - now = 00:00:09.9319622
> NextDay triggered
> now = 10/1/2016 12:00:00 AM +08:00
> nextDay = 10/2/2016 12:00:00 AM
> nextDay - now = 23:59:59.9771333

What the log is showing is next day should be triggered at 12:00 AM, but it actually triggered 10 seconds earlier. So the batch started at the wrong time and a new next day scheduled to start in 10 seconds, finally started at the right time.

Minimal code I used to test that:
```
using System;
using Akka.Actor;
using Akka.Event;

namespace ReproAkkaSchedulerBug
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var system = ActorSystem.Create("ReproAkkaSchedulerBug")) {
                system.ActorOf<TestActor>();
                Console.WriteLine("Press any key to quit...");
                Console.ReadKey();
            }
        }
    }

    class TestActor : ReceiveActor
    {
        public TestActor()
        {
            Receive<NextDay>(msg => {
                Context.GetLogger().Info("NextDay triggered");
                ScheduleNextDay();
            });

            ScheduleNextDay();
        }

        void ScheduleNextDay()
        {
            var log = Context.GetLogger();
            var now = Context.System.Scheduler.Now;
            var nextDay = now.Date.AddDays(1);
            var countdown = nextDay - now;
            log.Info("now = {0}", now);
            log.Info("nextDay = {0}", nextDay);
            log.Info("nextDay - now = {0}", countdown);
            Context.System.Scheduler.ScheduleTellOnce(countdown, Self, new NextDay(), Self);
        }
    }

    class NextDay
    {}
}
```
with the following NuGet packages:
```
<packages>
  <package id="Akka" version="1.1.2" targetFramework="net452" />
  <package id="Newtonsoft.Json" version="9.0.1" targetFramework="net452" />
  <package id="System.Collections.Immutable" version="1.1.36" targetFramework="net452" />
</packages>
```

**Comment by Danthar** [comment] 2016-10-01 14:08
The build in scheduler is not meant for long running, accurate message scheduling. I can get into the details of why not. But the short of it is. Use the https://github.com/akkadotnet/Akka.Quartz.Actor plugin to handle stuff like that. 

Added advantage is, that with this plugin you scheduled messages can survive actor restarts as well.

**Comment by ShamsulAmry** [comment] 2016-10-01 20:02
Thanks @Danthar , I'll try that.

Any guide on the `TimeSpan` limit before it's considered long running? My assumption of a scheduled message would be for it to be sent to the mailbox at least after the `TimeSpan` interval has passed, not earlier. An idea on the use case the message scheduling mechanism was meant for will also help for future use.

For the project that I used the scheduler for, I simply added one minute to the TimeSpan which is workable for it's requirement (to start processing new batch when entering new day but need not necessarily start at exact midnight 0 second).

**Comment by Aaronontheweb** [comment] 2016-10-09 05:35
@ShamsulAmry going to close this out since it's not a bug, just the way the scheduler is designed. Our current scheduler is implemented using a hashed wheel timer, which allows it to be very fast and efficient, but at the cost of some precision. Most scheduled intervals are so small (20-3000ms) that the imprecision makes little visible difference.

However, due to the law of large numbers a much larger timespan like 12 hours (43,200,000ms) will cause this imprecision to show up using a real value, like the 10s interval you saw in your case.

Padding the time is one thing that could work, or you could use something like @Danthar's suggestion and try Akka.Quartz.

**Closed by Aaronontheweb** 2016-10-09 05:35 UTC
Labels: akka-actor

**Comment by ShamsulAmry** [comment] 2016-10-10 02:57
Noted, thanks!
