### ISSUE TITLE
Remoting does not work on Mono

### ISSUE THREAD

**Issue by loosechainsaw** [akkadotnet/akka.net#636] opened 2015-02-17 03:44 UTC
When starting up an actor system that uses remoting on mono it hangs.

Simple code sample.

using System;
using System.Threading;
using Akka;
using Akka.Actor;

namespace AkkaRemoting
{

    public class RequestMessage
    {

    }

    public class BackendActor : ReceiveActor
    {

        public static Random random = new Random(41);

        public BackendActor()
        {
            Receive<RequestMessage>(x =>
            {
                var sender = Sender;
               Console.WriteLine("The value is: " + random.Next());
            });

        }
    }

    public class FrontendActor : ReceiveActor
    {
        public FrontendActor()
        {

            Receive<RequestMessage>(x =>
            {
                var sender = Sender;

                var selection = Context.System.ActorSelection("akka.tcp://System1@localhost:8888/user/backend");
                selection.Tell(new RequestMessage());
            });
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var system1configuration = FluentConfig.Begin().StartRemotingOn("localhost", 8888);
            var system2configuration = FluentConfig.Begin().StartRemotingOn("localhost", 8889);

            var system1 = ActorSystem.Create("System1", system1configuration.Build());
            var system2 = ActorSystem.Create("System2", system2configuration.Build());

            var backend = system1.ActorOf(Props.Create<BackendActor>(),"backend");
            var frontend = system2.ActorOf(Props.Create<FrontendActor>(),"frontend");

            Thread.Sleep(1000);

            var result = frontend.Ask<string>(new RequestMessage());
            result.ContinueWith(x => Console.WriteLine(x.Result));

            Console.WriteLine("Press any key to exit....");
            Console.ReadKey();
            system1.Shutdown();
            system2.Shutdown();
        }
    }
}

**Comment by rogeralsing** [comment] 2015-02-18 05:56
I'll dig into this.

**Comment by rogeralsing** [comment] 2015-02-27 17:52
The endpoint manager seems to fail somehow, the last message that is logged is "Starting prune timer for endpoint manager"

**Comment by stefansedich** [comment] 2015-03-02 06:18
Any news on this one? I was just today deploying to our mono test server and noticed this :(

**Comment by stefansedich** [comment] 2015-03-03 03:43
Interesting I tried this out running mono 3.12 on windows and it works fine, so I upgraded my Ubuntu box to 3.12 just then but it still does not work there, just hands in the same place.


Cheers

**Comment by stefansedich** [comment] 2015-03-03 05:27
Ok found the cause, it looks related to https://github.com/akkadotnet/akka.net/issues/687

In TransportAdapters.cs line 297 if I change the RegisterManager method to:

private Task<ActorRef> RegisterManager()
        {
            return System.ActorSelection("akka://system/transports").Ask<ActorRef>(new RegisterTransportActor(ManagerProps, ManagerName));
        }


I get further although it does uncover some new issues now but that is one step forward. What is the plan for #687? I wonder if that will fix this completely.

**Comment by bruinbrown** [comment] 2015-03-03 20:13
@stefansedich I should have been more specific with the bug, I missed out the system name, so if you were to change the address to akka://<system-name>/system/transports then it should work, that's why it throws the exception you're seeing

**Comment by stefansedich** [comment] 2015-03-03 21:24
@bruinbrown that still did not seem to work, it might have something to do with using RemoteActorRefProvider in this case?

**Comment by bruinbrown** [comment] 2015-03-03 21:28
@stefansedich it looks like markdown stripped out part of what I wrote, what I meant was akka://system-name/system/transports

**Comment by stefansedich** [comment] 2015-03-03 21:32
@bruinbrown aaaah right I get you now, too early you did say "system name" in there after all :) so the following does work now:

    return System.ActorSelection("akka://" + System.Name + "/system/transports")
        .Ask<ActorRef>(new RegisterTransportActor(ManagerProps, ManagerName));

Although I assume there is going to be a better fix, I am going to patch Remote for now so I can deploy my app and await some more discussion on this.



Thanks
Stefan

**Comment by stefansedich** [comment] 2015-03-03 22:23
Looks like I spoke too soon, even though it start up I am getting something new :(

    Akka.Remote.EndpointAssociationException: Association failed with akka.tcp://import@localhost:9998

**Comment by stefansedich** [comment] 2015-03-04 01:09
Ok after talking with @Aaronontheweb  looks like the issue is inside Helios and related to the way mono handles TcpClient construction and the setting of the ExclusiveAddressUse property, the following code:

    var client = new TcpClient
    {
        ReceiveTimeout = 5000,
        SendTimeout = 5000,
        Client = { NoDelay = true },
        ReceiveBufferSize = 5000
     };

     client.Client.ExclusiveAddressUse = true;


That works fine under normal .NET but running under mono I can see the the default TcpClient constructor in mono actually does a Bind() so I cannot set this property at all as the socket has already been bound, maybe @migueldeicaza can shed some light into why mono does this differently?


Thanks
Stefan

**Comment by stefansedich** [comment] 2015-03-04 21:42
So after some investigation the root causes have been nailed down and should be solved, from what I could see we had two issues:

1. The first issue was that the actor selection was failing (#687), this issue has been fixed and PR merged into dev.

2. Once the first issue was fixed I uncovered an issue when running under mono where it was trying to configure the reuseAddress setting of the socket after it had already been bound. Turns out from my investigation that the mono TcpClient (https://github.com/mono/mono/blob/master/mcs/class/System/System.Net.Sockets/TcpClient.cs) for some reason will bind in it's default constructor which would then cause the failure as we were setting reuseAddress after it had already been bound.

I have changed this in Helios so that the TcpConnection uses a Socket directly and sent a PR across for this.




Thanks
Stefan

**Comment by rogeralsing** [comment] 2015-03-05 05:29
Yaaay :) :+1:  IoT here we come!

**Comment by rikace** [comment] 2015-03-22 17:46
It seems that the error is at protocol level. Have you a temporary solutions or the "bug" is still in progress? I can keep the investigation otherwise

**Comment by stefansedich** [comment] 2015-03-23 00:59
@rikace this has been fixed now, there were 2 fixes required, one being inside Helios itself and another in Akka.NET, both fixes have been merged into the develop branches of the respective projects.


Thanks
Stefan

**Comment by rikace** [comment] 2015-03-23 01:04
You guys rock!!!

Thanks

**Comment by stefansedich** [comment] 2015-03-23 01:07
@rikace I should mention by "works" I had my use case of remoting working in production, hopefully soon I can get the unit tests up and running in a mono environment to validate that everything working 100% /cc @Aaronontheweb

**Comment by rikace** [comment] 2015-03-23 01:12
I will test it tomorrow on mono and let you know

**Closed** 2015-04-03 17:57 UTC
Labels: bug, in progress, mono
