### ISSUE TITLE
Using `ActorOf` in TestKit prevents `Console.Out` from emitting from actors

### ISSUE THREAD

**Issue by BertLamb** [akkadotnet/akka.net#2722] opened 2017-06-03 02:01 UTC
Project exemplifying the issue is available here: https://github.com/BertLamb/TestKitSystemOutBug

If an actor attempts to write to `Console.Out` when created in TestKit using `ActorOf` then the messages from the actor will not be written to the console (Lines written in the TestFixture are emitted).

Strangely, if the actor is created using `ActorOfAsTestActorRef` then the `Console.Out` messages from the actor work just fine.

```c#
[TestFixture]
    public class NUnitTest : TestKit
    {
        private static Props ActorProps => Props.Create(() => new SystemOutActor());

        [Test]
        public void WriteToConsoleWithActorOf()
        {
            Console.Out.WriteLine("This will show up");
            var actor = ActorOf(ActorProps);
            Console.Out.WriteLine("So will this");
            actor.Tell("Console writes from the actor however will not be output");
            actor.Tell("This one won't either");
            Console.Out.WriteLine("But this line will show up");
        }

        [Test]
        public void WriteToConsoleWithActorOfAsTestActorRef()
        {
            var actor = ActorOfAsTestActorRef<SystemOutActor>(ActorProps);

            actor.Tell("Hello World!");
            actor.Tell("These WILL be output to Standard Out like it should be");
        }
    }

    public class SystemOutActor : ReceiveActor
    {
        public SystemOutActor()
        {
            Receive<string>(str => Console.Out.WriteLine(str));
        }
    }
```

**Comment by rustamm** [comment] 2019-05-18 00:14
Looks like I'm hitting the same issue. Were you able to find out why this happens since June 2017?

**Comment by Aaronontheweb** [comment] 2019-05-18 21:52
Akka.NET itself doesn't do much to manipulate the `Console` on the background threads during testing - it sounds to me like the issue is that actors running on a background thread aren't getting their Console IO picked up by NUnit. The `TestActorRef` actors might be running on the foreground thread - I'd need to check.

**Comment by rustamm** [comment] 2019-05-20 19:08
@Aaronontheweb good call, looks like the root cause is that background threads writing to console output doesn't work with NUnit. The solution I found is to do this somewhere in the test code: `Console.SetOut(TestContext.Out);`

**Comment by Aaronontheweb** [comment] 2019-05-20 19:15
@rustamm glad I could help! I'll close this issue out then since it seems to be an issue with NUnit rather than Akka.NET specifically.

**Closed by Aaronontheweb** 2019-05-20 19:15 UTC
