### ISSUE TITLE
Streams: buffering seems not working

### ISSUE THREAD

**Issue by vasily-kirichenko** [akkadotnet/akka.net#1922] opened 2016-04-30 12:06 UTC
```fsharp
/// Helper functions to make piping possible
module Source =
    let inline ofSeq x = Source.From x
    let inline buffer size strategy (src: Source<_,_>) = src.Buffer(size, strategy)
    let inline map (mapper: 'a -> 'b) (src: Source<_,_>) = src.Map(fun x -> mapper x)

    let inline mapAsync parallelism (mapper: 'a -> Async<'b>) (src: Source<_,_>) = 
        src.MapAsync(parallelism, fun x -> Async.StartAsTask (mapper x))
    
    let inline runForeach materializer (action: 'a -> unit) (src: Source<_,_>) =
        src.RunForeach(System.Action<_> action, materializer) |> Async.AwaitTask

let system = System.create "test" (Configuration.defaultConfig())
let materializer = ActorMaterializer.Create system

// Download home page of a number of sites asynchronously, in max 10 threads, 
// buffer max 3 results and "slowly" output their length (5 seconds each)
["google.com"; "ya.ru"; "microsoft.com"; "jet.com"; "ycombinator.com"]
|> Source.ofSeq
|> Source.map (fun x -> Uri ("http://" + x))
|> Source.mapAsync 10 (fun url -> 
    async {
        use client = new WebClient()
        let! content = client.AsyncDownloadString url
        return url, content
    })
|> Source.map (fun x -> printfn "%O %O downloaded" DateTime.Now (fst x); x)
|> Source.buffer 3 OverflowStrategy.Backpressure
|> Source.runForeach materializer (fun (url, content) ->
    printfn "%O %O => %d bytes" DateTime.Now url content.Length
    Thread.Sleep 5000)
|> Async.RunSynchronously
```
Output:
```
30.04.2016 14:57:12 http://google.com/ downloaded
30.04.2016 14:57:12 http://google.com/ => 49308 bytes
30.04.2016 14:57:17 http://ya.ru/ downloaded
30.04.2016 14:57:17 http://ya.ru/ => 9480 bytes
30.04.2016 14:57:22 http://microsoft.com/ downloaded
30.04.2016 14:57:22 http://microsoft.com/ => 1020 bytes
30.04.2016 14:57:27 http://jet.com/ downloaded
30.04.2016 14:57:27 http://jet.com/ => 57171 bytes
30.04.2016 14:57:32 http://ycombinator.com/ downloaded
30.04.2016 14:57:32 http://ycombinator.com/ => 4068 bytes
```
It's clear that buffering does not work: after one page is downloaded the second one is not started to download until the sink (`runForeach`) consumes the first one. 
Is it a bug or buffering not implemented yet?

**Comment by Horusiath** [comment] 2016-05-03 06:52
Few things happens here. 

1. `Source.buffer` limits only upper bound of the possible throughput. 
2. Consumer demand works in the epidemic fashion, so it's propagated through up of the stream. In that case throughput capabilities of the foreach sink are propagated up to the async boundary (which is up to the `Source.map (fun x -> printfn "%O %O downloaded" DateTime.Now (fst x); x)` in this case).
3. Within the same section (limited by async boundary) the speed of the stream is equalized to the speed of the slowest consumer - since they are running in synchronous fashion. Reason behind that is fusing - this is an optimization, materializer fuses series of steps, that can be executed synchronously, together on the same actor (instead of creating a separate actor for each step).

Summarizing, in your code you have two sections, split by async boundary:

```fsharp
// section 1 starts here
["google.com"; "ya.ru"; "microsoft.com"; "jet.com"; "ycombinator.com"]
|> Source.ofSeq
|> Source.map (fun x -> Uri ("http://" + x))
|> Source.mapAsync 10 (fun url -> async { ... })
// section 2 starts here
|> Source.map (fun x -> printfn "%O %O downloaded" DateTime.Now (fst x); x)
|> Source.buffer 3 OverflowStrategy.Backpressure
|> Source.runForeach materializer (fun (url, content) -> { ... })
```

Everything seems to works correctly, the only problem in your measure is that your download date is actually taken inside second section, while download itself has occurred in the first one. If you want to check, when page has been really downloaded, extend tuple returned from `Source.mapAsync` to include current date like `return DateTime.Now, url, content` and use that date instead. 

My results are:

> **2016-05-03 08:45:52 http://google.com/ downloaded**
2016-05-03 08:45:52 http://google.com/ => 49409 bytes
**2016-05-03 08:45:52 http://ya.ru/ downloaded**
2016-05-03 08:45:57 http://ya.ru/ => 9479 bytes
**2016-05-03 08:45:52 http://microsoft.com/ downloaded**
2016-05-03 08:46:02 http://microsoft.com/ => 1020 bytes
**2016-05-03 08:45:53 http://jet.com/ downloaded**
2016-05-03 08:46:07 http://jet.com/ => 57299 bytes
**2016-05-03 08:45:52 http://ycombinator.com/ downloaded**
2016-05-03 08:46:12 http://ycombinator.com/ => 4068 bytes

Also if you want to change default stage buffer, use `.WithAttributes(Attributes.CreateInputBuffer(initial, max))`.

**Comment by vasily-kirichenko** [comment] 2016-05-03 08:11
Thanks for explanation, it works OK. However, I'm afraid I still don't understand how the buffering works, look at the following, slightly modified code:
```fsharp
let print fmt = kprintf (printfn "%O %s" DateTime.Now) fmt

["google.com"; "ya.ru"; "microsoft.com"; "jet.com"; "ycombinator.com"]
|> Source.ofSeq
|> Source.map (fun x -> Uri ("http://" + x))
|> Source.mapAsyncUnordered 2 (fun url ->  // 2 parallel downloadings at most
     async {
         use client = new WebClient()
         print "??? %O" url
         let! content = client.AsyncDownloadString url
         print "!!! %O" url
         return url, content
     })
|> Source.buffer 10 OverflowStrategy.Backpressure  // buffering at most 10 results
|> Source.runForeach materializer (fun (url, content) ->
    print "Sink: %O => %d bytes" url content.Length
    Thread.Sleep 5000)
|> Async.RunSynchronously
```
Output:
```
03.05.2016 11:00:56 ??? http://google.com/
03.05.2016 11:00:56 ??? http://ya.ru/
03.05.2016 11:00:56 !!! http://ya.ru/
03.05.2016 11:00:56 Sink: http://ya.ru/ => 9476 bytes
03.05.2016 11:00:56 !!! http://google.com/
03.05.2016 11:01:01 ??? http://microsoft.com/
03.05.2016 11:01:01 Sink: http://google.com/ => 49321 bytes
03.05.2016 11:01:02 !!! http://microsoft.com/
03.05.2016 11:01:06 ??? http://jet.com/
03.05.2016 11:01:06 Sink: http://microsoft.com/ => 1020 bytes
03.05.2016 11:01:07 !!! http://jet.com/
03.05.2016 11:01:11 ??? http://ycombinator.com/
03.05.2016 11:01:11 Sink: http://jet.com/ => 57299 bytes
03.05.2016 11:01:12 !!! http://ycombinator.com/
03.05.2016 11:01:16 Sink: http://ycombinator.com/ => 4068 bytes
```
It does download in exactly 2 threads, but it seems to be back pressed by the foreach, the 10 elements buffer does not seem to work. I expected the code to do: 

1. It downloads at most 2 links in parallel (already works)
2. It does it non-stop, until the buffer is filled (does not work)
3. Sink pulls the results from the buffer at one per 5 seconds rate (already works)

**Comment by Silv3rcircl3** [comment] 2016-05-18 07:27
The Problem is that you're blocking the thread to enforce back pressure, but since the buffer is fused together with runForeach you're also blocking the buffer, use Throttle instead of Thread.Sleep between buffer and runForeach, this gives you the following output:

```
??? http://google.com/
??? http://ya.ru/
!!! http://google.com/
??? http://microsoft.com/
!!! http://microsoft.com/
??? http://jet.com/
!!! http://ya.ru/
??? http://ycombinator.com/
!!! http://ycombinator.com/
!!! http://jet.com/
Sink: http://google.com/ => 49066 bytes
Sink: http://microsoft.com/ => 1020 bytes
Sink: http://ya.ru/ => 9464 bytes
Sink: http://ycombinator.com/ => 4068 bytes
Sink: http://jet.com/ => 57065 bytes
```

**Comment by vasily-kirichenko** [comment] 2016-05-18 07:41
Thanks. I find this behavior is not obvious at all. Looking at the flow, it's unclear that buffering actually does not work. 

What is the recommended way to buffer intermediate results, if a sink is slow? I thought `Buffer` is exactly the combinator which should be used.

**Comment by Silv3rcircl3** [comment] 2016-05-18 07:53
You can use the Async method on the Sink to avoid fusing, this way the Sink is running in it's own actor.

```csharp
var sink = Sink.ForEach<Tuple<Uri, string>>(tuple =>
{
	var url = tuple.Item1;
	var content = tuple.Item2;

	_print.WriteLine($"Sink: {url} => {content.Length} bytes");
	Thread.Sleep(5000);
}).Async();

...
.Buffer(10, OverflowStrategy.Backpressure)
.RunWith(sink, mat).Wait(TimeSpan.FromSeconds(30));
```

**Comment by Silv3rcircl3** [comment] 2016-05-20 09:04
@vasily-kirichenko can I close this one? 
If you want to read more about buffers you can take a look at the [documentation](http://doc.akka.io/docs/akka/2.4.4/scala/stream/stream-rate.html), it's the scala version because we haven't ported that part yet.

**Closed** 2016-05-20 09:12 UTC
Labels: akka-streams
