### ISSUE TITLE
Tutorial 1 code sample does not work - crashes with no exception.

### ISSUE THREAD

**Issue by PiotrJustyna** [akkadotnet/akka.net#4368] opened 2020-04-06 15:07 UTC
I'm having problems with the first code example in this section:

https://getakka.net/articles/intro/tutorial-1.html#structure-of-an-iactorref-and-paths-of-actors

The problem I'm facing is that the program quits with no exception while creating the second actor. I'm not sure if I'm instantiating the `system` correctly, as the code snippet provided is missing that bit.

Here is my output:

```
...
Loaded '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.0/System.Threading.ThreadPool.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.0/System.Linq.Expressions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'Anonymously Hosted DynamicMethods Assembly'. 
First: [akka://testSystem/user/first-actor#2008836512]
The program '[77318] AkkaSandbox.dll' has exited with code 0 (0x0).
```

What is failing is this line:

```csharp
IActorRef secondRef = Context.ActorOf(Props.Empty, "second-actor");
```

I tried surrounding it with a very general `try-catch`, but it's not catching anything.

Here is my code: https://github.com/PiotrJustyna/akkasandbox It is configured so that in can be ran in a remote container and I tested this with VS code and .net core both locally and in a remote container with the same results.

- I'm using Akka.Net version 1.4.4.
- macOS Catalina 10.15.4, .net core `3.1.0` and `3.1.200`

**Comment by Arkatufus** [comment] 2020-04-06 22:05
It is working as intended. The problem is that the actor is run on another thread, and most of the time, the main thread finishes before the actor thread can actually print anything onto the console.

Try adding a `Console.ReadKey()` at the end of your `Main()` function to stop the main thread from closing prematurely.

**Comment by PiotrJustyna** [comment] 2020-04-07 11:03
@Arkatufus Thanks for looking into it. The explanation makes sense. I went ahead and tried applying your suggestion just to be greeted with an exception:

```
Exception has occurred: CLR/System.InvalidOperationException
An unhandled exception of type 'System.InvalidOperationException' occurred in System.Console.dll: 'Cannot read keys when either application does not have a console or when console input has been redirected. Try Console.Read.'
   at System.ConsolePal.ReadKey(Boolean intercept)
   at System.Console.ReadKey()
   at AkkaSandbox.Program.Main(String[] args) in /workspaces/AkkaSandbox/AkkaSandbox/Program.cs:line 14
```

Code:

```csharp
static void Main(string[] args)
{
    var system = ActorSystem.Create("testSystem");
    var firstRef = system.ActorOf(Props.Create<PrintMyActorRefActor>(), "first-actor");
    Console.WriteLine($"First: {firstRef}");
    firstRef.Tell("printit", ActorRefs.NoSender);
    var result = Console.ReadKey();
    Console.WriteLine($"Result: {result}.");
}
```

Result:

![image](https://user-images.githubusercontent.com/6170837/78661957-809fc200-78c7-11ea-8599-6dbafde703a6.png)

Also, when I did what the exceptions suggested (`Console.Read()`), the program just hangs before printing the result to the output.

Code:

```csharp
static void Main(string[] args)
{
    var system = ActorSystem.Create("testSystem");
    var firstRef = system.ActorOf(Props.Create<PrintMyActorRefActor>(), "first-actor");
    Console.WriteLine($"First: {firstRef}");
    firstRef.Tell("printit", ActorRefs.NoSender);
    var result = Console.Read();
    Console.WriteLine($"Result: {result}.");
}
```

Result:

![image](https://user-images.githubusercontent.com/6170837/78661883-68c83e00-78c7-11ea-8755-17444d06bd00.png)

If I have some time later today, I will try putting this code in a generic host and see what happens.

**Comment by Arkatufus** [comment] 2020-04-07 14:31
Well, the `Console.ReadKey()` would work if you test it on a system with console access. Since you're working with container, its probably best to make your `Main()` an async function and do a `await Task.Delay(<delay time in miliseconds>);` to wait for the other thread to finish before exiting the main thread.

**Comment by PiotrJustyna** [comment] 2020-04-07 14:59
That is very interesting, thanks. I didn't realize vs code would not give console access. Live & learn I guess... When I run the code from plain terminal, it works well.

I don't want to artificially delay the execution and wait for the second actor to print, I'll try to come up with a good illustration for that section and will share it when I'm done. That would be very useful for newcomers trying to evaluate the code and to run some experiments.

**Closed** 2020-04-07 17:02 UTC
Labels: discussion, docs

**Comment by PiotrJustyna** [comment] 2020-04-07 19:14
@Arkatufus Just updated my code to use a generic host and I think it illustrates the documentation's section [Structure of an IActorRef and Paths of Actors](https://getakka.net/articles/intro/tutorial-1.html#structure-of-an-iactorref-and-paths-of-actors) well: https://github.com/PiotrJustyna/akkasandbox

Feel free to use it in the documentation, I'm sure it will help newcomers use your library.

**Comment by PiotrJustyna** [comment] 2020-04-07 22:47
https://github.com/akkadotnet/akka.net/pull/4371
