### ISSUE TITLE
DIActorContextAdapter uses typeof().Name instead of AssemblyQualifiedName

### ISSUE THREAD

**Issue by Danthar** [akkadotnet/akka.net#833] opened 2015-04-10 13:52 UTC
The Akka.DI.Core.DIActorContextAdapter passes typeof(TActor).Name to the Props object.
I do not think this is correct. As this would effectively bars a user from having more then 1 actor with the same type name, but in different namespaces, in the same ActorSystem.

First I figured it should be .FullName but then you cant reference Actors from different assemblies. So AssemblyQualifiedName it is.

**Comment by jcwrequests** [comment] 2015-04-10 15:40
@danthar thanks for the input and I will makes the adjustments. Do you have an example?

**Comment by jcwrequests** [comment] 2015-04-10 15:52
Nevermind about the example its just an impulse to asked for examples to recreate the issue. I am just a big believer in documentation. Cheers

**Comment by nvivo** [comment] 2015-04-10 16:21
Just an opinion, but I think this issue should be fixed [here](https://github.com/akkadotnet/akka.net/blob/dev/src/contrib/dependencyInjection/Akka.DI.Core/DIExt.cs#L31).

There shouldn't be a way to create an invalid props if you already have the Type object, so DIExt.Props could accept the Type directly and get the qualified name there.

I'd dare to go further and ask why pass strings at all if you already have the type? Couldn't the DIActorProducer hold the type object instead? It would be more performant than creating string qualified names, as those are not interned, so you will end up with a bunch of different references to the same value in memory.

**Comment by jcwrequests** [comment] 2015-04-10 16:34
@nvivo the strings are an Akka thing not something that I personally prefer. This part is from the JVM side. I was just working within the provided constraints. But I certainly agree with your opinion.

**Comment by nvivo** [comment] 2015-04-10 16:49
Yeah, this "must be equal to the JVM version" thing keeps biting me every day. =)

**Comment by Danthar** [comment] 2015-04-10 17:29
Just found the same issue in the AutofacDependencyResolver.

      public Props Create<TActor>() where TActor : ActorBase
        {
            return system.GetExtension<DIExt>().Props(typeof(TActor).Name);
        }

**Comment by rogeralsing** [comment] 2015-04-10 19:48
Some thoughts.
In the `DIActorProducer` the field containing the typename is `actorName` this is confusing as it is then used to getch concrete types via `actorName.GetType()`, so it's not the name, its the FQN of the actor.
Also, why do we store the actor type as a string internally? if we want to use a type, why dont we store it as a type?

**Comment by jcwrequests** [comment] 2015-04-10 22:14
@rogeralsing I believe that you are right. Thinking back that was something that I decided based on my initial understanding of the process which has changed considerably since then. Thanks for your suggestion it's really appreciated.

**Comment by jcwrequests** [comment] 2015-04-10 23:38
@rogeralsing I have a working model based on your suggestion which makes more sense. I will have to see if I can reproduce @nvivo @Danthar Issues after the changes. Thanks so much.

**Comment by nvivo** [comment] 2015-04-10 23:52
If the type or que qualified name is is used there can't be any problems.  My issue was exactly that the type couldn't be found just with the class name.

**Comment by jcwrequests** [comment] 2015-04-11 00:21
@nvivo Then I think my solution will solve that issue.

**Comment by nvivo** [comment] 2015-04-11 00:21
Btw, rogers's suggestion is *exactly* what I proposed a few hours before that you said couldn't be changed because that's how the jvm works.

**Comment by jcwrequests** [comment] 2015-04-11 01:46
@Danthar @nvivo  Please verify that PR#835 resolves this issue. Thanks.

**Comment by jcwrequests** [comment] 2015-04-11 16:55
@nvivo hey I was reading through the suggestions and realized that your suggestion was the same as @rogeralsing. When I was responding I was only on my phone and did not read it through clearly. Sorry for that.

**Comment by Aaronontheweb** [comment] 2015-04-11 22:56
Resovled per #835

**Closed** 2015-04-11 22:56 UTC
