### ISSUE TITLE
Remote + Cluster = what?

### ISSUE THREAD

**Issue by rogeralsing** [akkadotnet/akka.net#748] opened 2015-03-23 14:00 UTC
Are Akka.Remote and Akka.Cluster supposed to be able to be used together?

If I expose an actor in a cluster node, e.g. Petabridge Lighthouse.
And then try to reach that actor using normal remote from a non cluster node, it does work and I can pass messages to the actor on the cluster node.
But after the message have been processed, the cluster node throws a protocol exception.

Are non cluster systems supposed to be able to connect to individual cluster nodes?

* If yes, why does it disconnect and throw?
* If no, why can I connect and pass messages to actors on the cluster nodes?

**Comment by smalldave** [comment] 2015-03-23 14:17
Clustering is built on top of remote. 
Fundamentally clustering just gives you a way to detect and monitor other actor systems. 
Sounds like a bug. 
What is the protocol exception?

**Comment by rogeralsing** [comment] 2015-03-23 17:48
This:
```
Akka.Remote.Transport.ProtocolStateActor: Underlying transport closed.
Akka.Remote.Transport.ProtocolStateActor: Underlying transport closed.
Akka.Remote.EndpointWriter: AssociationError [akka.tcp://webcrawler@127.0.0.1:4053] <- akka.tcp://MyClient@localhost:65243: Error [Shut down address: akka.tcp://MyClient@localhost:65243] [   at Akka.Remote.EndpointReader.HandleDisassociated(DisassociateInfo info)
   at Akka.Remote.EndpointReader.OnReceive(Object message)
   at Akka.Actor.UntypedActor.Receive(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)]
Akka.Actor.OneForOneStrategy: Shut down address: akka.tcp://MyClient@localhost:65243
```

**Comment by rogeralsing** [comment] 2015-03-26 14:50
So I take it that it should be possible to remote into cluster nodes w/o affecting the cluster topology, right?

e.g. if we have a cluster for computation services and then let workstations use remote to communicate with that cluster.

**Comment by smalldave** [comment] 2015-03-26 15:08
Yes but the cluster is dynamic so how do you know who to talk to? You could arbitrarily nominate some nodes as entry points into you compute cluster. Guess the seed nodes would be a good choice for that. You'd still need to check the node you want to talk to is available.
I think the ClusterClient is designed to ease this a bit.

**Comment by rogeralsing** [comment] 2015-03-26 17:59
I'm thinking there could be fixed nodes in the topology.
e.g. a webserver with an actorsystem that fronts http requests. and then dynamic nodes for compute power that comes and goes.
That cant be a totally unrealistic senario (?)

**Comment by smalldave** [comment] 2015-03-26 18:08
Nope. But why not make webservers part of the cluster?

**Comment by Aaronontheweb** [comment] 2015-03-26 18:10
> Nope. But why not make webservers part of the cluster?

I agree with this. Just make the webservers part of the cluster.

The only nodes that shouldn't be part of a cluster are clients - i.e. desktop / mobile / embedded clients that aren't perpetually always on. Anything that fundamentally acts as a server of some sort should just be part of the cluster.

**Comment by Aaronontheweb** [comment] 2015-04-07 21:31
Marking this as a bug.

**Comment by skotzko** [comment] 2015-10-05 16:48
@Aaronontheweb please check up on this per our convo this AM

**Comment by HakanL** [comment] 2015-12-16 01:49
Maybe a little out of scope, but can a ClusterClient connect in to a cluster (via the seed nodes) and send/receive messages as if it was a full-blown node, or how does it differentiate from a regular node? I'm looking into how to handle a client who is very unreliable, but still want to send/receive (actually Tell/Ask) messages into the cluster, not caring who in the cluster responds.

**Comment by Aaronontheweb** [comment] 2016-03-24 01:35
Looking into #1700 and am porting the Cluster.Tests.MultiNode.RestartNodeSpec to tackle that bug, and ran into this. Definitely a bug by design. Looking into it now

**Comment by Aaronontheweb** [comment] 2016-03-24 01:59
Cluster nodes that are not joined in the cluster can communicate via Akka.Remote - confirmed that this works via multi-node test in #1821. 

As for a node that isn't running Akka.Cluster to communicate via Akka.Remote with the Cluster, I'll need a separate setup for that.

**Comment by Aaronontheweb** [comment] 2016-06-07 17:55
This is fixed - verified in our deathwatch specs and elsewhere for Akka.Cluster.

**Closed by Aaronontheweb** 2016-06-07 17:55 UTC
Labels: akka-cluster, akka-remote, confirmed bug, ready
