### ISSUE TITLE
How to close a TCP connection which is in connecting state?

### ISSUE THREAD

**Issue by MichaelMayrhofer** [akkadotnet/akka.net#4381] opened 2020-04-20 05:02 UTC
**Environment**
Akka Version 1.4.4
.NET Framework 4.6.1
Win10
Visual Studio 2019

**Steps to reproduce**
1. Check out a simple demo: https://github.com/MichaelMayrhofer/Akka.TcpDemo
The repo contains a projects:
1.1 TcpClient (implemented with akka.net):
1.1.1 Creates a client actor
1.1.2 Client actor tries to open a TCP connection with `Context.System.Tcp().Tell(new Tcp.Connect(...))`
1.1.3 Client actor will be stopped before there is any response to the Tcp.Connect message with `Context.Stop(Self)` 
2. Build & run the program TcpClient.
3. Press [enter] in the TcpClient.exe console window to open a TCP connection.
=> there will be an error output in the TcpClient.exe console window:

> [ERROR][20.04.2020 04:57:29][Thread 0008][akka://Akka-TcpDemo/system/IO-TCP/$a] Monitored actor [[akka://Akka-TcpDemo/user/client#1282531486]] terminated
> Cause: Akka.Actor.DeathPactException: Monitored actor [[akka://Akka-TcpDemo/user/client#1282531486]] terminated
>   at Akka.Actor.ActorBase.Unhandled(Object message)
>   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
>   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
>   at Akka.Actor.ActorCell.ReceivedTerminated(Terminated t)
>   at Akka.Actor.ActorCell.AutoReceiveMessage(Envelope envelope)
>   at Akka.Actor.ActorCell.Invoke(Envelope envelope)

**Question:**
How can I close/abort the TCP connect without getting this error message?

**Comment by Aaronontheweb** [comment] 2020-04-22 20:49
Yeah we really should clean that up - I hate those `DeathPactException`s. Any ideas on how we can do that @IgorFedchenko ?

**Comment by IgorFedchenko** [comment] 2020-04-23 15:21
Huh, that's an excellent question.

### Why is that?

In current architecture, when you are sending `Connect` message to `TcpManager`, it immediately starts `TcpConnection` for you, and this new `TcpConnection`  immediately starts watching your actor. For `TcpConnection`, if the guy who asked for connection stopped working without saying a word - something bad happend. That's why we have an error.

### How to avoid this?

The only way to ask `TcpConnection` to unwatch your actor is to send him a message. But you can not send when you do not have a reference to actor. That's what we have in the sample - we did not receive `Connected` message with `Sender` reference, so can not send `Close` message.

I think the "right" way here would be to set `Become(Closing)` on an actor, in that state receive `Connected` or `CommandFailed` and either send `Close` (if connected) or just stop if connection failed. At least, this is something you can do to avoid getting error message.

### Can we change/improve this somehow?

The problem is that we do not know that guy we asked to open connection until he will report result of this action to us. We send message to `TcpManager`, but the later sends command to `TcpConnection` and we now have to talk with new guy - and we do not know his address until he will start talking first.

What we could do here (in Akka.NET internals) is to add `ConnectionStarted` message from `TcpManager` in response to `Connect` message. He starts `TcpConnection`, and might share this reference with us.

This would still require to wait for `ConnectionStarted` message before closing an actor, but will not require us to wait until connection succeed or, even longer, until connection attempt will time out.
But, this will be a new pipeline - currently `TcpConnection` sends his reference (with `Connected`) once he is ready to receive commands. If we will be able to send him something like `Close` before connection actually exists, we will need to add special handling for that. Probably special `AbortConnecting` message... 

I am not sure we should do that. 

Another hacky way would be to send some `IgnoreCommanderFailure` flag, to let `TcpConnection` know we do not care if our actor crashes for some reason without closing connection first. But this is giving a gun to shoot into leg.

**Comment by IgorFedchenko** [comment] 2020-05-04 11:01
Probably we can close this issue for now, since I have explained the way one could avoid `DeathPactException`. Feel free to reopen/ask additional questions.

**Closed by IgorFedchenko** 2020-05-04 11:01 UTC
