### ISSUE TITLE
TcpEchoService.Server stops receiving communication if logging is used.

### ISSUE THREAD

**Issue by spankr** [akkadotnet/akka.net#2595] opened 2017-04-10 18:26 UTC
We noticed a weird situation where after we closed 2 connections to our tcp server, the 3rd would connect but not handle any of the incoming communication.

I took the TcpEchoService.Server project ( *akka.net/src/examples/TcpEchoService.Server/* from master) and was able to recreate what we are seeing. It isn't a consistent number of times before it stops working.
It seems to be when the ```Console.WriteLine()``` comments are replaced with ```_log.Info()``` in the Echo actors.

I also added a Hocon configuration section to my app.config.

[logging-changes.zip](https://github.com/akkadotnet/akka.net/files/910998/logging-changes.zip)

My input:
```
$ telnet localhost 9001
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
test
test
exit
$ telnet localhost 9001
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
test
test
exit
Connection closed by foreign host.
$ telnet localhost 9001
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
test   <-- This doesn't get echoed back
exit   <-- This doesn't close the connection
```

My log (some repetitive logs trimmed out)
```
TCP server is listening on *:9001
ENTER to exit...
[DEBUG][4/10/2017 6:08:47 PM][Thread 0001][EventStream(echo-server-system)] Logger log1-DefaultLogger [DefaultLogger] started
[DEBUG][4/10/2017 6:08:47 PM][Thread 0001][EventStream(echo-server-system)] StandardOutLogger being removed
[DEBUG][4/10/2017 6:08:47 PM][Thread 0001][EventStream(echo-server-system)] Default Loggers started
[WARNING][4/10/2017 6:08:47 PM][Thread 0001][ActorSystem(echo-server-system)] NewtonSoftJsonSerializer has been detected as a default serializer. It will be obsoleted in Akka.NET starting from version 1.5 in the favor of Hyperion
[INFO][4/10/2017 6:08:55 PM][Thread 0006][[akka://echo-server-system/user/echo-service#150159752]] Remote address [::ffff:127.0.0.1]:61159 connected
[INFO][4/10/2017 6:08:59 PM][Thread 0004][[akka://echo-server-system/user/echo-service/$a#884462836]] Received 'test' from remote address [[::ffff:127.0.0.1]:61159]
[INFO][4/10/2017 6:09:28 PM][Thread 0005][[akka://echo-server-system/user/echo-service#150159752]] Remote address [::ffff:127.0.0.1]:63282 connected
[INFO][4/10/2017 6:09:30 PM][Thread 0003][[akka://echo-server-system/user/echo-service/$h#933074899]] Received 'test' from remote address [[::ffff:127.0.0.1]:63282]
[INFO][4/10/2017 6:09:31 PM][Thread 0004][[akka://echo-server-system/user/echo-service/$h#933074899]] Received 'exit' from remote address [[::ffff:127.0.0.1]:63282]
[DEBUG][4/10/2017 6:09:31 PM][Thread 0005][akka://echo-server-system/system/IO-TCP/selectors/$a/8] Monitored actor [[akka://echo-server-system/user/echo-service/$h#933074899]] terminated
[INFO][4/10/2017 6:09:31 PM][Thread 0009][akka://echo-server-system/system/IO-TCP/selectors/$a/8] Message ChannelAcceptable from akka://echo-server-system/deadLetters to akka://echo-server-system/system/IO-TCP/selectors/$a/8 was not delivered. 8 dead letters encountered.
[INFO][4/10/2017 6:09:32 PM][Thread 0005][[akka://echo-server-system/user/echo-service#150159752]] Remote address [::ffff:127.0.0.1]:63475 connected
[INFO][4/10/2017 6:09:33 PM][Thread 0004][[akka://echo-server-system/user/echo-service/$i#809585582]] Received 'test' from remote address [[::ffff:127.0.0.1]:63475]
[INFO][4/10/2017 6:09:34 PM][Thread 0009][[akka://echo-server-system/user/echo-service/$i#809585582]] Received 'exit' from remote address [[::ffff:127.0.0.1]:63475]
[DEBUG][4/10/2017 6:09:34 PM][Thread 0009][akka://echo-server-system/system/IO-TCP/selectors/$a/9] Monitored actor [[akka://echo-server-system/user/echo-service/$i#809585582]] terminated
[INFO][4/10/2017 6:09:34 PM][Thread 0009][akka://echo-server-system/system/IO-TCP/selectors/$a/9] Message ChannelAcceptable from akka://echo-server-system/deadLetters to akka://echo-server-system/system/IO-TCP/selectors/$a/9 was not delivered. 9 dead letters encountered.
[INFO][4/10/2017 6:09:35 PM][Thread 0004][[akka://echo-server-system/user/echo-service#150159752]] Remote address [::ffff:127.0.0.1]:63668 connected
[INFO][4/10/2017 6:09:36 PM][Thread 0005][[akka://echo-server-system/user/echo-service/$j#1525255361]] Received 'test' from remote address [[::ffff:127.0.0.1]:63668]
[INFO][4/10/2017 6:09:38 PM][Thread 0004][[akka://echo-server-system/user/echo-service/$j#1525255361]] Received 'exit' from remote address [[::ffff:127.0.0.1]:63668]
[DEBUG][4/10/2017 6:09:38 PM][Thread 0004][akka://echo-server-system/system/IO-TCP/selectors/$a/10] Monitored actor [[akka://echo-server-system/user/echo-service/$j#1525255361]] terminated
[INFO][4/10/2017 6:09:39 PM][Thread 0004][[akka://echo-server-system/user/echo-service#150159752]] Remote address [::ffff:127.0.0.1]:63989 connected
[INFO][4/10/2017 6:09:41 PM][Thread 0009][[akka://echo-server-system/user/echo-service/$k#1351190378]] Received 'test' from remote address [[::ffff:127.0.0.1]:63989]
[INFO][4/10/2017 6:09:43 PM][Thread 0003][[akka://echo-server-system/user/echo-service/$k#1351190378]] Received 'exit' from remote address [[::ffff:127.0.0.1]:63989]
[DEBUG][4/10/2017 6:09:43 PM][Thread 0006][akka://echo-server-system/system/IO-TCP/selectors/$a/11] Monitored actor [[akka://echo-server-system/user/echo-service/$k#1351190378]] terminated
[INFO][4/10/2017 6:09:44 PM][Thread 0009][[akka://echo-server-system/user/echo-service#150159752]] Remote address [::ffff:127.0.0.1]:64246 connected
[INFO][4/10/2017 6:09:45 PM][Thread 0013][[akka://echo-server-system/user/echo-service/$l#929552863]] Received 'test' from remote address [[::ffff:127.0.0.1]:64246]
[INFO][4/10/2017 6:09:46 PM][Thread 0012][[akka://echo-server-system/user/echo-service/$l#929552863]] Received 'exit' from remote address [[::ffff:127.0.0.1]:64246]
[DEBUG][4/10/2017 6:09:46 PM][Thread 0006][akka://echo-server-system/system/IO-TCP/selectors/$a/12] Monitored actor [[akka://echo-server-system/user/echo-service/$l#929552863]] terminated
```

I don't see anything in the logs (console) once it starts misbehaving. No connections, nor receives. If I kill the server with by ```Console.ReadKey()``` then the client connection also closes. So it seems that the client connected to something.

**Comment by spankr** [comment] 2017-04-10 19:53
I can get it to happen with stock (non modifications above) code but it does take more iterations of creating and closing connections.

**Comment by spankr** [comment] 2017-04-10 21:54
I noticed a **System.Net.Sockets.SocketException** being thrown right before things stopped working.

So, I traced it down to the Select() method in the ChannelRegistryImpl class. (_src/core/Akka/IO/SelectionHandler.cs_: line 348)

The logic catches the SockeException and then proceeds to clean up all the closed connections:
```
if (ex.SocketErrorCode == SocketError.NotSocket)
{
  // One of the sockets has been closed
   readable.Where(x => !x.Connected).ForEach(x => _read.Remove(x));
   writeable.Where(x => !x.Connected).ForEach(x => _write.Remove(x));
}
```
Based on the normal (non-exceptional) flow of logic above it, when each of these sockets is removed, the channel is told a message.

I don't fully understand the logic so I'd like to leave this for someone on the team but this change seems to work for me.
```
if (ex.SocketErrorCode == SocketError.NotSocket)
{
    // One of the sockets has been closed
    readable.Where(x => !x.Connected).ForEach(x => 
    {
        var channel = _read[x];
        if (channel.IsOpen())
            channel.Connection.Tell(ChannelReadable.Instance);
        else
            channel.Connection.Tell(ChannelAcceptable.Instance);
        _read.Remove(x);
    });
    writeable.Where(x => !x.Connected).ForEach(x => 
    {
        var channel = _write[x];
        if (channel.IsOpen())
            channel.Connection.Tell(ChannelWritable.Instance);
        else
            channel.Connection.Tell(ChannelConnectable.Instance);
        _write.Remove(x);
    });
}
```

I'd be inclined to just have the ```try {} catch (SocketException ex) {}``` just around the **Socket.Select()** line and iterate the removal/cleanup after the catch.

```
try
{
    Socket.Select(readable, writeable, null, 1);
}
catch (SocketException ex) when (ex.SocketErrorCode == SocketError.NotSocket)
{
  // One of the sockets has been closed
}

foreach (var socket in readable)
{
    var channel = _read[socket];
    if (channel.IsOpen())
        channel.Connection.Tell(ChannelReadable.Instance);
    else
        channel.Connection.Tell(ChannelAcceptable.Instance);
    _read.Remove(socket);
}
foreach (var socket in writeable)
{
    var channel = _write[socket];
    if (channel.IsOpen())
        channel.Connection.Tell(ChannelWritable.Instance);
    else
        channel.Connection.Tell(ChannelConnectable.Instance);
    _write.Remove(socket);
}
Execute(Select);
```

The added bonus here is that if a SocketException was thrown for any other SocketErrorCode, they wouldn't be eaten by the catch.

**Comment by Danthar** [comment] 2017-04-11 07:28
@Horusiath Does the fixes you made in the akka.io branch cover this ?

**Comment by spankr** [comment] 2017-04-19 16:06
I was reading through #1335 and if the Akka.io branch is slated for the 1.3.0 milestone, it sounds like it will also resolve this issue. It looks like that akka.io branch is enough of a rewrite that #2615 is an obsolete change once that is merged.

**Comment by alexvaluyskiy** [comment] 2017-07-22 11:07
@Horusiath have you fixed it?

**Comment by Horusiath** [comment] 2017-07-22 11:12
Needs to be verified.

**Comment by IgorFedchenko** [comment] 2020-05-06 13:26
The code is pretty much rewritten since this issue was found. And I could not reproduce the issue after 50+ iterations... So I guess we can close this @Aaronontheweb 

Btw `TcpEchoService.Server` sample was not included in solution and was still targeting full framework - so I have updated it and included back to sln. And fixed `DeathPactException` when server stopped manually.

So added PR to close this issue.

**Closed** 2020-05-06 17:05 UTC
Labels: akka-io, potential bug
